export const logHandler: any = () => {}
export const errorHandler: any = () => {}
export const exportHandler: any = () => {}
export const taskCreateHandler: any = () => {}
export const taskListHandler: any = () => {}
export const taskGetHandler: any = () => {}
export const taskUpdateHandler: any = () => {}
export const taskDirHandler: any = () => {}
export const completionHandler: any = () => {}
