import {
  type SaturationType,
  type GemSetup,
  type MasterProducer,
} from './masters-database';

function makeGem(
  drumDesc: string, drumSat: SaturationType, drumDrive: number,
  bassDesc: string, bassSat: SaturationType, bassDrive: number,
  gtrDesc: string, gtrSat: SaturationType, gtrDrive: number, gtrWidth: number,
  voxDesc: string, voxSat: SaturationType, voxDrive: number,
  synDesc: string, synSat: SaturationType, synDrive: number, synWidth: number,
  volDrums = 0.5, volBass = 0.0, volGtr = 0.8, volVox = 1.2, volSyn = -3.5
): GemSetup {
  return {
    drums: {
      volumeDb: volDrums,
      eq: { sub: 2.0, punch: 2.5, attack: 3.0, air: 1.5 },
      saturation: drumSat,
      drive: drumDrive,
      compRatio: 3.5,
      compAttack: 25,
      compRelease: 120,
      description: drumDesc,
    },
    bass: {
      volumeDb: volBass,
      eq: { subBass: 2.5, grit: 2.0, cutMids: -1.5, clarity: 1.8 },
      saturation: bassSat,
      drive: bassDrive,
      compRatio: 4.0,
      compAttack: 15,
      compRelease: 90,
      description: bassDesc,
    },
    guitars: {
      volumeDb: volGtr,
      eq: { lowCut: 85, body: 1.8, bite: 2.5, sheen: 2.0 },
      saturation: gtrSat,
      drive: gtrDrive,
      stereoWidth: gtrWidth,
      description: gtrDesc,
    },
    vocals: {
      volumeDb: volVox,
      eq: { body: 1.2, clarity: 2.0, presence: 2.5, air: 3.0 },
      saturation: voxSat,
      drive: voxDrive,
      compRatio: 3.5,
      compAttack: 12,
      compRelease: 100,
      description: voxDesc,
    },
    synthsFx: {
      volumeDb: volSyn,
      eq: { lowMids: 0.8, presence: 1.5, air: 2.0 },
      saturation: synSat,
      drive: synDrive,
      stereoWidth: synWidth,
      description: synDesc,
    },
  };
}

export const PRODUCERS_MIDDLE: MasterProducer[] = [
  // 3. MARTIN BIRCH
  {
    id: 'martin-birch',
    name: 'MARTIN BIRCH',
    title: 'The Headmaster of Heavy Metal (NWOBHM)',
    category: 'metal_rock',
    era: '70s & 80s Classic Heavy Metal & Hard Rock',
    country: 'United Kingdom',
    bio: 'O arquiteto sonoro supremo do Iron Maiden, Black Sabbath da era Dio, Deep Purple, Rainbow e Whitesnake. Mestre das gravações em fita analógica quente e dinâmica natural.',
    albums: [
      {
        id: 'birch-number',
        albumTitle: 'The Number of the Beast',
        band: 'Iron Maiden',
        year: 1982,
        hardwareChain: 'Neve 8068 + Studer A800 24-Track Tape + EMT 140 Plate + Pultec EQP-1A',
        soundSignature: 'A bíblia do NWOBHM: baixo estalado na cara, guitarras dobradas em estéreo amplo, bateria dinâmica e vocal operático.',
        targetLufs: -9.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 115, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3000, biteGainDb: 2.5, cabHighCutHz: 5800, distortionGain: 0.70, stereoSpread: 1.35, description: 'Dave Murray & Adrian Smith Marshalls JMP 50W valvulados com overdrive orgânico britânico e solos líricos.' },
        eq10Band: { hz30: -1.5, hz60: 1.5, hz120: 2.0, hz250: 0.5, hz500: 1.0, hz1000: 1.5, hz2500: 2.0, hz4000: 2.5, hz8000: 2.0, hz16000: 1.2 },
        saturation: { type: 'tape_warmth', drive: 0.65 },
        compressor: { threshold: -18, ratio: 2.8, attack: 35, release: 150, knee: 5 },
        stereoWidth: 1.35,
        gemSetup: makeGem(
          'Bateria Clive Burr com dinâmica 100% natural, pratos Zildjian brilhantes e chimbal orgânico.', 'tape_warmth', 0.65,
          'Baixo Precision Steve Harris tocado com dois dedos, clank metálico em 2.5kHz e DI valvulado.', 'neve_tube', 0.75,
          'Guitarras Dave Murray e Adrian Smith em Marshalls JMP valvulados em estéreo puro.', 'marshall_jcm800', 0.70, 1.35,
          'Bruce Dickinson em sua estreia: vocais operáticos com compressão analógica suave.', 'la2a_opto', 0.65,
          'Efeitos sonoros teatrais (intro de Barry Clayton).', 'tape_warmth', 0.50, 1.40,
          0.5, 2.0, 0.8, 2.5, -6.0
        ),
      },
      {
        id: 'birch-powerslave',
        albumTitle: 'Powerslave',
        band: 'Iron Maiden',
        year: 1984,
        hardwareChain: 'Compass Point Studios + Neve 8078 + Studer A800 + EMT 250 Reverb',
        soundSignature: 'O ápice sonoro do Iron Maiden: timbres egípcios épicos, o baixo galopante mais famoso do mundo e bateria viva.',
        targetLufs: -9.0,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 850, midScoopGainDb: 0.0, bitePresenceHz: 3200, biteGainDb: 2.8, cabHighCutHz: 6000, distortionGain: 0.72, stereoSpread: 1.38, description: 'Guitarras clássicas do Maiden gravadas em Nassau com Marshalls JCM800 e delays analógicos.' },
        eq10Band: { hz30: -1.2, hz60: 1.8, hz120: 2.2, hz250: 0.2, hz500: 0.8, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'tape_warmth', drive: 0.68 },
        compressor: { threshold: -17, ratio: 3.0, attack: 30, release: 140, knee: 4 },
        stereoWidth: 1.38,
        gemSetup: makeGem(
          'Bateria Nicko McBrain gravada na sala viva do Compass Point com caixa aberta e bumbo de madeira.', 'tape_warmth', 0.68,
          'Baixo Steve Harris com ataque percussivo em 3kHz e graves sólidos.', 'neve_tube', 0.75,
          'Guitarras gêmeas Murray/Smith com harmonia de terças perfeitas.', 'marshall_jcm800', 0.72, 1.38,
          'Vocais triunfais de Bruce Dickinson em Aces High e Rime of the Ancient Mariner.', 'la2a_opto', 0.70,
          'Efeitos marítimos e ventos místicos em Rime of the Ancient Mariner.', 'tape_warmth', 0.50, 1.50,
          0.8, 1.8, 1.0, 2.2, -4.0
        ),
      },
      {
        id: 'birch-heavenandhell',
        albumTitle: 'Heaven and Hell',
        band: 'Black Sabbath (Dio Era)',
        year: 1980,
        hardwareChain: 'Criteria Studios + Neve 8068 + Fairchild 670 + EMT 140',
        soundSignature: 'A ressurreição mística do Black Sabbath com Ronnie James Dio: guitarras pesadas e majestosas de Tony Iommi e o baixo lendário de Geezer Butler.',
        targetLufs: -9.0,
        tuningSignature: { standardName: 'Eb Standard (Eb-Ab-Db-Gb-Bb-Eb / A=415.3Hz)', baseFreqA4Hz: 415.3, centOffset: -100, harmonicResonanceCenterHz: 77.78 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 112, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3000, biteGainDb: 2.5, cabHighCutHz: 5900, distortionGain: 0.72, stereoSpread: 1.38, description: 'Tony Iommi com amplificadores Laney Supergroup e Marshall JMP modificados em afinação Eb.' },
        eq10Band: { hz30: -1.0, hz60: 2.2, hz120: 2.0, hz250: 0.0, hz500: 0.5, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 2.0, hz16000: 1.2 },
        saturation: { type: 'tape_warmth', drive: 0.68 },
        compressor: { threshold: -17, ratio: 2.8, attack: 32, release: 140, knee: 4 },
        stereoWidth: 1.38,
        gemSetup: makeGem(
          'Bateria Bill Ward dinâmica e percussiva.', 'tape_warmth', 0.68,
          'Baixo Geezer Butler com o icônico riff de Heaven and Hell.', 'neve_tube', 0.75,
          'Riffs imortais de Tony Iommi em Neon Knights e Die Young.', 'marshall_jcm800', 0.75, 1.38,
          'Ronnie James Dio com vocais divinos e presença imponente.', 'la2a_opto', 0.75,
          'Teclados celestiais de Geoff Nicholls e efeitos arcanos.', 'tape_warmth', 0.50, 1.45,
          1.0, 1.2, 1.2, 2.2, -3.0
        ),
      },
    ],
  },

  // 4. FLEMMING RASMUSSEN
  {
    id: 'flemming-rasmussen',
    name: 'FLEMMING RASMUSSEN',
    title: 'The Sweet Silence Thrash Alchemist',
    category: 'metal_rock',
    era: '80s Thrash Metal & Speed Metal Era',
    country: 'Denmark',
    bio: 'Engenheiro e produtor da trilogia dourada do Metallica (Ride the Lightning, Master of Puppets e ...And Justice for All) e Blind Guardian no lendário Sweet Silence Studios em Copenhague.',
    albums: [
      {
        id: 'rasmussen-puppets',
        albumTitle: 'Master of Puppets',
        band: 'Metallica',
        year: 1986,
        hardwareChain: 'Sweet Silence Studios + Trident A-Range + Mesa Boogie Mark IIC+ + Studer A800',
        soundSignature: 'A obra-prima do Thrash Metal: EQ cavado em V nos amplificadores, palhetada alternada cirúrgica e clareza acústica.',
        targetLufs: -8.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'mesa_rectifier', cabResonanceHz: 112, midScoopHz: 750, midScoopGainDb: -3.5, bitePresenceHz: 3500, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.85, stereoSpread: 1.42, description: 'Mesa Boogie Mark IIC+ modificado como pré-amp nos power amps Marshall com corte em V cirúrgico e palhetada rápida.' },
        eq10Band: { hz30: -1.0, hz60: 2.5, hz120: 1.5, hz250: -1.5, hz500: -0.8, hz1000: 1.0, hz2500: 2.2, hz4000: 2.8, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'tape_warmth', drive: 0.70 },
        compressor: { threshold: -16, ratio: 3.5, attack: 20, release: 90, knee: 3 },
        stereoWidth: 1.42,
        gemSetup: makeGem(
          'Bateria Lars Ulrich com bumbo de madeira Tama, caixa Ludwig Black Beauty e reverberação de estúdio dinamarquês.', 'tape_warmth', 0.70,
          'Baixo Cliff Burton com Rickenbacker e distorção Big Muff/Wah nos momentos solo.', 'bigmuff_bass_fuzz', 0.75,
          'Guitarras Hetfield/Hammett com Mesa Boogie Mark IIC+ modificado como pré-amp nos Marshalls.', 'mesa_rectifier', 0.80, 1.42,
          'Vocais ferozes e jovens de James Hetfield com microfone Shure SM7.', 'la2a_opto', 0.65,
          'Harmonizações acústicas clássicas em Battery e Master of Puppets.', 'tape_warmth', 0.50, 1.50,
          1.5, 0.2, 1.2, 1.5, -4.0
        ),
      },
      {
        id: 'rasmussen-lightning',
        albumTitle: 'Ride the Lightning',
        band: 'Metallica',
        year: 1984,
        hardwareChain: 'Sweet Silence Studios + Trident Console + Marshall JCM800 + Studer A800 (Tape Sped Up)',
        soundSignature: 'Thrash Metal elétrico e cru com fita acelerada em +1/4 de tom (A=445Hz) e guitarras com Tube Screamer.',
        targetLufs: -9.0,
        tuningSignature: { standardName: 'Sped-up Varispeed Tape (A=445.0Hz)', baseFreqA4Hz: 445.0, centOffset: +20, harmonicResonanceCenterHz: 83.35 },
        guitarToneprint: { ampModel: 'ts9_screamer', cabResonanceHz: 118, midScoopHz: 850, midScoopGainDb: -1.0, bitePresenceHz: 3600, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.78, stereoSpread: 1.38, description: 'Ibanez TS9 Tube Screamer empurrando Marshall JCM800 valvulado com agudos elétricos cortantes.' },
        eq10Band: { hz30: -1.2, hz60: 2.0, hz120: 1.5, hz250: -1.0, hz500: -0.5, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'tape_warmth', drive: 0.68 },
        compressor: { threshold: -17, ratio: 3.2, attack: 22, release: 100, knee: 4 },
        stereoWidth: 1.38,
        gemSetup: makeGem(
          'Bateria acústica veloz com caixa reverberada e pratos vivos.', 'tape_warmth', 0.68,
          'Baixo Cliff Burton melódico e presente em For Whom the Bell Tolls.', 'bigmuff_bass_fuzz', 0.70,
          'Rhythm guitars afiadas com Tubescreamer empurrando os Marshalls.', 'ts9_screamer', 0.78, 1.38,
          'Vocais rasgados com reverb clássico.', 'la2a_opto', 0.65,
          'Introduções acústicas de Fade to Black e Fight Fire With Fire.', 'tape_warmth', 0.50, 1.40,
          1.0, 0.5, 1.0, 1.6, -5.0
        ),
      },
      {
        id: 'rasmussen-blindguardian',
        albumTitle: 'Imaginations from the Other Side',
        band: 'Blind Guardian',
        year: 1995,
        hardwareChain: 'Sweet Silence Studios + Trident A-Range + Mesa Boogie + Studer Tape',
        soundSignature: 'A obra-prima do Speed/Power Metal épico: coros monumentais de 50 vozes, bumbos duplos velozes e guitarras medievais.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'mesa_rectifier', cabResonanceHz: 108, midScoopHz: 700, midScoopGainDb: -1.2, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.82, stereoSpread: 1.45, description: 'André Olbrich e Marcus Siepen com guitarras com timbre lírico e solos medievais em Mesa Boogie.' },
        eq10Band: { hz30: -0.8, hz60: 2.5, hz120: 1.5, hz250: -0.8, hz500: 0.2, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'tape_warmth', drive: 0.72 },
        compressor: { threshold: -14, ratio: 3.5, attack: 20, release: 85, knee: 3 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria Thomen Stauch rápida como um trovão com pedal duplo cirúrgico.', 'tape_warmth', 0.78,
          'Baixo Hansi Kürsch com ataque firme.', 'ampeg_svt', 0.70,
          'Guitarras com dezenas de camadas e melodias barrocas.', 'mesa_rectifier', 0.80, 1.45,
          'Coros operáticos gigantes e os vocais rasgados de Hansi Kürsch.', 'la2a_opto', 0.75,
          'Flautas, gaitas de fole e orquestrações de fantasia.', 'pultec_tube', 0.60, 1.65,
          1.8, 0.0, 1.2, 2.0, 0.0
        ),
      },
    ],
  },

  // 5. BOB ROCK
  {
    id: 'bob-rock',
    name: 'BOB ROCK',
    title: 'The Heavy Stadium Sound Master',
    category: 'metal_rock',
    era: '80s, 90s & 2000s Stadium Rock & Modern Metal',
    country: 'Canada / USA',
    bio: 'Produtor do Metallica Black Album, Mötley Crüe Dr. Feelgood e The Cult. Criador do som de bateria de estádio e paredes de guitarra com mais de 40 camadas.',
    albums: [
      {
        id: 'rock-blackalbum',
        albumTitle: 'Metallica (The Black Album)',
        band: 'Metallica',
        year: 1991,
        hardwareChain: 'One On One Studios + Neve 8078 + SSL 4000 + Studer A800 + UREI 1176',
        soundSignature: 'O padrão-ouro mundial de produção de estúdio: bumbos com impacto massivo em 60Hz, baixo audível e guitarras com corpo gigante.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'mesa_rectifier', cabResonanceHz: 108, midScoopHz: 650, midScoopGainDb: -2.8, bitePresenceHz: 3200, biteGainDb: 3.0, cabHighCutHz: 6300, distortionGain: 0.85, stereoSpread: 1.46, description: 'Paredão James Hetfield: Mesa Boogie Mark IIC+ e ADA MP-1 com corpo massivo de 4x12 e agudos polidos.' },
        eq10Band: { hz30: 0.0, hz60: 3.2, hz120: 1.8, hz250: -0.8, hz500: 0.0, hz1000: 1.2, hz2500: 1.8, hz4000: 2.5, hz8000: 2.2, hz16000: 1.8 },
        saturation: { type: 'shadow_hills', drive: 0.70 },
        compressor: { threshold: -15, ratio: 3.2, attack: 25, release: 100, knee: 4 },
        stereoWidth: 1.46,
        gemSetup: makeGem(
          'Bateria Lars Ulrich com 40 microfones, caixa de sino de bronze, bumbo colossal e sala gigante.', 'tape_warmth', 0.75,
          'Baixo Jason Newsted dobrando as guitarras com Spector 5 cordas e amplificador SVT.', 'ampeg_svt', 0.75,
          'Paredão Hetfield com 4 amplificadores combinados (Mesa Boogie Mark IIC+, Marshall e ADA MP-1).', 'mesa_rectifier', 0.80, 1.46,
          'James Hetfield aprendendo a cantar melodias com microfone Shure SM7B e Neve 1073.', 'la2a_opto', 0.70,
          'Arranjos orquestrais de Michael Kamen (Nothing Else Matters).', 'pultec_tube', 0.60, 1.65,
          2.5, 0.0, 1.0, 2.0, -3.0
        ),
      },
      {
        id: 'rock-drfeelgood',
        albumTitle: 'Dr. Feelgood',
        band: 'Mötley Crüe',
        year: 1989,
        hardwareChain: 'Little Mountain Sound Studios + SSL 4000 + Neve 1073 + Studer A800',
        soundSignature: 'A maior produção de Glam/Hard Rock dos anos 80: bumbo que chuta o peito, baixo gigantesco e guitarras com ganho luxuoso.',
        targetLufs: -7.8,
        tuningSignature: { standardName: 'D Standard (D-G-C-F-A-D)', baseFreqA4Hz: 440.0, centOffset: -200, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 750, midScoopGainDb: -1.0, bitePresenceHz: 3200, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.80, stereoSpread: 1.45, description: 'Mick Mars com Marshalls JCM800 modificados por José Arredondo e guitarras afinadas em D Standard.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.8, hz250: -0.8, hz500: 0.2, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'ssl_vca', drive: 0.72 },
        compressor: { threshold: -14, ratio: 3.4, attack: 22, release: 90, knee: 3 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria Tommy Lee monstruosa com caixa ensurdecedora e bumbo pesado.', 'ssl_vca', 0.80,
          'Baixo Nikki Sixx com graves densos que sustentam o groove.', 'ampeg_svt', 0.75,
          'Guitarras de Mick Mars em afinação D pesada e cortante em Dr. Feelgood e Kickstart My Heart.', 'marshall_jcm800', 0.80, 1.45,
          'Vince Neil com vocais agudos dobrados em estéreo.', 'la2a_opto', 0.72,
          'Sirenes de ambulância, buzinas de moto e efeitos especiais.', 'tape_warmth', 0.50, 1.50,
          2.0, 0.2, 1.2, 1.8, -4.0
        ),
      },
    ],
  },

  // 6. ANDY SNEAP
  {
    id: 'andy-sneap',
    name: 'ANDY SNEAP',
    title: 'The Modern Thrash & Heavy Architect',
    category: 'metal_rock',
    era: '2000s, 2010s & 2020s Metal Renaissance',
    country: 'United Kingdom',
    bio: 'Produtor e guitarrista que revitalizou o som do Judas Priest (Firepower e Invincible Shield), Accept, Megadeth, Saxon, Arch Enemy e Testament.',
    albums: [
      {
        id: 'sneap-firepower',
        albumTitle: 'Firepower',
        band: 'Judas Priest',
        year: 2018,
        hardwareChain: 'Backstage Studios + SSL Duality + Neve 1073 + Empirical Labs Distressor',
        soundSignature: 'A masterização moderna perfeita de Heavy Metal: punch cortante, clareza cirúrgica em todas as frequências e presença vocal imponente.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'Standard E / Drop D (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'peavey_5150', cabResonanceHz: 104, midScoopHz: 720, midScoopGainDb: -1.5, bitePresenceHz: 3400, biteGainDb: 3.2, cabHighCutHz: 6300, distortionGain: 0.88, stereoSpread: 1.44, description: 'EVH 5150 III com profiling digital de alta fidelidade e saturação de válvula moderna com palhetada articulada.' },
        eq10Band: { hz30: -0.5, hz60: 2.5, hz120: 1.2, hz250: -1.0, hz500: 0.2, hz1000: 1.2, hz2500: 2.0, hz4000: 2.8, hz8000: 2.5, hz16000: 2.0 },
        saturation: { type: 'distressor_nuke', drive: 0.72 },
        compressor: { threshold: -13, ratio: 3.6, attack: 20, release: 80, knee: 3 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria Scott Travis com sample blending imperceptível, caixa com impacto brutal e pratos ultra-limpos.', 'distressor_nuke', 0.75,
          'Baixo Ian Hill com corte em duas bandas (sub limpo + distorção no médio).', 'darkglass_b7k', 0.75,
          'Dobras de guitarras Richie Faulkner e Glenn Tipton com EVH 5150 III e Kemper profiling.', 'peavey_5150', 0.80, 1.44,
          'Rob Halford com processamento moderno, de-esser cirúrgico e ar de 10kHz.', 'la2a_opto', 0.72,
          'Efeitos futuristas e pads discretos.', 'ssl_vca', 0.50, 1.45,
          1.8, 0.0, 1.2, 1.8, -4.0
        ),
      },
      {
        id: 'sneap-invincible',
        albumTitle: 'Invincible Shield',
        band: 'Judas Priest',
        year: 2024,
        hardwareChain: 'Backstage Studios + SSL Duality + Neve 1073 + Shadow Hills Mastering Compressor',
        soundSignature: 'A continuação do ápice moderno do Judas Priest: guitarras incandescentes, solos virtuosísticos e Rob Halford imortal.',
        targetLufs: -6.5,
        tuningSignature: { standardName: 'Standard E / Drop D (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'peavey_5150', cabResonanceHz: 104, midScoopHz: 700, midScoopGainDb: -1.2, bitePresenceHz: 3500, biteGainDb: 3.5, cabHighCutHz: 6400, distortionGain: 0.90, stereoSpread: 1.46, description: 'Richie Faulkner com EVH 5150 e Gibson Flying V com agudos cristalinos e palhetada relâmpago.' },
        eq10Band: { hz30: -0.5, hz60: 2.6, hz120: 1.4, hz250: -1.0, hz500: 0.2, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.8, hz16000: 2.2 },
        saturation: { type: 'shadow_hills', drive: 0.74 },
        compressor: { threshold: -13, ratio: 3.8, attack: 18, release: 80, knee: 3 },
        stereoWidth: 1.46,
        gemSetup: makeGem(
          'Bateria Scott Travis rápida e impecável em Panic Attack.', 'distressor_nuke', 0.80,
          'Baixo Ian Hill preciso e consistente.', 'darkglass_b7k', 0.75,
          'Guitarras afiadas com duelos de solos em Invincible Shield e The Serpent and the King.', 'peavey_5150', 0.82, 1.46,
          'Rob Halford com alcance vocal impressionante para 72 anos.', 'la2a_opto', 0.75,
          'Sintetizadores retrô dos anos 80 na intro de Panic Attack.', 'ssl_vca', 0.55, 1.55,
          1.8, 0.0, 1.2, 1.8, -2.5
        ),
      },
    ],
  },

  // 7. JENS BOGREN
  {
    id: 'jens-bogren',
    name: 'JENS BOGREN',
    title: 'Fascination Street Nordic Metal Legend',
    category: 'metal_rock',
    era: '2000s, 2010s & 2020s Progressive, Melodic Death & Modern Metal',
    country: 'Sweden',
    bio: 'Produtor e masterizador de Angra (ØMNI, Cycles of Pain, Secret Garden), Sepultura (Quadra, Machine Messiah), Opeth (Ghost Reveries), Symphony X, Arch Enemy e Dimmu Borgir.',
    albums: [
      {
        id: 'bogren-omni',
        albumTitle: 'ØMNI',
        band: 'Angra',
        year: 2018,
        hardwareChain: 'Fascination Street Studios + SSL 4000 G+ + Manley Massive Passive + Shadow Hills',
        soundSignature: 'Power/Prog Metal sinfônico perfeito: percussão brasileira integrada a bumbos duplos velozes, orquestrações ricas e guitarras neoclássicas.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'Standard E / Drop D (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'soldano_slo100', cabResonanceHz: 102, midScoopHz: 700, midScoopGainDb: -1.0, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6400, distortionGain: 0.82, stereoSpread: 1.48, description: 'Guitarras Rafael Bittencourt e Marcelo Barbosa com distorção boutique Soldano/Bogner, timbre limpo e definido para sweep picking.' },
        eq10Band: { hz30: 0.0, hz60: 2.5, hz120: 1.5, hz250: -0.8, hz500: 0.2, hz1000: 1.2, hz2500: 2.0, hz4000: 2.8, hz8000: 2.8, hz16000: 2.2 },
        saturation: { type: 'shadow_hills', drive: 0.70 },
        compressor: { threshold: -13, ratio: 3.5, attack: 22, release: 85, knee: 3 },
        stereoWidth: 1.48,
        gemSetup: makeGem(
          'Bateria Bruno Valverde com dinâmicas fusion, bumbos duplos rápidos e percussões brasileiras.', 'ssl_vca', 0.75,
          'Baixo Felipe Andreoli com baixo 6 cordas Ibanez e timbre hi-tech ultra-definido.', 'darkglass_b7k', 0.75,
          'Guitarras Rafael Bittencourt e Marcelo Barbosa com técnica impecável e timbres modernos.', 'peavey_5150', 0.78, 1.48,
          'Fabio Lione com vocais operáticos de tenor e participação de Sandy.', 'la2a_opto', 0.72,
          'Arranjos orquestrais épicos e camadas de sintetizador amplas.', 'pultec_tube', 0.65, 1.70,
          1.5, 0.0, 1.0, 1.8, 0.5
        ),
      },
      {
        id: 'bogren-cyclesofpain',
        albumTitle: 'Cycles of Pain',
        band: 'Angra',
        year: 2023,
        hardwareChain: 'Fascination Street Studios + SSL Duality + Shadow Hills + Bricasti M7',
        soundSignature: 'Power/Prog Metal maduro e dinâmico: arranjos orquestrais profundos, percussão afro-brasileira e solos líricos.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'Standard E / Drop D (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'soldano_slo100', cabResonanceHz: 102, midScoopHz: 720, midScoopGainDb: -1.0, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6300, distortionGain: 0.82, stereoSpread: 1.46, description: 'Guitarras de Rafael e Marcelo com riqueza harmônica e dinâmicas sutis.' },
        eq10Band: { hz30: 0.0, hz60: 2.4, hz120: 1.5, hz250: -0.8, hz500: 0.2, hz1000: 1.2, hz2500: 2.0, hz4000: 2.6, hz8000: 2.8, hz16000: 2.2 },
        saturation: { type: 'shadow_hills', drive: 0.72 },
        compressor: { threshold: -13, ratio: 3.4, attack: 22, release: 85, knee: 3 },
        stereoWidth: 1.46,
        gemSetup: makeGem(
          'Bateria Bruno Valverde sofisticada e veloz.', 'ssl_vca', 0.75,
          'Baixo Felipe Andreoli com definição cristalina.', 'darkglass_b7k', 0.75,
          'Guitarras neoclássicas com timbres quentes e definidos.', 'soldano_slo100', 0.78, 1.46,
          'Vocais Fabio Lione e participações de Lenine e Amanda Somerville.', 'la2a_opto', 0.72,
          'Orquestrações clássicas e percussões ricas.', 'pultec_tube', 0.65, 1.70,
          1.5, 0.0, 1.0, 1.8, 0.5
        ),
      },
      {
        id: 'bogren-quadra',
        albumTitle: 'Quadra',
        band: 'Sepultura',
        year: 2020,
        hardwareChain: 'Fascination Street Studios + SSL Duality + Empirical Labs Distressor + Manley',
        soundSignature: 'Thrash/Prog tribal colossal: bateria explosiva de Eloy Casagrande, afinações em Drop B e orquestrações dramáticas.',
        targetLufs: -6.5,
        tuningSignature: { standardName: 'Drop B (B-F#-B-E-G#-C#)', baseFreqA4Hz: 440.0, centOffset: -300, harmonicResonanceCenterHz: 61.74 },
        guitarToneprint: { ampModel: 'peavey_5150', cabResonanceHz: 90, midScoopHz: 680, midScoopGainDb: -1.8, bitePresenceHz: 3500, biteGainDb: 3.5, cabHighCutHz: 6200, distortionGain: 0.90, stereoSpread: 1.46, description: 'Andreas Kisser em Drop B com distorção pesadíssima EVH 5150 III e timbres cortantes.' },
        eq10Band: { hz30: 0.2, hz60: 3.0, hz120: 1.8, hz250: -1.0, hz500: 0.0, hz1000: 1.5, hz2500: 2.2, hz4000: 3.0, hz8000: 2.8, hz16000: 2.0 },
        saturation: { type: 'distressor_nuke', drive: 0.75 },
        compressor: { threshold: -12, ratio: 3.8, attack: 18, release: 75, knee: 3 },
        stereoWidth: 1.46,
        gemSetup: makeGem(
          'Bateria monumental de Eloy Casagrande com impacto devastador e técnica incomparável.', 'distressor_nuke', 0.80,
          'Baixo Paulo Jr. em 5 cordas sustentando o peso sísmico.', 'darkglass_b7k', 0.78,
          'Guitarras em Drop B com riffs cirúrgicos e agressividade pura.', 'peavey_5150', 0.82, 1.46,
          'Vocais furiosos de Derrick Green com presença cortante.', 'distressor_nuke', 0.75,
          'Percussões tribais brasileiras e orquestrações clássicas.', 'ssl_vca', 0.60, 1.55,
          2.0, 0.2, 1.2, 1.6, -1.0
        ),
      },
    ],
  },

  // 8. GEORGE MARINO
  {
    id: 'george-marino',
    name: 'GEORGE MARINO',
    title: 'Sterling Sound Analog Golden Legend',
    category: 'metal_rock',
    era: '80s & 90s Golden Mastering Era',
    country: 'USA',
    bio: 'Engenheiro-chefe da Sterling Sound em Nova York por mais de 30 anos. Masterizou Back in Black do AC/DC e Appetite for Destruction do Guns N\' Roses.',
    albums: [
      {
        id: 'marino-backinblack',
        albumTitle: 'Back in Black',
        band: 'AC/DC',
        year: 1980,
        hardwareChain: 'Sterling Sound Custom Console + Neumann SAL 74B + Fairchild 670 + Pultec EQ',
        soundSignature: 'A masterização de Rock definitiva de todos os tempos: guitarras SG e Les Paul em Marshall com dinâmica aberta e bumbo com ar.',
        targetLufs: -9.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 2800, biteGainDb: 2.2, cabHighCutHz: 5800, distortionGain: 0.65, stereoSpread: 1.36, description: 'Angus e Malcolm Young em amplificadores Marshall JTM45 e Super Lead 100W no volume máximo com crunch valvulado puro.' },
        eq10Band: { hz30: -1.8, hz60: 1.8, hz120: 2.2, hz250: 0.0, hz500: 0.8, hz1000: 1.2, hz2500: 1.8, hz4000: 2.2, hz8000: 1.8, hz16000: 1.0 },
        saturation: { type: 'neve_tube', drive: 0.60 },
        compressor: { threshold: -18, ratio: 2.5, attack: 35, release: 150, knee: 5 },
        stereoWidth: 1.36,
        gemSetup: makeGem(
          'Bateria Phil Rudd: o metrônomo humano com caixa no 2 e 4 e bumbo sem frescuras.', 'tape_warmth', 0.60,
          'Baixo Cliff Williams marcando as notas raiz com precisão absoluta.', 'ampeg_svt', 0.60,
          'Guitarras Angus e Malcolm Young divididas 100% L e R nos Marshalls sem nenhum pedal.', 'marshall_jcm800', 0.65, 1.36,
          'Brian Johnson com vocais estridentes e agudos cortantes.', 'la2a_opto', 0.60,
          'O icônico sino de Hells Bells e ambiência de Nassau.', 'tape_warmth', 0.45, 1.40,
          1.5, -0.5, 1.8, 1.5, -12.0
        ),
      },
      {
        id: 'marino-appetite',
        albumTitle: 'Appetite for Destruction',
        band: 'Guns N\' Roses',
        year: 1987,
        hardwareChain: 'Sterling Sound + Neumann Lathe + Pultec EQP-1A + UREI 1176',
        soundSignature: 'Sleaze Rock perigoso e visceral: guitarras com overdrive rasgado, baixo com palhetada metálica e voz rouca penetrante.',
        targetLufs: -8.8,
        tuningSignature: { standardName: 'Eb Standard (Eb-Ab-Db-Gb-Bb-Eb / A=415.3Hz)', baseFreqA4Hz: 415.3, centOffset: -100, harmonicResonanceCenterHz: 77.78 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 114, midScoopHz: 700, midScoopGainDb: -0.8, bitePresenceHz: 3200, biteGainDb: 3.0, cabHighCutHz: 6000, distortionGain: 0.78, stereoSpread: 1.40, description: 'Slash Marshall SIR #36 modificado (JTM45 com estágio de ganho extra) + Les Paul com captadores Alnico II Pro.' },
        eq10Band: { hz30: -1.0, hz60: 2.2, hz120: 1.8, hz250: -0.5, hz500: 0.5, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'ssl_vca', drive: 0.65 },
        compressor: { threshold: -16, ratio: 3.0, attack: 28, release: 110, knee: 4 },
        stereoWidth: 1.40,
        gemSetup: makeGem(
          'Bateria Steven Adler com swing funk/rock e caixa aberta.', 'tape_warmth', 0.65,
          'Baixo Duff McKagan com palhetada aguda, chorus analógico e corpo de Fender PJ.', 'sansamp_di', 0.70,
          'Guitarras Slash e Izzy Stradlin com Les Paul e Marshall JCM800 modificado.', 'marshall_jcm800', 0.75, 1.40,
          'Axl Rose com vocais duplos raspados e alcance inacreditável.', 'la2a_opto', 0.70,
          'Sirenes, ruídos de rua e assobios em estéreo.', 'tape_warmth', 0.50, 1.45,
          1.2, 0.0, 1.5, 1.8, -6.0
        ),
      },
    ],
  },

  // 9. RICK RUBIN
  {
    id: 'rick-rubin',
    name: 'RICK RUBIN',
    title: 'The Reductive Audio Shaman',
    category: 'metal_rock',
    era: '80s, 90s & 2000s Raw Power & Stripped-Down Energy',
    country: 'USA',
    bio: 'Produtor lendário do Slayer (Reign in Blood, South of Heaven, Seasons in the Abyss), System of a Down (Toxicity, Mezmerize), Slipknot (Vol. 3), Red Hot Chili Peppers e Metallica (Death Magnetic).',
    albums: [
      {
        id: 'rubin-reigninblood',
        albumTitle: 'Reign in Blood',
        band: 'Slayer',
        year: 1986,
        hardwareChain: 'Hit City West + Neve 8068 + DBX 160 + Studer A800',
        soundSignature: '28 minutos de velocidade pura: bateria seca sem reverb, guitarras rasgando os alto-falantes e vocais na cara.',
        targetLufs: -8.0,
        tuningSignature: { standardName: 'Eb Standard (A=415.3Hz)', baseFreqA4Hz: 415.3, centOffset: -100, harmonicResonanceCenterHz: 77.78 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 115, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3500, biteGainDb: 3.5, cabHighCutHz: 6200, distortionGain: 0.85, stereoSpread: 1.40, description: 'Kerry King e Jeff Hanneman em Marshalls JCM800 2203 com palhetada furiosa e solos caóticos com whammy bar.' },
        eq10Band: { hz30: -1.5, hz60: 2.0, hz120: 1.5, hz250: -1.0, hz500: 0.0, hz1000: 1.5, hz2500: 2.5, hz4000: 3.0, hz8000: 2.2, hz16000: 1.2 },
        saturation: { type: 'dbx160_vca', drive: 0.75 },
        compressor: { threshold: -14, ratio: 3.8, attack: 15, release: 80, knee: 3 },
        stereoWidth: 1.40,
        gemSetup: makeGem(
          'Bateria Dave Lombardo: bumbos duplos rápidos como metralhadora, sem nenhum reverb artificial.', 'dbx160_vca', 0.80,
          'Baixo Tom Araya tocado com palheta sustentando a velocidade brutal.', 'sansamp_di', 0.70,
          'Guitarras Kerry King e Jeff Hanneman com Marshalls JCM800 2203 rasgados.', 'marshall_jcm800', 0.80, 1.40,
          'Tom Araya gritando em Angel of Death com compressão analógica rápida.', 'distressor_nuke', 0.75,
          'Ruídos de chuva e trovões em Raining Blood.', 'tape_warmth', 0.50, 1.40,
          2.0, -0.5, 1.2, 1.6, -8.0
        ),
      },
      {
        id: 'rubin-toxicity',
        albumTitle: 'Toxicity',
        band: 'System of a Down',
        year: 2001,
        hardwareChain: 'Cello Studios + Neve 8078 + SSL 4000 + Fairchild + UREI 1176',
        soundSignature: 'Metal alternativo explosivo: contrastes brutais entre sussurros acústicos e explosões de fúria sonora.',
        targetLufs: -6.5,
        tuningSignature: { standardName: 'Drop C (C-G-C-F-A-D)', baseFreqA4Hz: 440.0, centOffset: -200, harmonicResonanceCenterHz: 65.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 98, midScoopHz: 700, midScoopGainDb: -1.2, bitePresenceHz: 3400, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.88, stereoSpread: 1.45, description: 'Daron Malakian Marshall JMP + Mesa Boogie com riffs em Drop C sincopados e dinâmicas extremas.' },
        eq10Band: { hz30: -0.2, hz60: 2.8, hz120: 1.5, hz250: -1.0, hz500: 0.2, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'distressor_nuke', drive: 0.75 },
        compressor: { threshold: -12, ratio: 3.6, attack: 18, release: 80, knee: 3 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria John Dolmayan com pratos nítidos e caixa explosiva no centro.', 'dbx160_vca', 0.80,
          'Baixo Shavo Odadjian com distorção rústica e subgrave encorpado.', 'sansamp_di', 0.75,
          'Guitarras Daron Malakian em afinação Drop C dobradas com amplificadores Marshall e Mesa.', 'marshall_jcm800', 0.82, 1.45,
          'Vocais Serj Tankian com harmonizações líricas e gritos frenéticos.', 'la2a_opto', 0.75,
          'Instrumentos tradicionais armênios, sitares e efeitos acústicos.', 'tape_warmth', 0.60, 1.50,
          1.8, 0.0, 1.2, 1.8, -2.0
        ),
      },
    ],
  },

  // 10. COLIN RICHARDSON
  {
    id: 'colin-richardson',
    name: 'COLIN RICHARDSON',
    title: 'The Lord of British Metal Precision',
    category: 'metal_rock',
    era: '90s & 2000s Industrial Metal & Modern Death',
    country: 'United Kingdom',
    bio: 'Produtor e engenheiro lendário de Fear Factory (Demanufacture), Carcass (Heartwork), Machine Head (Burn My Eyes) e Bullet for My Valentine.',
    albums: [
      {
        id: 'richardson-demanufacture',
        albumTitle: 'Demanufacture',
        band: 'Fear Factory',
        year: 1995,
        hardwareChain: 'SSL 4000 E + Neve 1073 + TC Electronic 2290 + Sony Digital 3348',
        soundSignature: 'A perfeição industrial do metal: bumbos triggados com precisão mecânica, baixo sintetizado e guitarras em afinação B cortantes como lâminas.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'B Standard (B-E-A-D-G-B)', baseFreqA4Hz: 440.0, centOffset: -500, harmonicResonanceCenterHz: 61.74 },
        guitarToneprint: { ampModel: 'peavey_5150', cabResonanceHz: 90, midScoopHz: 650, midScoopGainDb: -2.5, bitePresenceHz: 3800, biteGainDb: 3.5, cabHighCutHz: 6200, distortionGain: 0.90, stereoSpread: 1.45, description: 'Dino Cazares com guitarra Ibanez de 7 cordas e Marshall JCM800 modificado com ataque de palheta cirúrgico e gate ultrarrápido.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.2, hz250: -1.5, hz500: -0.2, hz1000: 1.5, hz2500: 2.5, hz4000: 3.2, hz8000: 2.8, hz16000: 2.0 },
        saturation: { type: 'ssl_vca', drive: 0.75 },
        compressor: { threshold: -13, ratio: 4.0, attack: 12, release: 70, knee: 2 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria mecânica de Raymond Herrera com pedal duplo perfeitamente alinhado e estalo cirúrgico.', 'ssl_vca', 0.80,
          'Baixo com camada subgrave limpa e distorção de médio para dobrar o bumbo.', 'darkglass_b7k', 0.75,
          'Guitarras de 7 cordas de Dino Cazares afinadas em B com gate silencioso entre as notas.', 'peavey_5150', 0.82, 1.45,
          'Vocais industriais de Burton C. Bell: gutural agressivo vs refrões limpos espaciais.', 'la2a_opto', 0.72,
          'Sintetizadores e sequenciadores industriais de Rhys Fulber.', 'ssl_vca', 0.70, 1.65,
          2.0, 0.0, 1.0, 1.5, 0.0
        ),
      },
    ],
  },
];
