import {
  type SaturationType,
  type GemSetup,
  type MasterProducer,
} from './masters-database';

function makeGem(
  drumDesc: string, drumSat: SaturationType, drumDrive: number,
  bassDesc: string, bassSat: SaturationType, bassDrive: number,
  gtrDesc: string, gtrSat: SaturationType, gtrDrive: number, gtrWidth: number,
  voxDesc: string, voxSat: SaturationType, voxDrive: number,
  synDesc: string, synSat: SaturationType, synDrive: number, synWidth: number,
  volDrums = 0.5, volBass = 0.0, volGtr = 0.8, volVox = 1.2, volSyn = -3.5
): GemSetup {
  return {
    drums: {
      volumeDb: volDrums,
      eq: { sub: 2.0, punch: 2.5, attack: 3.0, air: 1.5 },
      saturation: drumSat,
      drive: drumDrive,
      compRatio: 3.5,
      compAttack: 25,
      compRelease: 120,
      description: drumDesc,
    },
    bass: {
      volumeDb: volBass,
      eq: { subBass: 2.5, grit: 2.0, cutMids: -1.5, clarity: 1.8 },
      saturation: bassSat,
      drive: bassDrive,
      compRatio: 4.0,
      compAttack: 15,
      compRelease: 90,
      description: bassDesc,
    },
    guitars: {
      volumeDb: volGtr,
      eq: { lowCut: 85, body: 1.8, bite: 2.5, sheen: 2.0 },
      saturation: gtrSat,
      drive: gtrDrive,
      stereoWidth: gtrWidth,
      description: gtrDesc,
    },
    vocals: {
      volumeDb: volVox,
      eq: { body: 1.2, clarity: 2.0, presence: 2.5, air: 3.0 },
      saturation: voxSat,
      drive: voxDrive,
      compRatio: 3.5,
      compAttack: 12,
      compRelease: 100,
      description: voxDesc,
    },
    synthsFx: {
      volumeDb: volSyn,
      eq: { lowMids: 0.8, presence: 1.5, air: 2.0 },
      saturation: synSat,
      drive: synDrive,
      stereoWidth: synWidth,
      description: synDesc,
    },
  };
}

export const PRODUCERS_PART2: MasterProducer[] = [
  // 11. BRENDAN O'BRIEN
  {
    id: 'brendan-obrien',
    name: 'BRENDAN O\'BRIEN',
    title: 'The Grunge & Alt-Rock Master',
    category: 'metal_rock',
    era: '90s & 2000s Grunge, Alt-Rock & Hard Rock',
    country: 'USA',
    bio: 'Produtor lendário de Pearl Jam (Vs., Vitalogy), Rage Against the Machine (Evil Empire), Stone Temple Pilots (Core, Purple), Soundgarden (Superunknown) e AC/DC (Black Ice).',
    albums: [
      {
        id: 'obrien-evilempire',
        albumTitle: 'Evil Empire',
        band: 'Rage Against the Machine',
        year: 1996,
        hardwareChain: 'Neve 8078 + UREI 1176 + Pultec + Studer A800',
        soundSignature: 'Punch analógico avassalador: o bumbo mais gordo do rap-metal, baixo elétrico mastodôntico e guitarras com efeitos inovadores.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Drop D (D-A-D-G-B-E)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 108, midScoopHz: 750, midScoopGainDb: 0.0, bitePresenceHz: 3000, biteGainDb: 2.8, cabHighCutHz: 6000, distortionGain: 0.75, stereoSpread: 1.40, description: 'Tom Morello com Marshall JCM800 2205 + pedal Whammy + chave seletora killswitch.' },
        eq10Band: { hz30: 0.0, hz60: 3.0, hz120: 1.8, hz250: -0.5, hz500: 0.5, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'neve_tube', drive: 0.70 },
        compressor: { threshold: -15, ratio: 3.2, attack: 25, release: 100, knee: 4 },
        stereoWidth: 1.40,
        gemSetup: makeGem(
          'Bateria Brad Wilk: bumbo 22" acústico monstruoso e caixa com estalo analógico.', 'tape_warmth', 0.75,
          'Baixo Tim Commerford com distorção de amplificador Ampeg SVT e graves pesados.', 'ampeg_svt', 0.75,
          'Guitarras de Tom Morello cheias de dinamismo, solos alienígenas e wah-wah.', 'marshall_jcm800', 0.78, 1.40,
          'Zack de la Rocha com vocais cuspindo fogo na cara com compressão 1176.', 'la2a_opto', 0.72,
          'Efeitos de turntable e scratches de guitarra.', 'tape_warmth', 0.55, 1.45,
          2.2, 0.5, 1.2, 1.8, -4.0
        ),
      },
      {
        id: 'obrien-vs',
        albumTitle: 'Vs.',
        band: 'Pearl Jam',
        year: 1993,
        hardwareChain: 'The Site + Neve 8068 + Studer A800 + UREI 1176',
        soundSignature: 'Grunge enérgico e visceral: dinâmica crua em Animal e Go, vocais rasgados de Eddie Vedder e bateria potente de Dave Abbruzzese.',
        targetLufs: -7.8,
        tuningSignature: { standardName: 'Drop D / Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3200, biteGainDb: 2.8, cabHighCutHz: 6100, distortionGain: 0.75, stereoSpread: 1.42, description: 'Stone Gossard e Mike McCready em amplificadores Marshall JCM800 e Fender Bassman vintage.' },
        eq10Band: { hz30: -0.5, hz60: 2.5, hz120: 1.8, hz250: -0.5, hz500: 0.5, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'tape_warmth', drive: 0.70 },
        compressor: { threshold: -15, ratio: 3.0, attack: 28, release: 110, knee: 4 },
        stereoWidth: 1.42,
        gemSetup: makeGem(
          'Bateria Dave Abbruzzese com pratos vivos e caixa de madeira explosiva.', 'tape_warmth', 0.72,
          'Baixo Jeff Ament com baixo fretless e ataques melódicos.', 'ampeg_svt', 0.70,
          'Guitarras com riffs de puro Rock em Go, Animal e Blood.', 'marshall_jcm800', 0.75, 1.42,
          'Eddie Vedder com interpretação visceral e emotiva.', 'la2a_opto', 0.75,
          'Violões orgânicos em Daughter e Elderly Woman.', 'tape_warmth', 0.50, 1.45,
          1.5, 0.2, 1.2, 1.8, -3.0
        ),
      },
    ],
  },

  // 12. MICHAEL WAGENER
  {
    id: 'michael-wagener',
    name: 'MICHAEL WAGENER',
    title: 'The German Heavy Metal Pioneer',
    category: 'metal_rock',
    era: '80s & 90s Heavy Metal & Hard Rock',
    country: 'Germany / USA',
    bio: 'Produtor e mixador de Accept (Balls to the Wall), Skid Row (Slave to the Grind), Ozzy Osbourne (No More Tears) e Dokken (Tooth and Nail).',
    albums: [
      {
        id: 'wagener-slavetothegrind',
        albumTitle: 'Slave to the Grind',
        band: 'Skid Row',
        year: 1991,
        hardwareChain: 'SSL 4000 + Neve 1073 + DBX 160 + Studer A800',
        soundSignature: 'O primeiro álbum de heavy metal a estrear em #1 na Billboard: guitarras cortantes, baixo gordo e vocais rasgados de Sebastian Bach.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 112, midScoopHz: 750, midScoopGainDb: -1.0, bitePresenceHz: 3200, biteGainDb: 3.0, cabHighCutHz: 6100, distortionGain: 0.82, stereoSpread: 1.42, description: 'Dave Snake Sabo e Scotti Hill em amplificadores Marshall JCM800 e ADA MP-1 valvulado.' },
        eq10Band: { hz30: -1.0, hz60: 2.5, hz120: 1.5, hz250: -0.8, hz500: 0.2, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'ssl_vca', drive: 0.72 },
        compressor: { threshold: -14, ratio: 3.5, attack: 22, release: 90, knee: 3 },
        stereoWidth: 1.42,
        gemSetup: makeGem(
          'Bateria pesada com bumbo profundo e caixa com estalo de bronze.', 'ssl_vca', 0.75,
          'Baixo Rachel Bolan com ataque de palheta metálico.', 'sansamp_di', 0.72,
          'Paredes de guitarra Marshall com crunch afiado em estéreo.', 'marshall_jcm800', 0.78, 1.42,
          'Vocais acrobáticos e agudos viscerais de Sebastian Bach.', 'la2a_opto', 0.72,
          'Ambiência de estúdio e backing vocals em coro.', 'tape_warmth', 0.50, 1.45,
          1.5, 0.0, 1.2, 2.0, -5.0
        ),
      },
      {
        id: 'wagener-nomoretears',
        albumTitle: 'No More Tears',
        band: 'Ozzy Osbourne',
        year: 1991,
        hardwareChain: 'A&M Studios + SSL 4000 + Neve 1073 + Lexicon 480L',
        soundSignature: 'Produção monumental de metal: o baixo mais icônico de Bob Daisley, guitarras incandescentes de Zakk Wylde e a voz inconfundível de Ozzy.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Drop D (D-A-D-G-B-E)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 700, midScoopGainDb: -1.2, bitePresenceHz: 3500, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.85, stereoSpread: 1.45, description: 'Zakk Wylde com Gibson Les Paul Custom, captadores EMG 81/85 e Marshall JCM800 2203 com overdrive BOSS SD-1.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.8, hz250: -0.8, hz500: 0.2, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.74 },
        compressor: { threshold: -14, ratio: 3.5, attack: 20, release: 85, knee: 3 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria Randy Castillo com bumbos pesados e caixa de aço estalando.', 'ssl_vca', 0.78,
          'Baixo Bob Daisley com a linha icônica de No More Tears.', 'ampeg_svt', 0.75,
          'Guitarras de Zakk Wylde com harmônicos artificiais (pinch harmonics) e timbres pesados.', 'marshall_jcm800', 0.82, 1.45,
          'Ozzy Osbourne com dobras de voz perfeitas e reverberação luxuosa.', 'la2a_opto', 0.72,
          'Teclados orquestrais de John Sinclair e efeitos espaciais.', 'pultec_tube', 0.60, 1.60,
          1.8, 0.2, 1.2, 1.8, -2.0
        ),
      },
    ],
  },

  // 13. MAX NORMAN
  {
    id: 'max-norman',
    name: 'MAX NORMAN',
    title: 'The Sound of Randy Rhoads & Megadeth Platinum',
    category: 'metal_rock',
    era: '80s & 90s Heavy & Thrash Platinum Master',
    country: 'United Kingdom / USA',
    bio: 'Produtor lendário dos álbuns com Randy Rhoads (Blizzard of Ozz, Diary of a Madman), Megadeth (Countdown to Extinction, Youthanasia) e Savatage.',
    albums: [
      {
        id: 'norman-countdown',
        albumTitle: 'Countdown to Extinction',
        band: 'Megadeth',
        year: 1992,
        hardwareChain: 'SSL 4000 G + Studer A800 + Eventide H3000 + Neve 1073',
        soundSignature: 'A masterização definitiva de Thrash Metal melódico: guitarras Jackson em V ultradefinidas, baixo David Ellefson na cara e bateria precisa.',
        targetLufs: -7.8,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 750, midScoopGainDb: -1.5, bitePresenceHz: 3400, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.80, stereoSpread: 1.44, description: 'Dave Mustaine e Marty Friedman com amplificadores Custom Bogner Triple Giant e Marshall JCM800.' },
        eq10Band: { hz30: -0.8, hz60: 2.5, hz120: 1.5, hz250: -1.0, hz500: 0.0, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.72 },
        compressor: { threshold: -14, ratio: 3.5, attack: 20, release: 85, knee: 3 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria Nick Menza com pratos nítidos, caixa firme e bumbo de clique percussivo.', 'ssl_vca', 0.75,
          'Baixo David Ellefson com palheta metálica e distorção em 1kHz.', 'sansamp_di', 0.75,
          'Guitarras Mustaine/Friedman com técnica impecável e solos neoclássicos.', 'marshall_jcm800', 0.78, 1.44,
          'Vocal sarcástico e rítmico de Dave Mustaine no centro.', 'la2a_opto', 0.68,
          'Contagens regressivas e efeitos sonoros teatrais.', 'ssl_vca', 0.50, 1.45,
          1.5, 0.2, 1.2, 1.5, -4.0
        ),
      },
      {
        id: 'norman-blizzard',
        albumTitle: 'Blizzard of Ozz',
        band: 'Ozzy Osbourne (Randy Rhoads)',
        year: 1980,
        hardwareChain: 'Ridge Farm Studios + Trident Console + Marshall 1959 + Studer Tape',
        soundSignature: 'A genialidade de Randy Rhoads: guitarras dobradas 3x com solos neoclássicos perfeitos em Crazy Train e Mr. Crowley.',
        targetLufs: -8.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 112, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3200, biteGainDb: 3.0, cabHighCutHz: 6000, distortionGain: 0.75, stereoSpread: 1.40, description: 'Randy Rhoads com Marshall 1959 Super Lead 100W modificado com ganho extra e pedal MXR Distortion+.' },
        eq10Band: { hz30: -1.0, hz60: 2.0, hz120: 1.8, hz250: 0.0, hz500: 0.5, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'tape_warmth', drive: 0.68 },
        compressor: { threshold: -16, ratio: 3.0, attack: 28, release: 110, knee: 4 },
        stereoWidth: 1.40,
        gemSetup: makeGem(
          'Bateria Lee Kerslake com caixa aberta e bumbo clássico.', 'tape_warmth', 0.68,
          'Baixo Bob Daisley com precisão melódica.', 'ampeg_svt', 0.70,
          'Guitarras dobradas de Randy Rhoads em Crazy Train e Suicide Solution.', 'marshall_jcm800', 0.75, 1.40,
          'Ozzy Osbourne jovem e triunfante.', 'la2a_opto', 0.70,
          'Órgão de tubos clássico de Don Airey na introdução de Mr. Crowley.', 'pultec_tube', 0.65, 1.65,
          1.2, 0.2, 1.2, 1.8, -1.0
        ),
      },
    ],
  },

  // 14. BOB EZRIN
  {
    id: 'bob-ezrin',
    name: 'BOB EZRIN',
    title: 'The Cinematic Rock Mastermind',
    category: 'prog_synth',
    era: '70s, 80s, 90s & Modern Prog Rock',
    country: 'Canada / USA',
    bio: 'Arquiteto sonoro de Pink Floyd (The Wall), KISS (Destroyer), Alice Cooper (Billion Dollar Babies) e Deep Purple (Now What?!).',
    albums: [
      {
        id: 'ezrin-thewall',
        albumTitle: 'The Wall',
        band: 'Pink Floyd',
        year: 1979,
        hardwareChain: 'Super Bear Studios + MCI Console + Fairchild 670 + Studer A800',
        soundSignature: 'A maior produção conceitual da história da música: dinâmica épica, coros de crianças, helicópteros e os solos de David Gilmour.',
        targetLufs: -10.0,
        tuningSignature: { standardName: 'Drop D / Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 108, midScoopHz: 850, midScoopGainDb: 0.0, bitePresenceHz: 2800, biteGainDb: 2.2, cabHighCutHz: 5800, distortionGain: 0.65, stereoSpread: 1.45, description: 'David Gilmour Fender Stratocaster Black Strat + amplificadores Hiwatt Custom 100 + pedal Big Muff / Tube Driver.' },
        eq10Band: { hz30: 0.0, hz60: 2.5, hz120: 2.0, hz250: 0.0, hz500: 0.5, hz1000: 1.0, hz2500: 1.8, hz4000: 2.2, hz8000: 2.5, hz16000: 2.0 },
        saturation: { type: 'tape_warmth', drive: 0.60 },
        compressor: { threshold: -18, ratio: 2.6, attack: 35, release: 150, knee: 5 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria Nick Mason com bumbo de madeira profundo e sala acústica.', 'tape_warmth', 0.62,
          'Baixo Roger Waters com corpo analógico aveludado.', 'ampeg_svt', 0.65,
          'Guitarras David Gilmour com o solo lendário de Comfortably Numb.', 'marshall_jcm800', 0.70, 1.45,
          'Vocais teatrais Waters/Gilmour e coro de crianças em Another Brick in the Wall.', 'la2a_opto', 0.68,
          'Efeitos cinematográficos de helicópteros, TV, passos e orquestrações de Michael Kamen.', 'pultec_tube', 0.70, 1.75,
          1.0, 0.5, 1.2, 1.5, 2.0
        ),
      },
    ],
  },

  // 15. KEVIN SHIRLEY
  {
    id: 'kevin-shirley',
    name: 'KEVIN SHIRLEY ("The Caveman")',
    title: 'The Modern Live Metal Maestro',
    category: 'metal_rock',
    era: '2000s, 2010s & 2020s Modern Classic Metal',
    country: 'South Africa / USA',
    bio: 'Produtor de todos os álbuns do Iron Maiden desde 2000 (Brave New World, Dance of Death, A Matter of Life and Death, The Book of Souls, Senjutsu) e Dream Theater.',
    albums: [
      {
        id: 'shirley-bravenewworld',
        albumTitle: 'Brave New World',
        band: 'Iron Maiden',
        year: 2000,
        hardwareChain: 'Studio Guillaume Tell + Neve VR + Studer A800 + UREI 1176',
        soundSignature: 'O retorno triunfal de Bruce Dickinson e Adrian Smith: 3 guitarras gravadas ao vivo no estúdio com energia orgânica e peso moderno.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Standard E / Drop D (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3200, biteGainDb: 2.8, cabHighCutHz: 6100, distortionGain: 0.78, stereoSpread: 1.48, description: 'Trio de guitarras Murray/Smith/Gers em amplificadores Marshall JCM900 e DSL100.' },
        eq10Band: { hz30: -0.8, hz60: 2.2, hz120: 1.8, hz250: -0.5, hz500: 0.5, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'tape_warmth', drive: 0.70 },
        compressor: { threshold: -14, ratio: 3.2, attack: 25, release: 100, knee: 4 },
        stereoWidth: 1.48,
        gemSetup: makeGem(
          'Bateria Nicko McBrain gravada ao vivo na sala de Paris com caixa aberta e chimbal rápido.', 'tape_warmth', 0.72,
          'Baixo Steve Harris galopante e presente com Precision Bass.', 'neve_tube', 0.75,
          'Trio de guitarras divididas L, C, R em The Wicker Man e Ghost of the Navigator.', 'marshall_jcm800', 0.78, 1.48,
          'Bruce Dickinson com interpretação potente e alcance operático.', 'la2a_opto', 0.72,
          'Sintetizadores orquestrais de apoio e ambiência de estúdio.', 'ssl_vca', 0.50, 1.50,
          1.2, 1.5, 1.2, 1.8, -2.5
        ),
      },
    ],
  },

  // 16. TED JENSEN
  {
    id: 'ted-jensen',
    name: 'TED JENSEN',
    title: 'Sterling Sound Master of Dynamic Power',
    category: 'metal_rock',
    era: '70s, 80s, 90s & Modern Mastering Legend',
    country: 'USA',
    bio: 'Engenheiro-chefe da Sterling Sound. Masterizou American Idiot do Green Day, Hotel California dos Eagles, Train of Thought do Dream Theater e Fallen do Evanescence.',
    albums: [
      {
        id: 'jensen-americanidiot',
        albumTitle: 'American Idiot',
        band: 'Green Day',
        year: 2004,
        hardwareChain: 'Sterling Sound + Neumann SAL + Manley Variable Mu + Sontec MES 432C',
        soundSignature: 'A masterização de punk/rock mais potente e dinâmica do século XXI: bumbos com pegada seca, guitarras em parede estéreo e voz cristalina.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 112, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.80, stereoSpread: 1.46, description: 'Billie Joe Armstrong com Gibson Les Paul Junior e amplificadores Marshall Plexi 100W modificados (Pete e Meat).' },
        eq10Band: { hz30: -0.5, hz60: 2.6, hz120: 1.5, hz250: -0.8, hz500: 0.2, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.72 },
        compressor: { threshold: -13, ratio: 3.5, attack: 20, release: 80, knee: 3 },
        stereoWidth: 1.46,
        gemSetup: makeGem(
          'Bateria Tre Cool: bumbo seco na cara, caixa com estalo de madeira e pratos brilhantes.', 'ssl_vca', 0.78,
          'Baixo Mike Dirnt com palhetada agressiva e graves sólidos.', 'sansamp_di', 0.75,
          'Paredão de guitarras Marshall dobradas com afinação standard e crunch quente.', 'marshall_jcm800', 0.80, 1.46,
          'Billie Joe Armstrong com voz direta e sem firulas.', 'la2a_opto', 0.72,
          'Violões em Boulevard of Broken Dreams e Wake Me Up When September Ends.', 'tape_warmth', 0.55, 1.50,
          1.8, 0.2, 1.2, 1.8, -3.0
        ),
      },
    ],
  },

  // 17. HANS ZIMMER
  {
    id: 'hans-zimmer',
    name: 'HANS ZIMMER',
    title: 'The Sovereign Titan of Hollywood Cinema',
    category: 'cinema',
    era: '90s, 2000s, 2010s & 2020s Cinematic Universe',
    country: 'Germany / UK / USA',
    bio: 'Compositor e produtor vencedor de 2 Oscars (Dune, O Rei Leão, Interestelar, A Origem, Batman O Cavaleiro das Trevas, Gladiador). Mestre dos subgraves sísmicos e orquestrações épicas.',
    albums: [
      {
        id: 'zimmer-dune',
        albumTitle: 'Dune: Part One & Two (Original Soundtrack)',
        band: 'Hans Zimmer',
        year: 2024,
        hardwareChain: 'Remote Control Productions + Custom Moog Subharmonics + Neve Genesys + Shadow Hills',
        soundSignature: 'Subgraves sísmicos de 20Hz a 40Hz, gaitas de foles processadas como guitarras elétricas, coros femininos hipnóticos e percussões gigantes.',
        targetLufs: -8.0,
        tuningSignature: { standardName: 'Microtonal Arrakis Tuning (A=432.0Hz)', baseFreqA4Hz: 432.0, centOffset: -32, harmonicResonanceCenterHz: 54.0 },
        guitarToneprint: { ampModel: 'soldano_slo100', cabResonanceHz: 85, midScoopHz: 700, midScoopGainDb: 0.0, bitePresenceHz: 3000, biteGainDb: 2.0, cabHighCutHz: 6000, distortionGain: 0.70, stereoSpread: 1.60, description: 'Guitarras de 8 cordas processadas como instrumentos de vento do deserto e sintetizadores Moog distorcidos.' },
        eq10Band: { hz30: 4.5, hz60: 3.5, hz120: 1.5, hz250: -0.5, hz500: 0.5, hz1000: 1.0, hz2500: 1.8, hz4000: 2.5, hz8000: 3.0, hz16000: 2.5 },
        saturation: { type: 'shadow_hills', drive: 0.65 },
        compressor: { threshold: -16, ratio: 2.8, attack: 35, release: 120, knee: 5 },
        stereoWidth: 1.60,
        gemSetup: makeGem(
          'Taikos gigantes e percussões profundas do deserto de Arrakis.', 'shadow_hills', 0.70,
          'Subgraves analógicos Moog em 30Hz que fazem o chão tremer.', 'darkglass_b7k', 0.75,
          'Guitarras e violoncelos elétricos processados com distorção boutique.', 'soldano_slo100', 0.70, 1.60,
          'Vozes sussurradas e cantos arcanos femininos em estéreo.', 'la2a_opto', 0.65,
          'Sintetizadores futuristas e orquestra sinfônica completa.', 'pultec_tube', 0.75, 1.80,
          2.5, 3.0, 1.0, 1.5, 2.5
        ),
      },
    ],
  },

  // 18. LUDWIG GÖRANSSON
  {
    id: 'ludwig-goransson',
    name: 'LUDWIG GÖRANSSON',
    title: 'The Modern Cinematic & Sonic Alchemist',
    category: 'cinema',
    era: '2010s & 2020s Cutting-Edge Cinema Sound',
    country: 'Sweden / USA',
    bio: 'Produtor e compositor vencedor de 2 Oscars (Oppenheimer, Pantera Negra, The Mandalorian, Tenet). Mestre da fusão entre violinos acústicos agressivos, sintetizadores analógicos e batidas industriais.',
    albums: [
      {
        id: 'goransson-oppenheimer',
        albumTitle: 'Oppenheimer (Original Motion Picture Soundtrack)',
        band: 'Ludwig Göransson',
        year: 2023,
        hardwareChain: 'Synchron Stage Vienna + Neve 88RS + Eventide + Shadow Hills Mastering',
        soundSignature: 'Violinos solo frenéticos acelerando em tempo real, sintetizadores épicos em Can You Hear the Music e impacto sonoro colossal da fissão nuclear.',
        targetLufs: -8.5,
        tuningSignature: { standardName: 'Standard Orchestral (A=442.0Hz)', baseFreqA4Hz: 442.0, centOffset: +8, harmonicResonanceCenterHz: 110.5 },
        guitarToneprint: { ampModel: 'soldano_slo100', cabResonanceHz: 95, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3200, biteGainDb: 2.2, cabHighCutHz: 6200, distortionGain: 0.65, stereoSpread: 1.55, description: 'Violinos distorcidos e guitarras ambiente processadas com reverbs cinemáticos.' },
        eq10Band: { hz30: 3.5, hz60: 2.8, hz120: 1.5, hz250: 0.0, hz500: 0.5, hz1000: 1.2, hz2500: 2.0, hz4000: 2.8, hz8000: 3.0, hz16000: 2.5 },
        saturation: { type: 'shadow_hills', drive: 0.65 },
        compressor: { threshold: -16, ratio: 2.8, attack: 30, release: 110, knee: 4 },
        stereoWidth: 1.55,
        gemSetup: makeGem(
          'Percussões dinâmicas de orquestra e impactos de fissão atômica.', 'shadow_hills', 0.68,
          'Graves orquestrais de contrabaixo acústico e sintetizadores subgraves.', 'ampeg_svt', 0.65,
          'Cordas frenéticas e guitarras ambientais em estéreo.', 'soldano_slo100', 0.70, 1.55,
          'Ambiência de sala e respirações humanas.', 'la2a_opto', 0.60,
          'Camadas massivas de sintetizadores analógicos Moog e orquestra.', 'pultec_tube', 0.70, 1.75,
          1.8, 2.0, 1.2, 1.2, 2.0
        ),
      },
    ],
  },

  // 19. VANGELIS
  {
    id: 'vangelis',
    name: 'VANGELIS',
    title: 'The Grandmaster of Analog Synthesizers',
    category: 'prog_synth',
    era: '70s, 80s, 90s & 2000s Electronic & Cinematic Pioneer',
    country: 'Greece',
    bio: 'Pioneiro supremo dos sintetizadores analógicos (Yamaha CS-80), Blade Runner (1982), Chariots of Fire e 1492: A Conquista do Paraíso.',
    albums: [
      {
        id: 'vangelis-bladerunner',
        albumTitle: 'Blade Runner (Original Soundtrack)',
        band: 'Vangelis',
        year: 1982,
        hardwareChain: 'Nemo Studios London + Yamaha CS-80 + Lexicon 224 Reverb + Studer A80',
        soundSignature: 'O som do futuro distópico de 2019: sintetizadores analógicos CS-80 com expressividade de fita, reverbs espaciais e saxofones sob a chuva.',
        targetLufs: -9.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'fairchild_mu', cabResonanceHz: 110, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 2800, biteGainDb: 1.8, cabHighCutHz: 6000, distortionGain: 0.50, stereoSpread: 1.65, description: 'Guitarras ambiente e sintetizadores Yamaha CS-80 com pitch ribbon e modulação de fita analógica.' },
        eq10Band: { hz30: 2.0, hz60: 2.2, hz120: 1.5, hz250: 0.2, hz500: 0.8, hz1000: 1.2, hz2500: 1.8, hz4000: 2.5, hz8000: 3.0, hz16000: 2.5 },
        saturation: { type: 'tape_warmth', drive: 0.65 },
        compressor: { threshold: -18, ratio: 2.5, attack: 35, release: 140, knee: 5 },
        stereoWidth: 1.65,
        gemSetup: makeGem(
          'Percussões épicas de gongo, sinos e caixas com reverb Lexicon 224.', 'tape_warmth', 0.65,
          'Baixos analógicos profundos de sintetizador CS-80.', 'neve_tube', 0.65,
          'Guitarras e saxofones melancólicos sob a chuva de Los Angeles.', 'fairchild_mu', 0.60, 1.65,
          'Monólogo clássico de Roy Batty e vocais etéreos.', 'la2a_opto', 0.65,
          'O icônico sintetizador Yamaha CS-80 com reverbs infinitos em Tears in Rain.', 'pultec_tube', 0.75, 1.80,
          1.0, 1.5, 1.2, 1.5, 3.0
        ),
      },
    ],
  },

  // 20. HERBERT VON KARAJAN & DEUTSCHE GRAMMOPHON
  {
    id: 'herbert-von-karajan',
    name: 'HERBERT VON KARAJAN',
    title: 'The Sovereign Master of Classical Orchestral Grandeur',
    category: 'classical',
    era: '60s, 70s & 80s Golden Classical & Audiophile Era',
    country: 'Austria / Germany',
    bio: 'O maestro mais famoso do século XX e o lendário padrão audiófilo da Deutsche Grammophon com a Orquestra Filarmônica de Berlim. Gravação sinfônica em espaço acústico real.',
    albums: [
      {
        id: 'karajan-beethoven9',
        albumTitle: 'Beethoven: Symphony No. 9 "Choral"',
        band: 'Berliner Philharmoniker (Herbert von Karajan)',
        year: 1977,
        hardwareChain: 'Berliner Philharmonie + Neumann M50 Decca Tree + Telefunken Magnetophon + Telefunken Pre-amps',
        soundSignature: 'A gravação definitiva da 9ª Sinfonia de Beethoven: dinâmica audiófila incomparável do pianíssimo ao fortíssimo (Ode à Alegria) com sala viva.',
        targetLufs: -14.0,
        tuningSignature: { standardName: 'Berlin Philharmonic Concert Pitch (A=443.0Hz)', baseFreqA4Hz: 443.0, centOffset: +12, harmonicResonanceCenterHz: 110.75 },
        guitarToneprint: { ampModel: 'fairchild_mu', cabResonanceHz: 115, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3000, biteGainDb: 1.5, cabHighCutHz: 6000, distortionGain: 0.40, stereoSpread: 1.50, description: 'Cordas acústicas da Filarmônica de Berlim gravadas com microfones valvulados Neumann M50.' },
        eq10Band: { hz30: 0.5, hz60: 1.5, hz120: 1.8, hz250: 0.5, hz500: 0.8, hz1000: 1.2, hz2500: 1.8, hz4000: 2.2, hz8000: 2.5, hz16000: 2.0 },
        saturation: { type: 'neve_tube', drive: 0.50 },
        compressor: { threshold: -22, ratio: 2.0, attack: 45, release: 200, knee: 6 },
        stereoWidth: 1.50,
        gemSetup: makeGem(
          'Tímpanos sinfônicos majestosos na sala da Philharmonie.', 'tape_warmth', 0.55,
          'Contrabaixos acústicos e violoncelos encorpados.', 'neve_tube', 0.60,
          'Cordas completas (violinos, violas) em estéreo amplo.', 'fairchild_mu', 0.55, 1.50,
          'Solistas vocais e o grande coro cantando Ode à Alegria.', 'la2a_opto', 0.60,
          'Madeiras, trompas e metais sinfônicos com ambiência acústica natural.', 'pultec_tube', 0.65, 1.70,
          0.8, 1.2, 1.2, 1.5, 1.5
        ),
      },
    ],
  },
];
