import {
  type SaturationType,
  type GemSetup,
  type MasterProducer,
} from './masters-database';

function makeGem(
  drumDesc: string, drumSat: SaturationType, drumDrive: number,
  bassDesc: string, bassSat: SaturationType, bassDrive: number,
  gtrDesc: string, gtrSat: SaturationType, gtrDrive: number, gtrWidth: number,
  voxDesc: string, voxSat: SaturationType, voxDrive: number,
  synDesc: string, synSat: SaturationType, synDrive: number, synWidth: number,
  volDrums = 0.5, volBass = 0.0, volGtr = 0.8, volVox = 1.2, volSyn = -3.5
): GemSetup {
  return {
    drums: {
      volumeDb: volDrums,
      eq: { sub: 2.0, punch: 2.5, attack: 3.0, air: 1.5 },
      saturation: drumSat,
      drive: drumDrive,
      compRatio: 3.5,
      compAttack: 25,
      compRelease: 120,
      description: drumDesc,
    },
    bass: {
      volumeDb: volBass,
      eq: { subBass: 2.5, grit: 2.0, cutMids: -1.5, clarity: 1.8 },
      saturation: bassSat,
      drive: bassDrive,
      compRatio: 4.0,
      compAttack: 15,
      compRelease: 90,
      description: bassDesc,
    },
    guitars: {
      volumeDb: volGtr,
      eq: { lowCut: 85, body: 1.8, bite: 2.5, sheen: 2.0 },
      saturation: gtrSat,
      drive: gtrDrive,
      stereoWidth: gtrWidth,
      description: gtrDesc,
    },
    vocals: {
      volumeDb: volVox,
      eq: { body: 1.2, clarity: 2.0, presence: 2.5, air: 3.0 },
      saturation: voxSat,
      drive: voxDrive,
      compRatio: 3.5,
      compAttack: 12,
      compRelease: 100,
      description: voxDesc,
    },
    synthsFx: {
      volumeDb: volSyn,
      eq: { lowMids: 0.8, presence: 1.5, air: 2.0 },
      saturation: synSat,
      drive: synDrive,
      stereoWidth: synWidth,
      description: synDesc,
    },
  };
}

export const ALL_20_PRODUCERS_FULL: MasterProducer[] = [
  // 1. ROY Z
  {
    id: 'roy-z',
    name: 'ROY Z',
    title: 'The Heavy Metal Renaissance Master',
    category: 'metal_rock',
    era: '90s, 2000s & 2020s Heavy Metal Revival',
    country: 'USA / Latin America',
    bio: 'Produtor e guitarrista lendário que redefiniu o heavy metal tradicional, resgatando Bruce Dickinson, Rob Halford / Fight, Judas Priest, Helloween, Angra e Sepultura com timbres analógicos potentes, graves densos e presença imponente.',
    albums: [
      {
        id: 'royz-mandrake',
        albumTitle: 'The Mandrake Project',
        band: 'Bruce Dickinson',
        year: 2024,
        hardwareChain: 'SSL AWS 900 + Shadow Hills + Chandler TG1 + Neve 1073 + Studer A800',
        soundSignature: 'Heavy Metal moderno hiper-dinâmico, guitarras afinadas em Drop D densas, graves sólidos e vocal cristalino.',
        targetLufs: -7.2,
        tuningSignature: { standardName: 'Drop D (D-A-D-G-B-E)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'mesa_rectifier', cabResonanceHz: 105, midScoopHz: 680, midScoopGainDb: -2.0, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.85, stereoSpread: 1.45, description: 'Mesa Boogie Dual Rectifier + Marshall JCM800 afinado em Drop D com ganho denso e presença cortante.' },
        eq10Band: { hz30: -1.0, hz60: 2.0, hz120: 1.2, hz250: -1.0, hz500: 0.5, hz1000: 1.0, hz2500: 1.8, hz4000: 2.2, hz8000: 2.0, hz16000: 1.5 },
        saturation: { type: 'shadow_hills', drive: 0.65 },
        compressor: { threshold: -14, ratio: 3.0, attack: 30, release: 100, knee: 4 },
        stereoWidth: 1.42,
        gemSetup: makeGem(
          'Bateria acústica encorpada com bumbo 22" e caixa Maple, compressão VCA paralela e microfonação de sala realista.', 'tape_warmth', 0.65,
          'Baixo em 5 cordas com distorção Darkglass B7K e DI valvulado Neve 1073.', 'darkglass_b7k', 0.70,
          'Paredão estéreo de guitarras Marshall JCM800 e Mesa Boogie com afinações graves.', 'mesa_rectifier', 0.75, 1.45,
          'Vocal lírico épico processado com 1176 All-Buttons-In e Pultec Air Boost.', 'la2a_opto', 0.60,
          'Sintetizadores orquestrais e efeitos cinematográficos amplos.', 'ssl_vca', 0.50, 1.60,
          1.0, 0.0, 1.2, 1.5, -2.0
        ),
      },
      {
        id: 'royz-fight-warofwords',
        albumTitle: 'War of Words',
        band: 'Fight (Rob Halford)',
        year: 1993,
        hardwareChain: 'SSL 4000 E + Neve 1073 + DBX 160 + Studer A800',
        soundSignature: 'Thrash/Groove metal agressivo dos anos 90: bumbos com clique cortante, baixo cru e Rob Halford rasgando a garganta com fúria.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Drop D (D-A-D-G-B-E)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'peavey_5150', cabResonanceHz: 108, midScoopHz: 650, midScoopGainDb: -2.5, bitePresenceHz: 3600, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.88, stereoSpread: 1.42, description: 'Guitarras de Brian Tilse e Russ Parrish com ganho agressivo de estado sólido/válvula e palhetada seca.' },
        eq10Band: { hz30: -0.8, hz60: 2.5, hz120: 1.5, hz250: -1.2, hz500: 0.0, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.75 },
        compressor: { threshold: -14, ratio: 3.5, attack: 18, release: 85, knee: 3 },
        stereoWidth: 1.42,
        gemSetup: makeGem(
          'Bateria Scott Travis com pegada furiosa de pedal duplo e caixa de metal estalando.', 'ssl_vca', 0.78,
          'Baixo Jack Frost com ataque de palheta metálico e corte em 800Hz.', 'sansamp_di', 0.75,
          'Guitarras cortantes afinadas em Drop D com riffs sincopados como Into the Pit e Nailed to the Gun.', 'peavey_5150', 0.82, 1.42,
          'Rob Halford com vocais agressivos, berros viscerais e agudos afiados.', 'distressor_nuke', 0.75,
          'Feedback analógico e efeitos de fita.', 'ssl_vca', 0.45, 1.35,
          1.8, 0.0, 1.2, 1.8, -6.0
        ),
      },
      {
        id: 'royz-fight-deadlyspace',
        albumTitle: 'A Small Deadly Space',
        band: 'Fight (Rob Halford)',
        year: 1995,
        hardwareChain: 'SSL 4000 G + Neve 1081 + Eventide H3000 + Studer Tape',
        soundSignature: 'Metal alternativo pesado e sombrio: afinações mais baixas, texturas industriais e vocais hipnóticos.',
        targetLufs: -7.6,
        tuningSignature: { standardName: 'Drop C# (C#-G#-C#-F#-A#-D#)', baseFreqA4Hz: 440.0, centOffset: -100, harmonicResonanceCenterHz: 69.30 },
        guitarToneprint: { ampModel: 'soldano_slo100', cabResonanceHz: 100, midScoopHz: 700, midScoopGainDb: -1.8, bitePresenceHz: 3300, biteGainDb: 3.0, cabHighCutHz: 6100, distortionGain: 0.85, stereoSpread: 1.44, description: 'Guitarras em Drop C# com afinação encorpada e timbres valvulados densos.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.8, hz250: -0.8, hz500: 0.2, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'distressor_nuke', drive: 0.72 },
        compressor: { threshold: -14, ratio: 3.4, attack: 22, release: 90, knee: 3 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria pesada com bumbo profundo e caixa encorpada.', 'tape_warmth', 0.72,
          'Baixo com graves densos e distorção aveludada.', 'ampeg_svt', 0.72,
          'Riffs pesados em afinação Drop C# com ambiência sombria.', 'soldano_slo100', 0.80, 1.44,
          'Rob Halford explorando tons médios sombrios e refrões poderosos.', 'la2a_opto', 0.70,
          'Camadas de efeitos espaciais e microfonias controladas.', 'ssl_vca', 0.50, 1.45,
          1.5, 0.2, 1.2, 1.6, -3.5
        ),
      },
      {
        id: 'royz-chemical',
        albumTitle: 'The Chemical Wedding',
        band: 'Bruce Dickinson',
        year: 1998,
        hardwareChain: 'Neve 8078 + Fairchild 670 + Pultec EQP-1A + Studer A800 Tape',
        soundSignature: 'Heavy Metal sombrio, afinações em Drop C, guitarras colossais e bateria explosiva inspirada em William Blake.',
        targetLufs: -8.0,
        tuningSignature: { standardName: 'Drop C (C-G-C-F-A-D)', baseFreqA4Hz: 440.0, centOffset: -200, harmonicResonanceCenterHz: 65.41 },
        guitarToneprint: { ampModel: 'soldano_slo100', cabResonanceHz: 95, midScoopHz: 750, midScoopGainDb: -1.5, bitePresenceHz: 3200, biteGainDb: 3.5, cabHighCutHz: 6000, distortionGain: 0.90, stereoSpread: 1.40, description: 'Guitarras em Drop C gravadas com Soldano SLO-100 e Marshall JCM800 com graves sísmicos e harmônicos arcanos.' },
        eq10Band: { hz30: -0.5, hz60: 2.5, hz120: 1.5, hz250: -0.8, hz500: 0.8, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 1.8, hz16000: 1.2 },
        saturation: { type: 'neve_tube', drive: 0.70 },
        compressor: { threshold: -15, ratio: 3.2, attack: 25, release: 120, knee: 5 },
        stereoWidth: 1.38,
        gemSetup: makeGem(
          'Bateria gigante com sala ao vivo, bumbo agressivo e esteira brilhante.', 'tape_warmth', 0.70,
          'Baixo distorcido com SansAmp e ataque em 800Hz para cortar nas guitarras pesadas.', 'sansamp_di', 0.75,
          'Guitarras em afinação Drop C dobradas 4x com ganho denso de Marshall e Soldano.', 'soldano_slo100', 0.80, 1.40,
          'Voz dramática e potente com microfone Neumann U47 e compressor óptico.', 'la2a_opto', 0.65,
          'Efeitos arcanos, sinos e teclados atmosféricos profundos.', 'tape_warmth', 0.55, 1.50,
          1.2, -0.5, 1.5, 1.2, -1.5
        ),
      },
      {
        id: 'royz-resurrection',
        albumTitle: 'Resurrection',
        band: 'Halford',
        year: 2000,
        hardwareChain: 'SSL 4000 G+ + Neve 1073 + UREI 1176 + Studer A827',
        soundSignature: 'O retorno triunfal do Metal God: bumbos duplos ultrarrápidos, guitarras em afinação standard afiadas e vocais agudos cortantes.',
        targetLufs: -7.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 700, midScoopGainDb: -1.0, bitePresenceHz: 3500, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.80, stereoSpread: 1.42, description: 'Guitarras Marshall JCM800 dobradas com Tubescreamer para afinação Standard E cortante.' },
        eq10Band: { hz30: -1.0, hz60: 2.2, hz120: 1.5, hz250: -1.0, hz500: 0.2, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.2, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.70 },
        compressor: { threshold: -14, ratio: 3.5, attack: 20, release: 90, knee: 3 },
        stereoWidth: 1.42,
        gemSetup: makeGem(
          'Bateria Bobby Jarzombek com bumbos velozes e esteira supersônica.', 'ssl_vca', 0.75,
          'Baixo Ray Riendeau com ataque metálico em 1.5kHz.', 'sansamp_di', 0.70,
          'Guitarras afiadas em afinação Standard E dobradas em estéreo.', 'marshall_jcm800', 0.75, 1.42,
          'Rob Halford atingindo notas agudas F5 com clareza cristalina.', 'la2a_opto', 0.70,
          'Intro futurista e efeitos de sintetizador.', 'ssl_vca', 0.50, 1.40,
          1.5, 0.0, 1.0, 1.8, -4.0
        ),
      },
      {
        id: 'royz-crucible',
        albumTitle: 'Crucible',
        band: 'Halford',
        year: 2002,
        hardwareChain: 'SSL 9000 J + Neve 1073 + Empirical Labs Distressor',
        soundSignature: 'Heavy Metal moderno hiper-pesado: afinações em Drop D e C, guitarras cortantes e vocais viscerais.',
        targetLufs: -7.0,
        tuningSignature: { standardName: 'Drop D (D-A-D-G-B-E)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'mesa_rectifier', cabResonanceHz: 104, midScoopHz: 680, midScoopGainDb: -1.8, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.85, stereoSpread: 1.45, description: 'Guitarras pesadas com Mesa Boogie Dual Rectifier e Marshall JCM800 em afinações baixas.' },
        eq10Band: { hz30: -0.8, hz60: 2.8, hz120: 1.5, hz250: -1.0, hz500: 0.2, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'distressor_nuke', drive: 0.75 },
        compressor: { threshold: -13, ratio: 3.6, attack: 18, release: 80, knee: 3 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria veloz e percussiva com ataque imediato na caixa.', 'distressor_nuke', 0.78,
          'Baixo em afinação pesada com distorção de médio.', 'darkglass_b7k', 0.75,
          'Guitarras afiadas com riffs técnicos em Betrayal e Crucible.', 'mesa_rectifier', 0.80, 1.45,
          'Rob Halford agressivo com agudos lancinantes.', 'la2a_opto', 0.72,
          'Efeitos industriais e transições dinâmicas.', 'ssl_vca', 0.50, 1.45,
          1.6, 0.2, 1.2, 1.8, -3.0
        ),
      },
      {
        id: 'royz-accident',
        albumTitle: 'Accident of Birth',
        band: 'Bruce Dickinson',
        year: 1997,
        hardwareChain: 'Trident A-Range + Neve 1073 + Fairchild + Studer Tape',
        soundSignature: 'Heavy Metal melódico clássico: Adrian Smith e Roy Z nas guitarras, refrões épicos e graves quentes.',
        targetLufs: -8.2,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 112, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3200, biteGainDb: 2.8, cabHighCutHz: 6000, distortionGain: 0.75, stereoSpread: 1.38, description: 'Dobras melódicas de Adrian Smith e Roy Z em amplificadores valvulados ingleses.' },
        eq10Band: { hz30: -1.2, hz60: 2.0, hz120: 1.8, hz250: -0.5, hz500: 0.5, hz1000: 1.2, hz2500: 1.8, hz4000: 2.2, hz8000: 1.8, hz16000: 1.2 },
        saturation: { type: 'tape_warmth', drive: 0.65 },
        compressor: { threshold: -16, ratio: 3.0, attack: 30, release: 110, knee: 4 },
        stereoWidth: 1.38,
        gemSetup: makeGem(
          'Bateria acústica dinâmica com pratos Paiste abertos.', 'tape_warmth', 0.65,
          'Baixo quente com corpo valvulado.', 'ampeg_svt', 0.65,
          'Guitarras dobradas com timbres clássicos britânicos.', 'marshall_jcm800', 0.70, 1.38,
          'Vocais teatrais de Bruce Dickinson.', 'la2a_opto', 0.60,
          'Violões e ambientações acústicas.', 'tape_warmth', 0.50, 1.45,
          0.8, 0.2, 1.0, 1.5, -3.0
        ),
      },
      {
        id: 'royz-ballstopicasso',
        albumTitle: 'Balls to Picasso',
        band: 'Bruce Dickinson',
        year: 1994,
        hardwareChain: 'Neve 8078 + Studer A800 + EMT 140 Reverb',
        soundSignature: 'Hard Rock e Metal latino/melódico com o hit Tears of the Dragon: violões brilhantes e guitarras expressivas.',
        targetLufs: -8.5,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 800, midScoopGainDb: 0.0, bitePresenceHz: 3000, biteGainDb: 2.5, cabHighCutHz: 6000, distortionGain: 0.70, stereoSpread: 1.38, description: 'Guitarras de Roy Z e Tribe of Gypsies com dinâmica aberta e solos emotivos em Tears of the Dragon.' },
        eq10Band: { hz30: -1.0, hz60: 2.0, hz120: 1.8, hz250: 0.0, hz500: 0.5, hz1000: 1.2, hz2500: 1.8, hz4000: 2.2, hz8000: 2.0, hz16000: 1.5 },
        saturation: { type: 'tape_warmth', drive: 0.65 },
        compressor: { threshold: -16, ratio: 2.8, attack: 30, release: 120, knee: 4 },
        stereoWidth: 1.38,
        gemSetup: makeGem(
          'Bateria acústica quente com caixa de madeira e chimbal definido.', 'tape_warmth', 0.65,
          'Baixo orgânico com sustentação natural.', 'ampeg_svt', 0.65,
          'Guitarras limpas e distorcidas com dinâmica expressiva.', 'marshall_jcm800', 0.70, 1.38,
          'Bruce Dickinson cantando com emoção em Tears of the Dragon.', 'la2a_opto', 0.68,
          'Violões clássicos e percussões latinas.', 'tape_warmth', 0.50, 1.45,
          1.0, 0.0, 1.0, 1.8, -2.5
        ),
      },
      {
        id: 'royz-tyranny',
        albumTitle: 'Tyranny of Souls',
        band: 'Bruce Dickinson',
        year: 2005,
        hardwareChain: 'SSL AWS 900 + Neve 1073 + Manley Massive Passive',
        soundSignature: 'Heavy Metal espacial e potente: afinações em Drop D, refrões solenes e produção moderna cristalina.',
        targetLufs: -7.0,
        tuningSignature: { standardName: 'Drop D (D-A-D-G-B-E)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'mesa_rectifier', cabResonanceHz: 106, midScoopHz: 700, midScoopGainDb: -1.5, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.82, stereoSpread: 1.44, description: 'Riffs em Drop D gravados por Roy Z com Mesa Boogie e Marshall JCM800.' },
        eq10Band: { hz30: -0.8, hz60: 2.5, hz120: 1.5, hz250: -1.0, hz500: 0.2, hz1000: 1.2, hz2500: 2.0, hz4000: 2.5, hz8000: 2.2, hz16000: 1.8 },
        saturation: { type: 'shadow_hills', drive: 0.70 },
        compressor: { threshold: -14, ratio: 3.2, attack: 25, release: 95, knee: 3 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria acústica potente com bumbos definidos.', 'tape_warmth', 0.70,
          'Baixo em 5 cordas sustentando as afinações pesadas.', 'darkglass_b7k', 0.72,
          'Guitarras dobradas com timbres modernos e afiados em Abduction.', 'mesa_rectifier', 0.78, 1.44,
          'Bruce Dickinson com performance vocal monumental.', 'la2a_opto', 0.70,
          'Teclados espaciais e violões de 12 cordas.', 'ssl_vca', 0.50, 1.50,
          1.2, 0.2, 1.2, 1.6, -2.0
        ),
      },
      {
        id: 'royz-angelretribution',
        albumTitle: 'Angel of Retribution',
        band: 'Judas Priest',
        year: 2005,
        hardwareChain: 'SSL 9000 J + Neve 1073 + Empirical Labs Distressor + Sony Oxford',
        soundSignature: 'A reunião histórica de Rob Halford com o Judas Priest: bumbos duplos fulminantes em Judas Rising e guitarras gêmeas clássicas.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'Standard E / Drop D (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 108, midScoopHz: 750, midScoopGainDb: -1.2, bitePresenceHz: 3500, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.82, stereoSpread: 1.45, description: 'Glenn Tipton e K.K. Downing em amplificadores Marshall JCM800 e Mesa Boogie com timbres britânicos afiados.' },
        eq10Band: { hz30: -0.8, hz60: 2.5, hz120: 1.5, hz250: -1.0, hz500: 0.2, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.72 },
        compressor: { threshold: -13, ratio: 3.5, attack: 20, release: 85, knee: 3 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria Scott Travis com pedal duplo supersônico em Judas Rising e Demonizer.', 'ssl_vca', 0.78,
          'Baixo Ian Hill sólido marcando os tempos no barramento principal.', 'sansamp_di', 0.72,
          'Guitarras gêmeas Tipton/Downing com duelos de solos clássicos.', 'marshall_jcm800', 0.80, 1.45,
          'Rob Halford triunfante com agudos estratosféricos.', 'la2a_opto', 0.72,
          'Intro atmosférica de sintetizadores e ambiências góticas.', 'ssl_vca', 0.50, 1.45,
          1.8, 0.0, 1.2, 1.8, -3.5
        ),
      },
      {
        id: 'royz-betterthanraw',
        albumTitle: 'Better Than Raw',
        band: 'Helloween',
        year: 1998,
        hardwareChain: 'Chateau du Pape + Neve 8068 + Studer A800 + EMT Plates',
        soundSignature: 'Power Metal pesado e moderno: bumbos duplos rápidos, riffs cortantes em Push e melodias inesquecíveis em I Can.',
        targetLufs: -7.8,
        tuningSignature: { standardName: 'Drop D / Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 110, midScoopHz: 750, midScoopGainDb: -1.0, bitePresenceHz: 3400, biteGainDb: 3.0, cabHighCutHz: 6200, distortionGain: 0.80, stereoSpread: 1.44, description: 'Michael Weikath e Roland Grapow com Marshalls JCM800 e afinações em Drop D pesadas.' },
        eq10Band: { hz30: -0.8, hz60: 2.5, hz120: 1.5, hz250: -0.8, hz500: 0.2, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'tape_warmth', drive: 0.70 },
        compressor: { threshold: -14, ratio: 3.4, attack: 22, release: 90, knee: 3 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria Uli Kusch com técnica refinada, bumbos velozes e caixa estalando.', 'tape_warmth', 0.75,
          'Baixo Markus Grosskopf com linhas melódicas rápidas e ataque claro.', 'ampeg_svt', 0.72,
          'Guitarras Weikath/Grapow com riffs pesadíssimos em Push e Revelation.', 'marshall_jcm800', 0.78, 1.44,
          'Andi Deris com vocais roucos e melódicos perfeitamente equilibrados.', 'la2a_opto', 0.70,
          'Intro clássica Deliberately Limited e orquestrações.', 'pultec_tube', 0.55, 1.55,
          1.5, 0.2, 1.2, 1.6, -2.5
        ),
      },
      {
        id: 'royz-darkride',
        albumTitle: 'The Dark Ride',
        band: 'Helloween',
        year: 2000,
        hardwareChain: 'Mi Sueño Studios + SSL 4000 + Neve 1073 + UREI 1176',
        soundSignature: 'O álbum mais pesado e sombrio da história do Helloween: afinações em Drop D e C, guitarras gigantes e atmosfera gótica.',
        targetLufs: -7.2,
        tuningSignature: { standardName: 'Drop D / Drop C (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: -100, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'soldano_slo100', cabResonanceHz: 102, midScoopHz: 700, midScoopGainDb: -1.5, bitePresenceHz: 3500, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.85, stereoSpread: 1.46, description: 'Guitarras pesadas em afinação Drop gravadas com Soldano SLO-100 e Mesa Boogie.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.8, hz250: -1.0, hz500: 0.2, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.74 },
        compressor: { threshold: -13, ratio: 3.6, attack: 20, release: 85, knee: 3 },
        stereoWidth: 1.46,
        gemSetup: makeGem(
          'Bateria pesada com bumbo profundo e caixa com estalo moderno.', 'ssl_vca', 0.78,
          'Baixo Markus Grosskopf com peso subgrave e distorção média.', 'sansamp_di', 0.75,
          'Guitarras sombrias e pesadas em Mr. Torture e The Dark Ride.', 'soldano_slo100', 0.82, 1.46,
          'Andi Deris com interpretação teatral e agressiva.', 'la2a_opto', 0.72,
          'Teclados góticos, sinos e efeitos cinemáticos.', 'pultec_tube', 0.60, 1.60,
          1.6, 0.2, 1.2, 1.6, -1.5
        ),
      },
      {
        id: 'royz-sepulturakairos',
        albumTitle: 'Kairos',
        band: 'Sepultura',
        year: 2011,
        hardwareChain: 'Trama Studios + SSL Duality + Neve 1073 + Distressor',
        soundSignature: 'Thrash Metal cru e orgânico gravado por Roy Z em São Paulo: guitarras cortantes, percussão pesada e peso analógico.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'D Standard (D-G-C-F-A-D)', baseFreqA4Hz: 440.0, centOffset: -200, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'peavey_5150', cabResonanceHz: 98, midScoopHz: 720, midScoopGainDb: -1.5, bitePresenceHz: 3500, biteGainDb: 3.2, cabHighCutHz: 6200, distortionGain: 0.88, stereoSpread: 1.44, description: 'Andreas Kisser com riffs furiosos em afinação D Standard e distorção EVH 5150 III.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.5, hz250: -1.0, hz500: 0.2, hz1000: 1.5, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'distressor_nuke', drive: 0.75 },
        compressor: { threshold: -13, ratio: 3.6, attack: 18, release: 80, knee: 3 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria Jean Dolabella com pegada crua, caixa aberta e bumbos percussivos.', 'distressor_nuke', 0.80,
          'Baixo Paulo Jr. sólido e encorpado.', 'darkglass_b7k', 0.75,
          'Guitarras cruas de Andreas Kisser com palhetada violenta em Kairos e Relentless.', 'peavey_5150', 0.82, 1.44,
          'Derrick Green com vocais guturais imponentes.', 'distressor_nuke', 0.75,
          'Percussões adicionais e ambiência ao vivo.', 'ssl_vca', 0.45, 1.40,
          1.8, 0.0, 1.2, 1.8, -4.0
        ),
      },
    ],
  },

  // 2. TERRY DATE
  {
    id: 'terry-date',
    name: 'TERRY DATE',
    title: 'The Architect of Groove & Raw Power',
    category: 'metal_rock',
    era: '80s, 90s & 2000s Groove Metal & Heavy Hardcore',
    country: 'USA',
    bio: 'Pioneiro absoluto do som do Pantera, Deftones, Soundgarden, White Zombie e Overkill. Criador da caixa explosiva de metal, bumbos com clique cortante e baixo que faz o chão tremer sem embolar.',
    albums: [
      {
        id: 'date-vulgar',
        albumTitle: 'Vulgar Display of Power',
        band: 'Pantera',
        year: 1992,
        hardwareChain: 'SSL 4000 E + DBX 160 + Eventide H3000 + Neve 1073 + Sony PCM-3348',
        soundSignature: 'A referência máxima de groove metal: bumbo com clique de moeda em 3.5kHz, baixo cortando em 800Hz e guitarras em estado sólido hiper-cortantes.',
        targetLufs: -7.0,
        tuningSignature: { standardName: '1/4 Tom Abaixo (A=430.5Hz / D-Standard Detuned)', baseFreqA4Hz: 430.5, centOffset: -38, harmonicResonanceCenterHz: 71.85 },
        guitarToneprint: { ampModel: 'randall_rg100', cabResonanceHz: 110, midScoopHz: 500, midScoopGainDb: -4.0, bitePresenceHz: 3800, biteGainDb: 3.5, cabHighCutHz: 6200, distortionGain: 0.90, stereoSpread: 1.45, description: 'Dimebag Darrell Randall RG100 com corte severo em 500Hz, ganho de estado sólido agressivo e ataque percussivo extremo.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.0, hz250: -1.8, hz500: -0.8, hz1000: 1.5, hz2500: 2.5, hz4000: 3.0, hz8000: 2.2, hz16000: 1.5 },
        saturation: { type: 'ssl_vca', drive: 0.75 },
        compressor: { threshold: -14, ratio: 3.8, attack: 15, release: 80, knee: 3 },
        stereoWidth: 1.45,
        gemSetup: makeGem(
          'Bateria Vinnie Paul com trigger no bumbo, caixa de bronze 14" estourando e DBX 160 em cada canal.', 'dbx160_vca', 0.80,
          'Baixo Rex Brown afinado em D com distorção de médio-agudo e subgrave cirúrgico.', 'sansamp_di', 0.75,
          'Guitarras Dimebag Darrell com amplificadores Randall RG100, corte cavado em 500Hz e agudos lacerantes.', 'randall_rg100', 0.85, 1.45,
          'Vocal Phil Anselmo rasgado e agressivo com compressão FET ultra-rápida.', 'distressor_nuke', 0.70,
          'FX atmosféricos e microfonia analógica controlada.', 'ssl_vca', 0.40, 1.30,
          2.0, -0.5, 0.8, 1.5, -8.0
        ),
      },
      {
        id: 'date-farbeyond',
        albumTitle: 'Far Beyond Driven',
        band: 'Pantera',
        year: 1994,
        hardwareChain: 'SSL 4000 G + DBX 160X + Neve 1081 + Sony Digital 3348',
        soundSignature: 'O álbum mais pesado a estrear em #1 na Billboard: afinação em C#, peso esmagador e fúria sonora.',
        targetLufs: -6.8,
        tuningSignature: { standardName: 'C# Standard Detuned (A=425Hz)', baseFreqA4Hz: 425.0, centOffset: -160, harmonicResonanceCenterHz: 67.20 },
        guitarToneprint: { ampModel: 'randall_rg100', cabResonanceHz: 92, midScoopHz: 520, midScoopGainDb: -3.8, bitePresenceHz: 4000, biteGainDb: 3.8, cabHighCutHz: 6200, distortionGain: 0.95, stereoSpread: 1.46, description: 'Guitarras Dimebag em C# com pedal MXR Flanger Doubler, ganho colossal e Whammy pedal.' },
        eq10Band: { hz30: -0.2, hz60: 3.0, hz120: 1.5, hz250: -1.5, hz500: -0.5, hz1000: 1.8, hz2500: 2.8, hz4000: 3.2, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'distressor_nuke', drive: 0.80 },
        compressor: { threshold: -13, ratio: 4.0, attack: 12, release: 70, knee: 2 },
        stereoWidth: 1.46,
        gemSetup: makeGem(
          'Bateria esmagadora com bumbos duplos furiosos e caixa com ataque cortante.', 'dbx160_vca', 0.85,
          'Baixo em Drop C# com peso sísmico e distorção pesada.', 'sansamp_di', 0.80,
          'Guitarras ultra-pesadas com afinação em C# e Whammy pedal.', 'randall_rg100', 0.88, 1.46,
          'Vocal gutural e rasgado com saturação de pré-amp.', 'distressor_nuke', 0.75,
          'Camadas industriais e microfonias de amplificador.', 'ssl_vca', 0.50, 1.35,
          2.2, 0.0, 1.0, 1.6, -6.0
        ),
      },
      {
        id: 'date-cowboys',
        albumTitle: 'Cowboys from Hell',
        band: 'Pantera',
        year: 1990,
        hardwareChain: 'Pantego Sound Studio + SSL 4000 E + DBX 160 + Eventide H3000',
        soundSignature: 'A certidão de nascimento do Power Groove: estalo de caixa inconfundível, bumbo de clique e solos virtuosos de Dimebag.',
        targetLufs: -7.8,
        tuningSignature: { standardName: 'Standard E (A=440.0Hz)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 82.41 },
        guitarToneprint: { ampModel: 'randall_rg100', cabResonanceHz: 112, midScoopHz: 600, midScoopGainDb: -3.5, bitePresenceHz: 3800, biteGainDb: 3.5, cabHighCutHz: 6200, distortionGain: 0.85, stereoSpread: 1.44, description: 'Dimebag com amplificadores Randall RG100 e pedal MXR 6-Band EQ com corte em V.' },
        eq10Band: { hz30: -0.8, hz60: 2.5, hz120: 1.2, hz250: -1.5, hz500: -0.5, hz1000: 1.2, hz2500: 2.2, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'ssl_vca', drive: 0.72 },
        compressor: { threshold: -14, ratio: 3.5, attack: 18, release: 85, knee: 3 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria Vinnie Paul com bumbo com clique percussivo e caixa estourando no centro.', 'dbx160_vca', 0.80,
          'Baixo Rex Brown sólido e presente.', 'sansamp_di', 0.72,
          'Guitarras afiadas em Cowboys from Hell, Domination e Cemetery Gates.', 'peavey_5150', 0.82, 1.44,
          'Phil Anselmo alternando entre agudos operáticos de Halford e berros ferozes.', 'la2a_opto', 0.72,
          'Introdução icônica de guitarra invertida e delays analógicos.', 'ssl_vca', 0.50, 1.40,
          1.8, 0.0, 1.2, 1.8, -5.0
        ),
      },
      {
        id: 'date-whitepony',
        albumTitle: 'White Pony',
        band: 'Deftones',
        year: 2000,
        hardwareChain: 'SSL 4000 + Neve 1073 + Fairchild 670 + Eventide DSP4000',
        soundSignature: 'Alt-Metal e Shoegaze pesado: bateria com ambiência gigante de sala, vocais sussurrados a gritos e guitarras densas.',
        targetLufs: -7.8,
        tuningSignature: { standardName: 'Drop C (C-G-C-F-A-D)', baseFreqA4Hz: 440.0, centOffset: -200, harmonicResonanceCenterHz: 65.41 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 100, midScoopHz: 650, midScoopGainDb: -1.0, bitePresenceHz: 3000, biteGainDb: 2.5, cabHighCutHz: 5900, distortionGain: 0.80, stereoSpread: 1.48, description: 'Stephen Carpenter guitarras de 7 cordas afinadas em Drop C com paredes densas de Marshall e delay.' },
        eq10Band: { hz30: 0.0, hz60: 2.8, hz120: 2.0, hz250: -0.5, hz500: 0.2, hz1000: 1.0, hz2500: 1.8, hz4000: 2.5, hz8000: 2.2, hz16000: 2.0 },
        saturation: { type: 'tape_warmth', drive: 0.70 },
        compressor: { threshold: -15, ratio: 3.2, attack: 28, release: 120, knee: 4 },
        stereoWidth: 1.48,
        gemSetup: makeGem(
          'Bateria Abe Cunningham com groove sincopado e sala aberta colossal.', 'tape_warmth', 0.75,
          'Baixo Chi Cheng com graves profundos e distorção aveludada.', 'ampeg_svt', 0.70,
          'Paredes de guitarras de 7 cordas com afinação em Drop C e texturas ambientais.', 'marshall_jcm800', 0.75, 1.48,
          'Chino Moreno: do sussurro sensual aos gritos viscerais com compressão óptica.', 'la2a_opto', 0.75,
          'Samplers e sintetizadores de Frank Delgado em estéreo panorâmico.', 'ssl_vca', 0.65, 1.65,
          1.2, 0.2, 1.2, 1.4, 0.5
        ),
      },
      {
        id: 'date-badmotorfinger',
        albumTitle: 'Badmotorfinger',
        band: 'Soundgarden',
        year: 1991,
        hardwareChain: 'Studio Litho + SSL 4000 + Neve 1073 + UREI 1176 + Studer A800',
        soundSignature: 'Grunge e Heavy Metal em afinações alternativas (Drop D, EEBBBB): bateria monumental de Matt Cameron e vocais monumentais de Chris Cornell.',
        targetLufs: -7.8,
        tuningSignature: { standardName: 'Drop D (D-A-D-G-B-E)', baseFreqA4Hz: 440.0, centOffset: 0, harmonicResonanceCenterHz: 73.42 },
        guitarToneprint: { ampModel: 'marshall_jcm800', cabResonanceHz: 105, midScoopHz: 750, midScoopGainDb: 0.0, bitePresenceHz: 3200, biteGainDb: 3.0, cabHighCutHz: 6100, distortionGain: 0.82, stereoSpread: 1.44, description: 'Kim Thayil com Guild S-100 e amplificadores Marshall JCM800 + Peavey VTM com afinações incomuns.' },
        eq10Band: { hz30: -0.5, hz60: 2.8, hz120: 1.8, hz250: -0.5, hz500: 0.2, hz1000: 1.2, hz2500: 2.0, hz4000: 2.8, hz8000: 2.5, hz16000: 1.8 },
        saturation: { type: 'tape_warmth', drive: 0.72 },
        compressor: { threshold: -15, ratio: 3.4, attack: 25, release: 100, knee: 4 },
        stereoWidth: 1.44,
        gemSetup: makeGem(
          'Bateria Matt Cameron com dinâmica refinada e caixa penetrante.', 'tape_warmth', 0.75,
          'Baixo Ben Shepherd com linhas graves pesadas.', 'ampeg_svt', 0.72,
          'Guitarras densas e psicodélicas de Kim Thayil em Rusty Cage e Outshined.', 'marshall_jcm800', 0.80, 1.44,
          'Chris Cornell no auge vocal de alcance e rouquidão inacreditáveis.', 'la2a_opto', 0.75,
          'Saxofone dissonante e efeitos em Room a Thousand Years Wide.', 'tape_warmth', 0.50, 1.45,
          1.5, 0.2, 1.2, 2.0, -3.0
        ),
      },
    ],
  },
];
