export type MicCategory = 'vocals' | 'guitars' | 'bass' | 'drums' | 'synths'
export type CapsuleType =
	| 'dynamic'
	| 'condenser_large'
	| 'condenser_small'
	| 'tube'
	| 'ribbon'
	| 'fet_di'
export type PolarPattern = 'cardioid' | 'supercardioid' | 'hypercardioid' | 'omni' | 'figure_8'

export interface MicrophoneModel {
	id: string
	name: string
	brand: string
	category: MicCategory
	capsule: CapsuleType
	polarPattern: PolarPattern
	year: number
	country: string
	icon: string
	famousUsers: string
	soundDescription: string
	eqResponse: {
		lowCutHz: number
		subBassGain: number // dB
		bassGain: number // dB
		lowMidGain: number // dB
		midFreqHz: number
		midGain: number // dB
		presenceFreqHz: number
		presenceGain: number // dB
		airFreqHz: number
		airGain: number // dB
	}
	preampType: 'neve_1073' | 'api_512' | 'ssl_e' | 'tube_tech' | 'avalon_pure'
	preampDrive: number // 0.0 to 1.0
	proximityStrength: number // 0.0 to 1.0
}

export const LEGENDARY_MICROPHONES: MicrophoneModel[] = [
	// ═════════════════════════════════════════════════════════════════════════════
	// 🎙️ 1. GEM VOZ (VOCAL MICROPHONES)
	// ═════════════════════════════════════════════════════════════════════════════
	{
		id: 'neumann-u87-ai',
		name: 'U87 Ai Large Diaphragm Condenser',
		brand: 'Neumann',
		category: 'vocals',
		capsule: 'condenser_large',
		polarPattern: 'cardioid',
		year: 1967,
		country: 'Germany',
		icon: '👑',
		famousUsers: 'Ronnie James Dio, Bruce Dickinson, Rob Halford, Klaus Meine',
		soundDescription:
			'O padrão-ouro absoluto: presença aveludada em 3.5kHz, graves neutros e agudos sedosos com cápsula K67.',
		eqResponse: {
			lowCutHz: 60,
			subBassGain: 0.0,
			bassGain: 1.0,
			lowMidGain: 0.5,
			midFreqHz: 1800,
			midGain: 1.2,
			presenceFreqHz: 3800,
			presenceGain: 4.2,
			airFreqHz: 12000,
			airGain: 4.5,
		},
		preampType: 'ssl_e',
		preampDrive: 0.35,
		proximityStrength: 0.65,
	},
	{
		id: 'neumann-u47-tube',
		name: 'U47 Vintage Tube',
		brand: 'Neumann / Telefunken',
		category: 'vocals',
		capsule: 'tube',
		polarPattern: 'cardioid',
		year: 1949,
		country: 'Germany',
		icon: '✨',
		famousUsers: 'The Beatles, Frank Sinatra, Freddie Mercury, David Gilmour',
		soundDescription:
			'Válvula VF14 com graves gigantescos, médios tridimensionais encorpados e brilho dourado lendário.',
		eqResponse: {
			lowCutHz: 45,
			subBassGain: 2.2,
			bassGain: 3.5,
			lowMidGain: 2.0,
			midFreqHz: 1500,
			midGain: 1.5,
			presenceFreqHz: 3200,
			presenceGain: 3.8,
			airFreqHz: 10000,
			airGain: 3.5,
		},
		preampType: 'tube_tech',
		preampDrive: 0.55,
		proximityStrength: 0.85,
	},
	{
		id: 'telefunken-ela-m251',
		name: 'ELA M 251E Diamond Series',
		brand: 'Telefunken',
		category: 'vocals',
		capsule: 'tube',
		polarPattern: 'cardioid',
		year: 1960,
		country: 'Austria / Germany',
		icon: '💎',
		famousUsers: 'André Matos (Angra/Shaman), Mariah Carey, Michael Jackson',
		soundDescription:
			'Cápsula CK12 com agudos ultra-abertos de 14kHz aveludados e transparência luxuosa.',
		eqResponse: {
			lowCutHz: 50,
			subBassGain: 0.5,
			bassGain: 1.8,
			lowMidGain: 0.8,
			midFreqHz: 2500,
			midGain: 2.0,
			presenceFreqHz: 4500,
			presenceGain: 4.0,
			airFreqHz: 14000,
			airGain: 6.0,
		},
		preampType: 'tube_tech',
		preampDrive: 0.4,
		proximityStrength: 0.6,
	},
	{
		id: 'sony-c800g',
		name: 'C-800G Studio Tube Condenser',
		brand: 'Sony',
		category: 'vocals',
		capsule: 'tube',
		polarPattern: 'cardioid',
		year: 1992,
		country: 'Japan',
		icon: '⚡',
		famousUsers: 'Modern Metalcore Screams, Pop/Rock High Vocals, Sebastian Bach',
		soundDescription:
			'Sistema de refrigeração Peltier externo: transientes ultrarrápidos e presença hiper-moderna nos agudos.',
		eqResponse: {
			lowCutHz: 70,
			subBassGain: -0.5,
			bassGain: 1.2,
			lowMidGain: -0.5,
			midFreqHz: 3000,
			midGain: 2.5,
			presenceFreqHz: 5500,
			presenceGain: 5.2,
			airFreqHz: 15000,
			airGain: 6.5,
		},
		preampType: 'avalon_pure',
		preampDrive: 0.3,
		proximityStrength: 0.55,
	},
	{
		id: 'shure-sm7b',
		name: 'SM7B Studio Dynamic',
		brand: 'Shure',
		category: 'vocals',
		capsule: 'dynamic',
		polarPattern: 'cardioid',
		year: 1973,
		country: 'USA',
		icon: '🎙️',
		famousUsers: 'James Hetfield (Metallica), Serj Tankian (SOAD), Michael Jackson',
		soundDescription:
			'O dinâmico de estúdio supremo: médios encorpados e quentes, com resposta aveludada a berros e transientes fortes.',
		eqResponse: {
			lowCutHz: 80,
			subBassGain: 1.5,
			bassGain: 2.8,
			lowMidGain: 1.2,
			midFreqHz: 2000,
			midGain: 1.0,
			presenceFreqHz: 5000,
			presenceGain: 3.5,
			airFreqHz: 12000,
			airGain: 1.0,
		},
		preampType: 'neve_1073',
		preampDrive: 0.45,
		proximityStrength: 0.7,
	},
	{
		id: 'shure-sm58-live',
		name: 'SM58 Live Stage Dynamic',
		brand: 'Shure',
		category: 'vocals',
		capsule: 'dynamic',
		polarPattern: 'cardioid',
		year: 1966,
		country: 'USA',
		icon: '🎤',
		famousUsers: 'Mick Jagger, Robert Plant, Bono, Paul McCartney',
		soundDescription:
			'O padrão de palco ao vivo mais consagrado do mundo, com presença encorpada e rejeição sonora.',
		eqResponse: {
			lowCutHz: 85,
			subBassGain: -0.5,
			bassGain: 1.8,
			lowMidGain: 1.0,
			midFreqHz: 2500,
			midGain: 2.0,
			presenceFreqHz: 4800,
			presenceGain: 4.5,
			airFreqHz: 10000,
			airGain: 1.5,
		},
		preampType: 'ssl_e',
		preampDrive: 0.38,
		proximityStrength: 0.75,
	},
	{
		id: 'sennheiser-e945-live',
		name: 'e945 Stage Supercardioid',
		brand: 'Sennheiser',
		category: 'vocals',
		capsule: 'dynamic',
		polarPattern: 'supercardioid',
		year: 2003,
		country: 'Germany',
		icon: '⚡',
		famousUsers: 'Tobias Sammet, Bruce Dickinson (Live), Floor Jansen',
		soundDescription:
			'Som alemão encorpado com agudos suaves e presença que perfura guitarras pesadas sem estridência.',
		eqResponse: {
			lowCutHz: 75,
			subBassGain: 0.5,
			bassGain: 2.2,
			lowMidGain: 1.2,
			midFreqHz: 3000,
			midGain: 2.8,
			presenceFreqHz: 5000,
			presenceGain: 4.8,
			airFreqHz: 13000,
			airGain: 4.0,
		},
		preampType: 'neve_1073',
		preampDrive: 0.42,
		proximityStrength: 0.65,
	},

	// ═════════════════════════════════════════════════════════════════════════════
	// 🎸 2. GEM GUITARRAS (GUITAR CABINET & AMP MICS)
	// ═════════════════════════════════════════════════════════════════════════════
	{
		id: 'shure-sm57-cab',
		name: 'SM57 Instrument Dynamic (Guitar Cone)',
		brand: 'Shure',
		category: 'guitars',
		capsule: 'dynamic',
		polarPattern: 'cardioid',
		year: 1965,
		country: 'USA',
		icon: '🎸',
		famousUsers: 'Dimebag Darrell, James Hetfield, Slash, Kerry King',
		soundDescription:
			'Ataque imediato e mordida agressiva de palhetada entre 3kHz e 5.5kHz com graves firmes.',
		eqResponse: {
			lowCutHz: 90,
			subBassGain: -1.0,
			bassGain: 1.5,
			lowMidGain: 2.2,
			midFreqHz: 2500,
			midGain: 2.5,
			presenceFreqHz: 5000,
			presenceGain: 5.5,
			airFreqHz: 10000,
			airGain: 1.0,
		},
		preampType: 'api_512',
		preampDrive: 0.5,
		proximityStrength: 0.75,
	},
	{
		id: 'royer-r121-ribbon',
		name: 'R-121 Studio Ribbon',
		brand: 'Royer Labs',
		category: 'guitars',
		capsule: 'ribbon',
		polarPattern: 'figure_8',
		year: 1998,
		country: 'USA',
		icon: '⚡',
		famousUsers: 'Andy Sneap, Colin Richardson, Metallica, Tool',
		soundDescription:
			'O fita supremo para guitarras pesadas: graves encorpados aveludados, médios densos e agudos ultra-suaves.',
		eqResponse: {
			lowCutHz: 40,
			subBassGain: 3.0,
			bassGain: 4.5,
			lowMidGain: 3.0,
			midFreqHz: 1200,
			midGain: 1.0,
			presenceFreqHz: 3000,
			presenceGain: 1.5,
			airFreqHz: 8000,
			airGain: -1.0,
		},
		preampType: 'neve_1073',
		preampDrive: 0.48,
		proximityStrength: 0.9,
	},
	{
		id: 'sennheiser-md421-gtr',
		name: 'MD 421-II Dynamic (Guitar Cab)',
		brand: 'Sennheiser',
		category: 'guitars',
		capsule: 'dynamic',
		polarPattern: 'cardioid',
		year: 1960,
		country: 'Germany',
		icon: '🔊',
		famousUsers: 'Tony Iommi (Black Sabbath), Tom Morello, Alex Lifeson',
		soundDescription:
			'Médios-graves recortados e presença brilhante: perfeito para riffs pesados e amplificadores valvulados.',
		eqResponse: {
			lowCutHz: 70,
			subBassGain: 0.5,
			bassGain: 2.2,
			lowMidGain: 1.8,
			midFreqHz: 2800,
			midGain: 2.0,
			presenceFreqHz: 4500,
			presenceGain: 4.8,
			airFreqHz: 12000,
			airGain: 2.5,
		},
		preampType: 'ssl_e',
		preampDrive: 0.42,
		proximityStrength: 0.7,
	},
	{
		id: 'sennheiser-e906',
		name: 'e906 Flat Front Dynamic',
		brand: 'Sennheiser',
		category: 'guitars',
		capsule: 'dynamic',
		polarPattern: 'supercardioid',
		year: 2004,
		country: 'Germany',
		icon: '🎙️',
		famousUsers: 'Dave Mustaine (Megadeth), Zakk Wylde, Gary Holt',
		soundDescription:
			'Encostado na grade do falante: ataque imediato de palheta e médios cortantes com chave de presença.',
		eqResponse: {
			lowCutHz: 85,
			subBassGain: -0.5,
			bassGain: 1.8,
			lowMidGain: 2.0,
			midFreqHz: 3000,
			midGain: 3.0,
			presenceFreqHz: 4800,
			presenceGain: 5.0,
			airFreqHz: 11000,
			airGain: 2.0,
		},
		preampType: 'api_512',
		preampDrive: 0.45,
		proximityStrength: 0.65,
	},
	{
		id: 'beyerdynamic-m160',
		name: 'M 160 Double-Ribbon Dynamic',
		brand: 'Beyerdynamic',
		category: 'guitars',
		capsule: 'ribbon',
		polarPattern: 'hypercardioid',
		year: 1957,
		country: 'Germany',
		icon: '💎',
		famousUsers: 'Eddie Kramer (Jimi Hendrix, Led Zeppelin)',
		soundDescription:
			'Dupla fita hipercardióide com calor analógico vintage e atenuação sedosa de estridências agudas.',
		eqResponse: {
			lowCutHz: 50,
			subBassGain: 1.8,
			bassGain: 3.2,
			lowMidGain: 2.5,
			midFreqHz: 2000,
			midGain: 1.2,
			presenceFreqHz: 3500,
			presenceGain: 2.0,
			airFreqHz: 10000,
			airGain: 0.5,
		},
		preampType: 'neve_1073',
		preampDrive: 0.5,
		proximityStrength: 0.8,
	},

	// ═════════════════════════════════════════════════════════════════════════════
	// ⚡ 3. GEM BAIXO (BASS GUITAR & CAB MICS & DIs)
	// ═════════════════════════════════════════════════════════════════════════════
	{
		id: 'neumann-u47-fet-bass',
		name: 'U47 FET Low-End Precision',
		brand: 'Neumann',
		category: 'bass',
		capsule: 'fet_di',
		polarPattern: 'cardioid',
		year: 1969,
		country: 'Germany',
		icon: '🎸',
		famousUsers: 'Steve Harris (Iron Maiden), Rex Brown, Cliff Burton',
		soundDescription:
			'Grave sólido e articulado com pegada rápida e corpo denso de contrabaixo de metal.',
		eqResponse: {
			lowCutHz: 35,
			subBassGain: 4.5,
			bassGain: 4.0,
			lowMidGain: 2.2,
			midFreqHz: 1200,
			midGain: 1.5,
			presenceFreqHz: 2800,
			presenceGain: 3.2,
			airFreqHz: 9000,
			airGain: 1.8,
		},
		preampType: 'neve_1073',
		preampDrive: 0.48,
		proximityStrength: 0.85,
	},
	{
		id: 'avalon-u5-di',
		name: 'Avalon U5 Class-A Direct Box',
		brand: 'Avalon Design',
		category: 'bass',
		capsule: 'fet_di',
		polarPattern: 'cardioid',
		year: 1995,
		country: 'USA',
		icon: '⚡',
		famousUsers: 'Felipe Andreoli (Angra), John Myung (Dream Theater), Duff McKagan',
		soundDescription:
			'Pureza Classe A de alta voltagem: definição de notas rápidas, graves profundos e estalo de corda.',
		eqResponse: {
			lowCutHz: 25,
			subBassGain: 4.0,
			bassGain: 3.5,
			lowMidGain: 1.0,
			midFreqHz: 1500,
			midGain: 1.0,
			presenceFreqHz: 3200,
			presenceGain: 3.5,
			airFreqHz: 12000,
			airGain: 4.0,
		},
		preampType: 'avalon_pure',
		preampDrive: 0.28,
		proximityStrength: 0.2,
	},
	{
		id: 'akg-d112-bass',
		name: 'D112 Bass Cabinet Dynamic',
		brand: 'AKG',
		category: 'bass',
		capsule: 'dynamic',
		polarPattern: 'cardioid',
		year: 1986,
		country: 'Austria',
		icon: '🔊',
		famousUsers: 'Flea (RHCP), Geezer Butler (Black Sabbath)',
		soundDescription:
			'Pegada profunda em 80Hz com médios recortados para deixar espaço para a parede de guitarras.',
		eqResponse: {
			lowCutHz: 30,
			subBassGain: 4.8,
			bassGain: 3.8,
			lowMidGain: -1.5,
			midFreqHz: 900,
			midGain: 0.5,
			presenceFreqHz: 2500,
			presenceGain: 3.0,
			airFreqHz: 8000,
			airGain: 1.0,
		},
		preampType: 'ssl_e',
		preampDrive: 0.45,
		proximityStrength: 0.8,
	},
	{
		id: 'sansamp-bd-di',
		name: 'SansAmp Bass Driver Tube-DI',
		brand: 'Tech 21',
		category: 'bass',
		capsule: 'fet_di',
		polarPattern: 'cardioid',
		year: 1994,
		country: 'USA',
		icon: '🎛️',
		famousUsers: 'Geddy Lee (Rush), David Ellefson (Megadeth)',
		soundDescription:
			'Overdrive analógico com médios escavados e distorção cortante que cola o baixo com a bateria.',
		eqResponse: {
			lowCutHz: 30,
			subBassGain: 4.2,
			bassGain: 3.8,
			lowMidGain: -2.0,
			midFreqHz: 800,
			midGain: 2.2,
			presenceFreqHz: 3200,
			presenceGain: 4.5,
			airFreqHz: 10000,
			airGain: 2.5,
		},
		preampType: 'api_512',
		preampDrive: 0.55,
		proximityStrength: 0.3,
	},

	// ═════════════════════════════════════════════════════════════════════════════
	// 🥁 4. GEM BATERIA (DRUM & PERCUSSION MICS)
	// ═════════════════════════════════════════════════════════════════════════════
	{
		id: 'shure-beta52a',
		name: 'Beta 52A Supercardioid Kick',
		brand: 'Shure',
		category: 'drums',
		capsule: 'dynamic',
		polarPattern: 'supercardioid',
		year: 1996,
		country: 'USA',
		icon: '💥',
		famousUsers: 'Eloy Casagrande (Slipknot), Mike Portnoy (Dream Theater)',
		soundDescription:
			'Sub-grave colossal de 50Hz, corte cirúrgico em 500Hz e estalo agudo de batedor em 4.5kHz.',
		eqResponse: {
			lowCutHz: 25,
			subBassGain: 6.0,
			bassGain: 4.2,
			lowMidGain: -4.0,
			midFreqHz: 600,
			midGain: -2.5,
			presenceFreqHz: 4500,
			presenceGain: 6.2,
			airFreqHz: 12000,
			airGain: 1.5,
		},
		preampType: 'api_512',
		preampDrive: 0.5,
		proximityStrength: 0.85,
	},
	{
		id: 'audix-d6-kick',
		name: 'D6 Low-Frequency Speed Kick',
		brand: 'Audix',
		category: 'drums',
		capsule: 'dynamic',
		polarPattern: 'cardioid',
		year: 2002,
		country: 'USA',
		icon: '⚡',
		famousUsers: 'Tomas Haake (Meshuggah), Chris Adler (Lamb of God)',
		soundDescription:
			'Resposta ultrarrápida até 30Hz com clique hiper-nítido sem embolar em pedal duplo veloz.',
		eqResponse: {
			lowCutHz: 20,
			subBassGain: 6.5,
			bassGain: 3.5,
			lowMidGain: -5.0,
			midFreqHz: 700,
			midGain: -3.0,
			presenceFreqHz: 4800,
			presenceGain: 6.8,
			airFreqHz: 11000,
			airGain: 2.0,
		},
		preampType: 'api_512',
		preampDrive: 0.55,
		proximityStrength: 0.8,
	},
	{
		id: 'shure-sm57-snare',
		name: 'SM57 Snare Top Classic',
		brand: 'Shure',
		category: 'drums',
		capsule: 'dynamic',
		polarPattern: 'cardioid',
		year: 1965,
		country: 'USA',
		icon: '🥁',
		famousUsers: 'Lars Ulrich, Dave Grohl, John Bonham',
		soundDescription:
			'O estalo de caixa clássico: corpo em 200Hz, estalo cortante em 5kHz e absorção pura de SPL.',
		eqResponse: {
			lowCutHz: 80,
			subBassGain: -1.0,
			bassGain: 2.0,
			lowMidGain: 2.5,
			midFreqHz: 1200,
			midGain: 1.0,
			presenceFreqHz: 5000,
			presenceGain: 5.5,
			airFreqHz: 10000,
			airGain: 2.0,
		},
		preampType: 'api_512',
		preampDrive: 0.5,
		proximityStrength: 0.7,
	},
	{
		id: 'neumann-km184-overheads',
		name: 'KM 184 Stereo Overheads',
		brand: 'Neumann',
		category: 'drums',
		capsule: 'condenser_small',
		polarPattern: 'cardioid',
		year: 1993,
		country: 'Germany',
		icon: '✨',
		famousUsers: 'Abbey Road Studios, Fascination Street (Jens Bogren)',
		soundDescription:
			'Overheads cristalinos: transientes rápidos de pratos, brilho sedoso de 14kHz e imagem estéreo 3D.',
		eqResponse: {
			lowCutHz: 80,
			subBassGain: -2.0,
			bassGain: 0.0,
			lowMidGain: 0.0,
			midFreqHz: 2500,
			midGain: 1.0,
			presenceFreqHz: 6000,
			presenceGain: 3.8,
			airFreqHz: 14000,
			airGain: 6.0,
		},
		preampType: 'ssl_e',
		preampDrive: 0.25,
		proximityStrength: 0.4,
	},
	{
		id: 'coles-4038-room',
		name: 'Coles 4038 BBC Studio Ribbon Room',
		brand: 'Coles Electroacoustics',
		category: 'drums',
		capsule: 'ribbon',
		polarPattern: 'figure_8',
		year: 1953,
		country: 'UK',
		icon: '🏰',
		famousUsers: 'Glyn Johns (Led Zeppelin), Pink Floyd',
		soundDescription:
			'Microfones de sala gigantescos: graves colossais, compressão natural e ambiência analógica.',
		eqResponse: {
			lowCutHz: 35,
			subBassGain: 3.5,
			bassGain: 4.5,
			lowMidGain: 3.0,
			midFreqHz: 1500,
			midGain: 1.0,
			presenceFreqHz: 3500,
			presenceGain: 1.2,
			airFreqHz: 9000,
			airGain: 0.0,
		},
		preampType: 'neve_1073',
		preampDrive: 0.5,
		proximityStrength: 0.9,
	},

	// ═════════════════════════════════════════════════════════════════════════════
	// 🎹 5. GEM SYNTHS, ACÚSTICOS & FX (STEREO ROOM & SYNTH MICS)
	// ═════════════════════════════════════════════════════════════════════════════
	{
		id: 'akg-c414-stereo-synths',
		name: 'AKG C414 XLS Matched Stereo Pair',
		brand: 'AKG',
		category: 'synths',
		capsule: 'condenser_large',
		polarPattern: 'cardioid',
		year: 1971,
		country: 'Austria',
		icon: '🎹',
		famousUsers: 'Jordan Rudess (Dream Theater), Tuomas Holopainen (Nightwish)',
		soundDescription:
			'Par estéreo casado: imagem ampla e linear de sintetizadores analógicos, pianos e orquestrações.',
		eqResponse: {
			lowCutHz: 40,
			subBassGain: 1.0,
			bassGain: 1.5,
			lowMidGain: 0.5,
			midFreqHz: 2200,
			midGain: 1.0,
			presenceFreqHz: 5000,
			presenceGain: 3.5,
			airFreqHz: 13000,
			airGain: 4.5,
		},
		preampType: 'ssl_e',
		preampDrive: 0.3,
		proximityStrength: 0.5,
	},
	{
		id: 'royer-sf24-blumlein',
		name: 'Royer SF-24 Stereo Ribbon (Blumlein)',
		brand: 'Royer Labs',
		category: 'synths',
		capsule: 'ribbon',
		polarPattern: 'figure_8',
		year: 2001,
		country: 'USA',
		icon: '🌐',
		famousUsers: 'Hans Zimmer, Brian May (Strings & Synths)',
		soundDescription:
			'Coincidência estéreo Blumlein a fita: profundidade espacial tridimensional com suavidade aveludada.',
		eqResponse: {
			lowCutHz: 40,
			subBassGain: 2.5,
			bassGain: 3.8,
			lowMidGain: 2.0,
			midFreqHz: 1800,
			midGain: 1.0,
			presenceFreqHz: 3500,
			presenceGain: 2.0,
			airFreqHz: 11000,
			airGain: 2.0,
		},
		preampType: 'neve_1073',
		preampDrive: 0.42,
		proximityStrength: 0.7,
	},
	{
		id: 'dpa-4006-omni',
		name: 'DPA 4006A Omnidirectional Reference',
		brand: 'DPA Microphones',
		category: 'synths',
		capsule: 'condenser_small',
		polarPattern: 'omni',
		year: 1982,
		country: 'Denmark',
		icon: '💎',
		famousUsers: 'London Symphony Orchestra, Vangelis (Blade Runner)',
		soundDescription:
			'Precisão acústica omnidirecional de referência com resposta de fase linear de 10Hz a 40kHz.',
		eqResponse: {
			lowCutHz: 20,
			subBassGain: 2.0,
			bassGain: 1.5,
			lowMidGain: 0.0,
			midFreqHz: 2000,
			midGain: 0.5,
			presenceFreqHz: 6000,
			presenceGain: 2.0,
			airFreqHz: 16000,
			airGain: 5.0,
		},
		preampType: 'avalon_pure',
		preampDrive: 0.2,
		proximityStrength: 0.1,
	},
	{
		id: 'schoeps-colette-mk4',
		name: 'Schoeps Colette MK4 Stereo Set',
		brand: 'Schoeps',
		category: 'synths',
		capsule: 'condenser_small',
		polarPattern: 'cardioid',
		year: 1973,
		country: 'Germany',
		icon: '🏛️',
		famousUsers: 'Wiener Philharmoniker, Peter Gabriel',
		soundDescription:
			'A pureza clássica alemã para pads, cordas e synths com neutralidade e campo estéreo luxuoso.',
		eqResponse: {
			lowCutHz: 35,
			subBassGain: 1.2,
			bassGain: 1.8,
			lowMidGain: 0.5,
			midFreqHz: 2000,
			midGain: 0.8,
			presenceFreqHz: 4500,
			presenceGain: 2.5,
			airFreqHz: 14000,
			airGain: 4.8,
		},
		preampType: 'avalon_pure',
		preampDrive: 0.22,
		proximityStrength: 0.4,
	},
]
