export type MicCategory = 'vocals' | 'guitars' | 'drums' | 'bass' | 'acoustic_room';
export type CapsuleType = 'dynamic' | 'condenser_large' | 'condenser_small' | 'tube' | 'ribbon' | 'fet_di';
export type PolarPattern = 'cardioid' | 'supercardioid' | 'hypercardioid' | 'omni' | 'figure_8';

export interface MicrophoneModel {
  id: string;
  name: string;
  brand: string;
  category: MicCategory;
  capsule: CapsuleType;
  polarPattern: PolarPattern;
  year: number;
  country: string;
  icon: string;
  famousUsers: string;
  soundDescription: string;
  eqResponse: {
    lowCutHz: number;
    subBassGain: number; // dB
    bassGain: number;    // dB
    lowMidGain: number;  // dB
    midFreqHz: number;
    midGain: number;     // dB
    presenceFreqHz: number;
    presenceGain: number;// dB
    airFreqHz: number;
    airGain: number;     // dB
  };
  preampType: 'neve_1073' | 'api_512' | 'ssl_e' | 'tube_tech' | 'avalon_pure';
  preampDrive: number; // 0.0 to 1.0
  proximityStrength: number; // 0.0 to 1.0 (bass boost at close distance)
}

export const LEGENDARY_MICROPHONES: MicrophoneModel[] = [
  // ─── VOCAL LEGENDS ──────────────────────────────────────────────────────────
  {
    id: 'shure-sm7b',
    name: 'SM7B Studio Dynamic',
    brand: 'Shure',
    category: 'vocals',
    capsule: 'dynamic',
    polarPattern: 'cardioid',
    year: 1973,
    country: 'USA',
    icon: '🎙️',
    famousUsers: 'James Hetfield (Metallica), Serj Tankian (SOAD), Michael Jackson (Thriller), Bruce Dickinson',
    soundDescription: 'O microfone dinâmico mais lendário do metal e rock: médios encorpados e quentes, resposta suave a transientes agressivos e chave de boost de presença.',
    eqResponse: {
      lowCutHz: 80,
      subBassGain: 1.5,
      bassGain: 2.8,
      lowMidGain: 1.2,
      midFreqHz: 2000,
      midGain: 1.0,
      presenceFreqHz: 5000,
      presenceGain: 3.5,
      airFreqHz: 12000,
      airGain: 1.0,
    },
    preampType: 'neve_1073',
    preampDrive: 0.45,
    proximityStrength: 0.70,
  },
  {
    id: 'neumann-u87-ai',
    name: 'U87 Ai Large Diaphragm Condenser',
    brand: 'Neumann',
    category: 'vocals',
    capsule: 'condenser_large',
    polarPattern: 'cardioid',
    year: 1967,
    country: 'Germany',
    icon: '👑',
    famousUsers: 'Ronnie James Dio, Bruce Dickinson, Rob Halford, Klaus Meine, Ozzy Osbourne',
    soundDescription: 'O padrão-ouro absoluto dos estúdios mundiais: presença aveludada em 3.5kHz, graves neutros e agudos sedosos impecáveis com cápsula K67.',
    eqResponse: {
      lowCutHz: 60,
      subBassGain: 0.0,
      bassGain: 1.0,
      lowMidGain: 0.5,
      midFreqHz: 1800,
      midGain: 1.2,
      presenceFreqHz: 3800,
      presenceGain: 4.2,
      airFreqHz: 12000,
      airGain: 4.5,
    },
    preampType: 'ssl_e',
    preampDrive: 0.35,
    proximityStrength: 0.65,
  },
  {
    id: 'neumann-u47-tube',
    name: 'U47 Vintage Tube',
    brand: 'Neumann / Telefunken',
    category: 'vocals',
    capsule: 'tube',
    polarPattern: 'cardioid',
    year: 1949,
    country: 'Germany',
    icon: '✨',
    famousUsers: 'The Beatles, Frank Sinatra, Freddie Mercury, David Gilmour',
    soundDescription: 'O microfone valvulado mais cobiçado da história da música: válvula VF14 com graves gigantescos, médios tridimensionais ricos e brilho dourado.',
    eqResponse: {
      lowCutHz: 45,
      subBassGain: 2.2,
      bassGain: 3.5,
      lowMidGain: 2.0,
      midFreqHz: 1500,
      midGain: 1.5,
      presenceFreqHz: 3200,
      presenceGain: 3.8,
      airFreqHz: 10000,
      airGain: 3.5,
    },
    preampType: 'tube_tech',
    preampDrive: 0.55,
    proximityStrength: 0.85,
  },
  {
    id: 'telefunken-ela-m251',
    name: 'ELA M 251E Diamond Series',
    brand: 'Telefunken',
    category: 'vocals',
    capsule: 'tube',
    polarPattern: 'cardioid',
    year: 1960,
    country: 'Austria / Germany',
    icon: '💎',
    famousUsers: 'André Matos (Angra/Shaman), Mariah Carey, Michael Jackson',
    soundDescription: 'O ápice da abertura aérea e pureza vocal: cápsula CK12 de terminação em borda com agudos abertos de 14kHz aveludados e transparência luxuosa.',
    eqResponse: {
      lowCutHz: 50,
      subBassGain: 0.5,
      bassGain: 1.8,
      lowMidGain: 0.8,
      midFreqHz: 2500,
      midGain: 2.0,
      presenceFreqHz: 4500,
      presenceGain: 4.0,
      airFreqHz: 14000,
      airGain: 6.0,
    },
    preampType: 'tube_tech',
    preampDrive: 0.40,
    proximityStrength: 0.60,
  },
  {
    id: 'sony-c800g',
    name: 'C-800G Studio Tube Condenser',
    brand: 'Sony',
    category: 'vocals',
    capsule: 'tube',
    polarPattern: 'cardioid',
    year: 1992,
    country: 'Japan',
    icon: '⚡',
    famousUsers: 'Modern Metalcore Screams, Pop/Rock High Vocals, Sebastian Bach',
    soundDescription: 'Sistema de refrigeração Peltier externo: definição de alta frequência incomparável, resposta de transiente ultrarrápida e presença hiper-moderna.',
    eqResponse: {
      lowCutHz: 70,
      subBassGain: -0.5,
      bassGain: 1.2,
      lowMidGain: -0.5,
      midFreqHz: 3000,
      midGain: 2.5,
      presenceFreqHz: 5500,
      presenceGain: 5.2,
      airFreqHz: 15000,
      airGain: 6.5,
    },
    preampType: 'avalon_pure',
    preampDrive: 0.30,
    proximityStrength: 0.55,
  },
  {
    id: 'akg-c414-xls',
    name: 'C414 XLS Multi-Pattern',
    brand: 'AKG',
    category: 'vocals',
    capsule: 'condenser_large',
    polarPattern: 'cardioid',
    year: 1971,
    country: 'Austria',
    icon: '🎛️',
    famousUsers: 'Geoff Tate (Queensrÿche), Kai Hansen (Helloween), Freddie Mercury',
    soundDescription: 'Neutro, cirúrgico e articulado: resposta de frequência linear de 20Hz a 20kHz com leve realce em 5kHz ideal para vocais agudos e líricos.',
    eqResponse: {
      lowCutHz: 55,
      subBassGain: 0.0,
      bassGain: 1.0,
      lowMidGain: 0.0,
      midFreqHz: 2200,
      midGain: 1.0,
      presenceFreqHz: 5000,
      presenceGain: 3.5,
      airFreqHz: 12000,
      airGain: 4.0,
    },
    preampType: 'api_512',
    preampDrive: 0.35,
    proximityStrength: 0.60,
  },
  {
    id: 'electrovoice-re20',
    name: 'RE20 Variable-D Broadcast Dynamic',
    brand: 'Electro-Voice',
    category: 'vocals',
    capsule: 'dynamic',
    polarPattern: 'cardioid',
    year: 1968,
    country: 'USA',
    icon: '🎙️',
    famousUsers: 'Thom Yorke, Stevie Wonder, Heavy Metal Screams & Growls',
    soundDescription: 'Tecnologia Variable-D com zero efeito de proximidade indesejado: som firme, graves estáveis mesmo cantando colado na grade e médios consistentes.',
    eqResponse: {
      lowCutHz: 60,
      subBassGain: 1.2,
      bassGain: 2.0,
      lowMidGain: 1.5,
      midFreqHz: 1600,
      midGain: 1.5,
      presenceFreqHz: 4200,
      presenceGain: 3.0,
      airFreqHz: 11000,
      airGain: 1.8,
    },
    preampType: 'api_512',
    preampDrive: 0.40,
    proximityStrength: 0.30,
  },

  // ─── GUITAR CABINET & AMPS ──────────────────────────────────────────────────
  {
    id: 'shure-sm57-cab',
    name: 'SM57 Instrument Dynamic (Guitar Cone)',
    brand: 'Shure',
    category: 'guitars',
    capsule: 'dynamic',
    polarPattern: 'cardioid',
    year: 1965,
    country: 'USA',
    icon: '🎸',
    famousUsers: 'Dimebag Darrell, James Hetfield, Slash, Adrian Smith, Kerry King',
    soundDescription: 'O microfone que gravou quase todas as guitarras de metal da história: mordida agressiva de palhetada entre 3kHz e 6kHz com graves controlados.',
    eqResponse: {
      lowCutHz: 90,
      subBassGain: -1.0,
      bassGain: 1.5,
      lowMidGain: 2.2,
      midFreqHz: 2500,
      midGain: 2.5,
      presenceFreqHz: 5000,
      presenceGain: 5.5,
      airFreqHz: 10000,
      airGain: 1.0,
    },
    preampType: 'api_512',
    preampDrive: 0.50,
    proximityStrength: 0.75,
  },
  {
    id: 'royer-r121-ribbon',
    name: 'R-121 Studio Ribbon',
    brand: 'Royer Labs',
    category: 'guitars',
    capsule: 'ribbon',
    polarPattern: 'figure_8',
    year: 1998,
    country: 'USA',
    icon: '⚡',
    famousUsers: 'Andy Sneap, Colin Richardson, Metallica (Load/Reload), Tool, Foo Fighters',
    soundDescription: 'O fita supremo para guitarras pesadas: graves encorpados aveludados, médios densos e agudos sedosos sem nenhuma aspereza digital.',
    eqResponse: {
      lowCutHz: 40,
      subBassGain: 3.0,
      bassGain: 4.5,
      lowMidGain: 3.0,
      midFreqHz: 1200,
      midGain: 1.0,
      presenceFreqHz: 3000,
      presenceGain: 1.5,
      airFreqHz: 8000,
      airGain: -1.0,
    },
    preampType: 'neve_1073',
    preampDrive: 0.48,
    proximityStrength: 0.90,
  },
  {
    id: 'sennheiser-md421',
    name: 'MD 421-II Dynamic',
    brand: 'Sennheiser',
    category: 'guitars',
    capsule: 'dynamic',
    polarPattern: 'cardioid',
    year: 1960,
    country: 'Germany',
    icon: '🔊',
    famousUsers: 'Tony Iommi (Black Sabbath), Tom Morello, Alex Lifeson (Rush)',
    soundDescription: 'Excelente resposta a transientes com médios-graves recortados e presença brilhante: perfeito para riffs pesados e timbres de amplificador valvulado.',
    eqResponse: {
      lowCutHz: 70,
      subBassGain: 0.5,
      bassGain: 2.2,
      lowMidGain: 1.8,
      midFreqHz: 2800,
      midGain: 2.0,
      presenceFreqHz: 4500,
      presenceGain: 4.8,
      airFreqHz: 12000,
      airGain: 2.5,
    },
    preampType: 'ssl_e',
    preampDrive: 0.42,
    proximityStrength: 0.70,
  },
  {
    id: 'sennheiser-e906',
    name: 'e906 Guitar Amp Dynamic',
    brand: 'Sennheiser',
    category: 'guitars',
    capsule: 'dynamic',
    polarPattern: 'supercardioid',
    year: 2004,
    country: 'Germany',
    icon: '🎙️',
    famousUsers: 'Dave Mustaine (Megadeth), Zakk Wylde, Gary Holt (Exodus/Slayer)',
    soundDescription: 'Design achatado para encostar direto na grade do amplificador: ataque imediato de palheta e médios cortantes com chave de presença.',
    eqResponse: {
      lowCutHz: 85,
      subBassGain: -0.5,
      bassGain: 1.8,
      lowMidGain: 2.0,
      midFreqHz: 3000,
      midGain: 3.0,
      presenceFreqHz: 4800,
      presenceGain: 5.0,
      airFreqHz: 11000,
      airGain: 2.0,
    },
    preampType: 'api_512',
    preampDrive: 0.45,
    proximityStrength: 0.65,
  },

  // ─── DRUMS & PERCUSSION ─────────────────────────────────────────────────────
  {
    id: 'akg-d112-kick',
    name: 'D112 MKII "The Egg" Kick Drum Dynamic',
    brand: 'AKG',
    category: 'drums',
    capsule: 'dynamic',
    polarPattern: 'cardioid',
    year: 1986,
    country: 'Austria',
    icon: '🥁',
    famousUsers: 'Lars Ulrich (Black Album), Vinnie Paul (Pantera), Nicko McBrain (Iron Maiden)',
    soundDescription: 'A lenda do bumbo de metal: grave monstruoso e ressonante em 60Hz e estalo cirúrgico de batedor em 4kHz pronto para perfurar a mixagem.',
    eqResponse: {
      lowCutHz: 30,
      subBassGain: 5.5,
      bassGain: 3.8,
      lowMidGain: -3.5,
      midFreqHz: 800,
      midGain: -2.0,
      presenceFreqHz: 4200,
      presenceGain: 5.8,
      airFreqHz: 10000,
      airGain: 1.0,
    },
    preampType: 'ssl_e',
    preampDrive: 0.52,
    proximityStrength: 0.90,
  },
  {
    id: 'shure-beta52a',
    name: 'Beta 52A Supercardioid Kick',
    brand: 'Shure',
    category: 'drums',
    capsule: 'dynamic',
    polarPattern: 'supercardioid',
    year: 1996,
    country: 'USA',
    icon: '💥',
    famousUsers: 'Eloy Casagrande (Sepultura/Slipknot), Mike Portnoy (Dream Theater)',
    soundDescription: 'Curva esculpida de fábrica para bumbos modernos: sub-grave colossal de 50Hz, corte cirúrgico de médios em 500Hz e ataque agudo de 4.5kHz.',
    eqResponse: {
      lowCutHz: 25,
      subBassGain: 6.0,
      bassGain: 4.2,
      lowMidGain: -4.0,
      midFreqHz: 600,
      midGain: -2.5,
      presenceFreqHz: 4500,
      presenceGain: 6.2,
      airFreqHz: 12000,
      airGain: 1.5,
    },
    preampType: 'api_512',
    preampDrive: 0.50,
    proximityStrength: 0.85,
  },
  {
    id: 'audix-d6-kick',
    name: 'D6 Very Low-Frequency Kick Dynamic',
    brand: 'Audix',
    category: 'drums',
    capsule: 'dynamic',
    polarPattern: 'cardioid',
    year: 2002,
    country: 'USA',
    icon: '⚡',
    famousUsers: 'Meshuggah (Tomas Haake), Trivium, Lamb of God (Chris Adler)',
    soundDescription: 'O microfone do bumbo duplo de velocidade: resposta estendida até 30Hz com clique hiper-rápido de madeira/plástico sem embolar em 200 BPM.',
    eqResponse: {
      lowCutHz: 20,
      subBassGain: 6.5,
      bassGain: 3.5,
      lowMidGain: -5.0,
      midFreqHz: 700,
      midGain: -3.0,
      presenceFreqHz: 4800,
      presenceGain: 6.8,
      airFreqHz: 11000,
      airGain: 2.0,
    },
    preampType: 'api_512',
    preampDrive: 0.55,
    proximityStrength: 0.80,
  },
  {
    id: 'neumann-km184-overheads',
    name: 'KM 184 Small Diaphragm Condenser',
    brand: 'Neumann',
    category: 'drums',
    capsule: 'condenser_small',
    polarPattern: 'cardioid',
    year: 1993,
    country: 'Germany',
    icon: '✨',
    famousUsers: 'Abbey Road Studios, Fascination Street (Jens Bogren), Studio Fredman',
    soundDescription: 'O padrão de Overheads e pratos de estúdio: transientes ultrarrápidos, brilho sedoso de 12kHz a 20kHz sem distorção e imagem estéreo expansiva.',
    eqResponse: {
      lowCutHz: 80,
      subBassGain: -2.0,
      bassGain: 0.0,
      lowMidGain: 0.0,
      midFreqHz: 2500,
      midGain: 1.0,
      presenceFreqHz: 6000,
      presenceGain: 3.8,
      airFreqHz: 14000,
      airGain: 6.0,
    },
    preampType: 'ssl_e',
    preampDrive: 0.25,
    proximityStrength: 0.40,
  },

  // ─── BASS GUITAR & CAB ──────────────────────────────────────────────────────
  {
    id: 'neumann-u47-fet-bass',
    name: 'U47 FET Low-End Precision',
    brand: 'Neumann',
    category: 'bass',
    capsule: 'fet_di',
    polarPattern: 'cardioid',
    year: 1969,
    country: 'Germany',
    icon: '🎸',
    famousUsers: 'Steve Harris (Iron Maiden), Rex Brown (Pantera), Cliff Burton (Metallica)',
    soundDescription: 'Circuito de transistor FET para suportar altíssima pressão sonora: grave sólido e articulado com pegada rápida e corpo denso de baixo.',
    eqResponse: {
      lowCutHz: 35,
      subBassGain: 4.5,
      bassGain: 4.0,
      lowMidGain: 2.2,
      midFreqHz: 1200,
      midGain: 1.5,
      presenceFreqHz: 2800,
      presenceGain: 3.2,
      airFreqHz: 9000,
      airGain: 1.8,
    },
    preampType: 'neve_1073',
    preampDrive: 0.48,
    proximityStrength: 0.85,
  },
  {
    id: 'avalon-u5-di',
    name: 'Avalon U5 High-Voltage Direct Box',
    brand: 'Avalon Design',
    category: 'bass',
    capsule: 'fet_di',
    polarPattern: 'cardioid',
    year: 1995,
    country: 'USA',
    icon: '⚡',
    famousUsers: 'Felipe Andreoli (Angra), John Myung (Dream Theater), Duff McKagan',
    soundDescription: 'Pré-amplificador Classe A de alta voltagem 100% discreto: pureza cristalina de notas rápidas, graves aveludados e agudos de estalo de corda.',
    eqResponse: {
      lowCutHz: 25,
      subBassGain: 4.0,
      bassGain: 3.5,
      lowMidGain: 1.0,
      midFreqHz: 1500,
      midGain: 1.0,
      presenceFreqHz: 3200,
      presenceGain: 3.5,
      airFreqHz: 12000,
      airGain: 4.0,
    },
    preampType: 'avalon_pure',
    preampDrive: 0.28,
    proximityStrength: 0.20,
  },
];
