/**
 * Master of Masters Studio Pro — Complete Dream Theater Discography & Producers Database.
 *
 * Contains ALL 16 Dream Theater studio albums with their historical producers, hardware setups,
 * and calibrated 10-band mastering EQ, tape saturation, and stem definitions.
 */

import type { MasterProducer } from './masters-database'

export const PRODUCERS_DREAM_THEATER_COMPLETE: MasterProducer[] = [
	{
		id: 'producer_john_petrucci_mike_portnoy',
		name: 'John Petrucci & Mike Portnoy',
		title: 'The Progressive Metal Architects',
		category: 'prog_synth',
		era: '1999–2025',
		country: 'USA',
		bio: 'A lendária dupla de produção por trás da era de ouro do Dream Theater (Scenes from a Memory, Six Degrees, Train of Thought, Octavarium, Systematic Chaos, Black Clouds e Parasomnia). Conhecidos pelo som colossal de guitarra Mesa Boogie Mark IIC+/JP-2C, bateria monumental com bumbo duplo ultra-articulado, baixo cristalino de 6 cordas e camadas épicas de teclados Kurzweil/Korg.',
		albums: [
			{
				id: 'dt_scenes_from_a_memory',
				albumTitle: 'Metropolis Pt. 2: Scenes from a Memory',
				band: 'Dream Theater',
				year: 1999,
				hardwareChain:
					'Mesa Boogie Mark IIC+ & Dual Rectifier, Tama Starclassic Maple Kit, Ernie Ball Music Man JP6, Neve VR Console, Lexicon 480L Reverb, TC 2290 Delay, SSL G-Bus Compressor',
				soundSignature:
					'A obra-prima conceitual do metal progressivo. Transientes dinâmicos ultra-coerentes, médios cirúrgicos na guitarra base, voz emotiva com reverb de placa quente e bumbo perfurante com sub-graves redondos.',
				targetLufs: -13.5,
				tuningSignature: {
					standardName: 'E Standard (440Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 110,
					midScoopHz: 650,
					midScoopGainDb: -2.5,
					bitePresenceHz: 3500,
					biteGainDb: 3.2,
					cabHighCutHz: 6800,
					distortionGain: 0.68,
					stereoSpread: 1.35,
					description:
						'O timbre definitivo de John Petrucci no Mark IIC+: corpo encorpado nos graves, crunch focado nos médios e agudos aveludados com sustain infinito.',
				},
				eq10Band: {
					hz30: 1.5,
					hz60: 2.8,
					hz120: 1.2,
					hz250: -1.0,
					hz500: -1.8,
					hz1000: 0.8,
					hz2500: 2.5,
					hz4000: 3.0,
					hz8000: 2.2,
					hz16000: 1.8,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.42,
				},
				compressor: {
					threshold: -18.0,
					ratio: 3.5,
					attack: 25.0,
					release: 120.0,
					knee: 3.0,
				},
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0.5,
						eq: { sub: 3.2, punch: 2.5, attack: 3.8, air: 2.0 },
						saturation: 'ssl_vca',
						drive: 0.35,
						compRatio: 4.0,
						compAttack: 20,
						compRelease: 100,
						description:
							'Kit Tama Starclassic com bumbo duplo perfurante e estalo de caixa preciso com gated plate.',
					},
					bass: {
						volumeDb: -0.5,
						eq: { subBass: 2.8, grit: 2.2, cutMids: -2.0, clarity: 2.6 },
						saturation: 'ampeg_svt',
						drive: 0.38,
						compRatio: 4.5,
						compAttack: 15,
						compRelease: 120,
						description:
							'Baixo 6 cordas Yamaha TRB John Myung com definição perfeita de notas e peso nos 40Hz.',
					},
					guitars: {
						volumeDb: 0.8,
						eq: { lowCut: 80, body: 2.0, bite: 3.0, sheen: 2.2 },
						saturation: 'mesa_rectifier',
						drive: 0.55,
						stereoWidth: 1.4,
						description:
							'Guitarras dobradas com Mark IIC+ e cabine 4x12 Celestion V30 com foco cirúrgico.',
					},
					vocals: {
						volumeDb: 1.2,
						eq: { body: 1.5, clarity: 2.8, presence: 3.2, air: 2.5 },
						saturation: 'la2a_opto',
						drive: 0.28,
						compRatio: 3.0,
						compAttack: 20,
						compRelease: 180,
						description:
							'James LaBrie em seu ápice vocal, com densidade analógica e plate reverb Lexicon 480L.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 1.0, presence: 2.2, air: 2.8 },
						saturation: 'pultec_tube',
						drive: 0.25,
						stereoWidth: 1.45,
						description:
							'Jordan Rudess com solos de sintetizador Kurzweil K2600 e piano espacial expansivo.',
					},
				},
			},
			{
				id: 'dt_six_degrees',
				albumTitle: 'Six Degrees of Inner Turbulence',
				band: 'Dream Theater',
				year: 2002,
				hardwareChain:
					'Mesa Boogie Dual Rectifier & Road King, Tama Starclassic, SSL 9000J Console, Eventide H3000, Ampex ATR-102 Master Tape',
				soundSignature:
					'Sonoridade monumental, pesada e orquestral. Guitarras de 7 cordas ultra-definidas (The Glass Prison), bateria maciça e dinâmica sinfônica impecável.',
				targetLufs: -12.5,
				tuningSignature: {
					standardName: 'B Standard (7-string) / E Standard',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 61.7,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 95,
					midScoopHz: 700,
					midScoopGainDb: -2.0,
					bitePresenceHz: 3800,
					biteGainDb: 3.5,
					cabHighCutHz: 7000,
					distortionGain: 0.75,
					stereoSpread: 1.4,
					description:
						'O lendário timbre de 7 cordas do Petrucci em The Glass Prison: ataque de palheta percussivo e peso sísmico.',
				},
				eq10Band: {
					hz30: 2.0,
					hz60: 3.2,
					hz120: 1.8,
					hz250: -0.8,
					hz500: -1.5,
					hz1000: 1.0,
					hz2500: 2.8,
					hz4000: 3.2,
					hz8000: 2.5,
					hz16000: 2.0,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.48,
				},
				compressor: {
					threshold: -17.5,
					ratio: 4.0,
					attack: 20.0,
					release: 100.0,
					knee: 3.5,
				},
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 0.8,
						eq: { sub: 3.5, punch: 2.8, attack: 4.0, air: 2.2 },
						saturation: 'ssl_vca',
						drive: 0.4,
						compRatio: 4.5,
						compAttack: 18,
						compRelease: 90,
						description:
							'Mike Portnoy com pratos Sabian brilhantes, bumbo duplo em fita e caixa agressiva.',
					},
					bass: {
						volumeDb: -0.2,
						eq: { subBass: 3.0, grit: 2.5, cutMids: -1.8, clarity: 2.8 },
						saturation: 'darkglass_b7k',
						drive: 0.42,
						compRatio: 5.0,
						compAttack: 12,
						compRelease: 100,
						description:
							'Baixo com ataque percussivo casando perfeitamente com os riffs de 7 cordas.',
					},
					guitars: {
						volumeDb: 1.0,
						eq: { lowCut: 75, body: 2.2, bite: 3.5, sheen: 2.5 },
						saturation: 'mesa_rectifier',
						drive: 0.65,
						stereoWidth: 1.42,
						description:
							'Paredão de guitarras de 7 cordas abertas nos extremos L e R com clareza cristalina.',
					},
					vocals: {
						volumeDb: 1.0,
						eq: { body: 1.8, clarity: 2.5, presence: 3.0, air: 2.2 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.2,
						compAttack: 25,
						compRelease: 160,
						description:
							'Vocais com compressão analógica quente e dobras harmônicas com Mike Portnoy.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.2, presence: 2.5, air: 3.0 },
						saturation: 'pultec_tube',
						drive: 0.28,
						stereoWidth: 1.48,
						description:
							'Arranjos orquestrais monumentais com profundidade 3D e sintetizadores rasgados.',
					},
				},
			},
			{
				id: 'dt_train_of_thought',
				albumTitle: 'Train of Thought',
				band: 'Dream Theater',
				year: 2003,
				hardwareChain:
					'Mesa Boogie Road King & Lonestar, Tama Starclassic Birch, Mixed by Kevin Shirley, Mastered by George Marino at Sterling Sound, Studer A800 24-track, SSL 4000G Console',
				soundSignature:
					'O álbum mais pesado e violento do Dream Theater. Graves maciços em afinações C e D, ataque de palheta rasgando as caixas, bumbo metralhadora com sub-graves de impacto e caixa potente.',
				targetLufs: -11.0,
				tuningSignature: {
					standardName: 'Drop C / D Standard / C Standard',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 65.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 100,
					midScoopHz: 600,
					midScoopGainDb: -1.5,
					bitePresenceHz: 4000,
					biteGainDb: 4.2,
					cabHighCutHz: 7200,
					distortionGain: 0.85,
					stereoSpread: 1.42,
					description:
						'O timbre mais thrash/heavy metal de John Petrucci: saturação densa, graves cortantes e harmônicos artificiais explodindo.',
				},
				eq10Band: {
					hz30: 2.5,
					hz60: 3.8,
					hz120: 2.2,
					hz250: -0.5,
					hz500: -1.2,
					hz1000: 1.2,
					hz2500: 3.2,
					hz4000: 3.8,
					hz8000: 2.8,
					hz16000: 2.2,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.58,
				},
				compressor: {
					threshold: -16.0,
					ratio: 4.5,
					attack: 15.0,
					release: 80.0,
					knee: 4.0,
				},
				stereoWidth: 1.42,
				gemSetup: {
					drums: {
						volumeDb: 1.2,
						eq: { sub: 4.0, punch: 3.2, attack: 4.5, air: 2.5 },
						saturation: 'distressor_nuke',
						drive: 0.48,
						compRatio: 5.0,
						compAttack: 15,
						compRelease: 80,
						description:
							'Mix de Kevin Shirley: bumbo furando a parede sonora e caixa com impacto explosivo.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.5, grit: 3.0, cutMids: -1.5, clarity: 3.2 },
						saturation: 'sansamp_di',
						drive: 0.52,
						compRatio: 5.5,
						compAttack: 10,
						compRelease: 90,
						description:
							'Baixo com SansAmp overdrive dobrando com a guitarra em As I Am e Honor Thy Father.',
					},
					guitars: {
						volumeDb: 1.5,
						eq: { lowCut: 70, body: 2.5, bite: 4.0, sheen: 2.8 },
						saturation: 'mesa_rectifier',
						drive: 0.78,
						stereoWidth: 1.45,
						description:
							'Muralha de guitarras pesadíssimas afinadas em C com definição nota-a-nota.',
					},
					vocals: {
						volumeDb: 0.8,
						eq: { body: 2.0, clarity: 2.8, presence: 3.5, air: 2.0 },
						saturation: 'fairchild_mu',
						drive: 0.35,
						compRatio: 3.8,
						compAttack: 20,
						compRelease: 140,
						description:
							'LaBrie com entrega agressiva e direta, cortando com autoridade pelo paredão.',
					},
					synthsFx: {
						volumeDb: 0.0,
						eq: { lowMids: 0.8, presence: 2.0, air: 2.5 },
						saturation: 'pultec_tube',
						drive: 0.3,
						stereoWidth: 1.4,
						description:
							'Teclados com texturas industriais e solos rápidos de uníssono com a guitarra.',
					},
				},
			},
			{
				id: 'dt_octavarium',
				albumTitle: 'Octavarium',
				band: 'Dream Theater',
				year: 2005,
				hardwareChain:
					'Mesa Boogie Road King & Mark IV, Tama Starclassic, The Hit Factory NYC, Studer A800, SSL 9000J Console, George Marino Master at Sterling Sound',
				soundSignature:
					'Produção de alta fidelidade e riqueza tímbrica com orquestra sinfônica real gravada no The Hit Factory. Equilíbrio de frequências nobre, graves quentes e agudos cristalinos.',
				targetLufs: -12.0,
				tuningSignature: {
					standardName: 'Root Octaves (F, G, A, B, C, D, E, F)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 87.3,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 105,
					midScoopHz: 650,
					midScoopGainDb: -1.8,
					bitePresenceHz: 3600,
					biteGainDb: 3.4,
					cabHighCutHz: 7000,
					distortionGain: 0.7,
					stereoSpread: 1.38,
					description:
						'Timbre fluido e cantado do solo final de Octavarium (estilo David Gilmour/Pink Floyd com pegada Petrucci).',
				},
				eq10Band: {
					hz30: 1.8,
					hz60: 2.9,
					hz120: 1.5,
					hz250: -0.8,
					hz500: -1.4,
					hz1000: 0.9,
					hz2500: 2.6,
					hz4000: 3.2,
					hz8000: 2.6,
					hz16000: 2.2,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.45,
				},
				compressor: {
					threshold: -17.0,
					ratio: 3.8,
					attack: 22.0,
					release: 110.0,
					knee: 3.2,
				},
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0.6,
						eq: { sub: 3.2, punch: 2.6, attack: 3.8, air: 2.4 },
						saturation: 'ssl_vca',
						drive: 0.36,
						compRatio: 4.2,
						compAttack: 20,
						compRelease: 95,
						description:
							'Kit dinâmico captado na sala histórica do The Hit Factory NYC com espacialidade nobre.',
					},
					bass: {
						volumeDb: -0.3,
						eq: { subBass: 2.9, grit: 2.4, cutMids: -1.8, clarity: 2.6 },
						saturation: 'ampeg_svt',
						drive: 0.38,
						compRatio: 4.8,
						compAttack: 14,
						compRelease: 110,
						description: 'Linhas melódicas de John Myung com corpo denso e clareza nos médios.',
					},
					guitars: {
						volumeDb: 0.9,
						eq: { lowCut: 80, body: 2.2, bite: 3.2, sheen: 2.6 },
						saturation: 'mesa_rectifier',
						drive: 0.62,
						stereoWidth: 1.4,
						description:
							'Variando de guitarras acústicas Taylor cintilantes até riffs pesados em Panic Attack.',
					},
					vocals: {
						volumeDb: 1.1,
						eq: { body: 1.6, clarity: 2.7, presence: 3.2, air: 2.6 },
						saturation: 'la2a_opto',
						drive: 0.28,
						compRatio: 3.0,
						compAttack: 22,
						compRelease: 170,
						description: 'Vocal com brilho aveludado e dinâmica emocional impecável.',
					},
					synthsFx: {
						volumeDb: 0.6,
						eq: { lowMids: 1.4, presence: 2.6, air: 3.2 },
						saturation: 'pultec_tube',
						drive: 0.26,
						stereoWidth: 1.48,
						description:
							'Continuum Fingerboard, Lap Steel e orquestra sinfônica com abertura 3D luxuosa.',
					},
				},
			},
			{
				id: 'dt_systematic_chaos',
				albumTitle: 'Systematic Chaos',
				band: 'Dream Theater',
				year: 2007,
				hardwareChain:
					'Mesa Boogie Lone Star & Mark IV, Tama Starclassic, Avatar Studios NYC, Mixed by Colin Richardson (Machine Head/Slipknot), Mastered by Ted Jensen',
				soundSignature:
					'Mixagem cirúrgica de metal moderno por Colin Richardson. Riffs cortantes como navalha, bumbo com transiente super-rápido e definição máxima de contrabaixo.',
				targetLufs: -11.5,
				tuningSignature: {
					standardName: 'Drop D / Drop C / Standard',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 73.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 108,
					midScoopHz: 620,
					midScoopGainDb: -1.8,
					bitePresenceHz: 4200,
					biteGainDb: 3.8,
					cabHighCutHz: 7200,
					distortionGain: 0.78,
					stereoSpread: 1.4,
					description:
						'Mordida de Colin Richardson com presença nos 4kHz e graves firmemente contidos.',
				},
				eq10Band: {
					hz30: 2.0,
					hz60: 3.4,
					hz120: 1.9,
					hz250: -0.6,
					hz500: -1.3,
					hz1000: 1.1,
					hz2500: 3.0,
					hz4000: 3.6,
					hz8000: 2.6,
					hz16000: 2.0,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.52,
				},
				compressor: {
					threshold: -16.5,
					ratio: 4.2,
					attack: 18.0,
					release: 90.0,
					knee: 3.8,
				},
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 1.0,
						eq: { sub: 3.6, punch: 3.0, attack: 4.2, air: 2.2 },
						saturation: 'ssl_vca',
						drive: 0.42,
						compRatio: 4.8,
						compAttack: 16,
						compRelease: 85,
						description:
							'Bateria ultra-articulada mixada para velocidade extrema em The Dark Eternal Night.',
					},
					bass: {
						volumeDb: -0.1,
						eq: { subBass: 3.2, grit: 2.8, cutMids: -1.6, clarity: 3.0 },
						saturation: 'darkglass_b7k',
						drive: 0.45,
						compRatio: 5.2,
						compAttack: 12,
						compRelease: 95,
						description: 'Baixo com ataque estalado e graves profundos amarrados ao bumbo.',
					},
					guitars: {
						volumeDb: 1.2,
						eq: { lowCut: 78, body: 2.4, bite: 3.8, sheen: 2.6 },
						saturation: 'mesa_rectifier',
						drive: 0.72,
						stereoWidth: 1.42,
						description: 'Riffs cortantes em Drop D com ataque preciso de palheta e sustentação.',
					},
					vocals: {
						volumeDb: 0.9,
						eq: { body: 1.7, clarity: 2.6, presence: 3.4, air: 2.2 },
						saturation: 'la2a_opto',
						drive: 0.32,
						compRatio: 3.5,
						compAttack: 20,
						compRelease: 150,
						description: 'Vocal com presenças agressivas e backing vocals rasgados de Portnoy.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.0, presence: 2.4, air: 2.8 },
						saturation: 'pultec_tube',
						drive: 0.28,
						stereoWidth: 1.44,
						description: 'Texturas sombrias, sintetizadores modulares e pads cinematográficos.',
					},
				},
			},
			{
				id: 'dt_black_clouds',
				albumTitle: 'Black Clouds & Silver Linings',
				band: 'Dream Theater',
				year: 2009,
				hardwareChain:
					'Mesa Boogie Mark V & Lone Star, Tama Starclassic Mirage/Maple, Avatar Studios NYC, Mixed by Paul Northfield (Rush/Queensrÿche), Mastered by Ted Jensen',
				soundSignature:
					'Produção épica e refinada com a mão de Paul Northfield. Claridade analógica cristalina em The Count of Tuscany e peso avassalador em A Nightmare to Remember.',
				targetLufs: -12.0,
				tuningSignature: {
					standardName: 'Drop C / Standard / A440',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 104,
					midScoopHz: 640,
					midScoopGainDb: -1.7,
					bitePresenceHz: 3700,
					biteGainDb: 3.5,
					cabHighCutHz: 7100,
					distortionGain: 0.74,
					stereoSpread: 1.4,
					description:
						'Estreia oficial do Mesa Boogie Mark V com Petrucci: o timbre mais cantado e rico em harmônicos.',
				},
				eq10Band: {
					hz30: 1.9,
					hz60: 3.0,
					hz120: 1.6,
					hz250: -0.7,
					hz500: -1.4,
					hz1000: 1.0,
					hz2500: 2.8,
					hz4000: 3.4,
					hz8000: 2.6,
					hz16000: 2.2,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.48,
				},
				compressor: {
					threshold: -17.0,
					ratio: 3.9,
					attack: 20.0,
					release: 100.0,
					knee: 3.5,
				},
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 0.8,
						eq: { sub: 3.4, punch: 2.8, attack: 4.0, air: 2.4 },
						saturation: 'ssl_vca',
						drive: 0.38,
						compRatio: 4.5,
						compAttack: 18,
						compRelease: 90,
						description:
							'Último álbum da primeira era Portnoy: bateria colossal gravada no Avatar Studios.',
					},
					bass: {
						volumeDb: -0.1,
						eq: { subBass: 3.0, grit: 2.6, cutMids: -1.7, clarity: 2.8 },
						saturation: 'ampeg_svt',
						drive: 0.4,
						compRatio: 5.0,
						compAttack: 12,
						compRelease: 105,
						description: 'Baixo com peso encorpado e definição perfeita em uníssonos rápidos.',
					},
					guitars: {
						volumeDb: 1.1,
						eq: { lowCut: 78, body: 2.3, bite: 3.5, sheen: 2.7 },
						saturation: 'mesa_rectifier',
						drive: 0.68,
						stereoWidth: 1.42,
						description:
							'Solos lendários de The Count of Tuscany e The Best of Times com sustain infinito.',
					},
					vocals: {
						volumeDb: 1.0,
						eq: { body: 1.8, clarity: 2.7, presence: 3.3, air: 2.5 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.2,
						compAttack: 22,
						compRelease: 160,
						description: 'Vocal cristalino e expressivo com reverb de sala rica.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.2, presence: 2.5, air: 3.0 },
						saturation: 'pultec_tube',
						drive: 0.28,
						stereoWidth: 1.46,
						description: 'Jordan Rudess com MorphWiz, violão acústico e orquestrações majestosas.',
					},
				},
			},
			{
				id: 'dt_parasomnia_2025',
				albumTitle: 'Parasomnia',
				band: 'Dream Theater',
				year: 2025,
				hardwareChain:
					'Mesa Boogie JP-2C & Badlander, Tama Starclassic Walnut/Birch, DTHQ Studios, Engineered by James Meslin, Mixed by Andy Sneap, Mastered by Ted Jensen at Sterling Sound',
				soundSignature:
					'O triunfante retorno de Mike Portnoy em 2025. Mixagem e masterização ultra-moderna de Andy Sneap: impacto visceral, separação 3D absoluta e fidelidade quântica.',
				targetLufs: -11.0,
				tuningSignature: {
					standardName: 'E Standard / 7-String / 8-String A440',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 112,
					midScoopHz: 680,
					midScoopGainDb: -1.9,
					bitePresenceHz: 3900,
					biteGainDb: 3.9,
					cabHighCutHz: 7300,
					distortionGain: 0.82,
					stereoSpread: 1.45,
					description:
						'O ápice do timbre de Petrucci: JP-2C com ataque instantâneo, mordida Sneap e graves maciços e controlados.',
				},
				eq10Band: {
					hz30: 2.2,
					hz60: 3.5,
					hz120: 2.0,
					hz250: -0.6,
					hz500: -1.4,
					hz1000: 1.1,
					hz2500: 3.2,
					hz4000: 3.8,
					hz8000: 2.8,
					hz16000: 2.4,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.55,
				},
				compressor: {
					threshold: -16.0,
					ratio: 4.2,
					attack: 16.0,
					release: 85.0,
					knee: 3.8,
				},
				stereoWidth: 1.45,
				gemSetup: {
					drums: {
						volumeDb: 1.1,
						eq: { sub: 3.8, punch: 3.2, attack: 4.4, air: 2.6 },
						saturation: 'ssl_vca',
						drive: 0.44,
						compRatio: 5.0,
						compAttack: 15,
						compRelease: 80,
						description:
							'Mike Portnoy 2025: ataque veloz, bumbos com punch no peito e pratos de brilho refinado.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.4, grit: 2.9, cutMids: -1.6, clarity: 3.1 },
						saturation: 'darkglass_b7k',
						drive: 0.48,
						compRatio: 5.4,
						compAttack: 10,
						compRelease: 90,
						description:
							'John Myung com Spector/Ernie Ball passando por Darkglass B7K e Ampeg SVT.',
					},
					guitars: {
						volumeDb: 1.3,
						eq: { lowCut: 75, body: 2.5, bite: 4.0, sheen: 2.9 },
						saturation: 'mesa_rectifier',
						drive: 0.76,
						stereoWidth: 1.45,
						description:
							'Mixagem de Andy Sneap: paredes de guitarras de 6, 7 e 8 cordas com definição cirúrgica.',
					},
					vocals: {
						volumeDb: 1.0,
						eq: { body: 1.9, clarity: 2.8, presence: 3.5, air: 2.6 },
						saturation: 'la2a_opto',
						drive: 0.32,
						compRatio: 3.4,
						compAttack: 18,
						compRelease: 140,
						description: 'James LaBrie com presença potente e dobras clássicas com Portnoy.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.2, presence: 2.6, air: 3.2 },
						saturation: 'pultec_tube',
						drive: 0.3,
						stereoWidth: 1.5,
						description:
							'Jordan Rudess com arranjos complexos de sintetizadores e orquestra cinematográfica 3D.',
					},
				},
			},
		],
	},
	{
		id: 'producer_david_prater',
		name: 'David Prater',
		title: 'The Platinum Hitmaker',
		category: 'prog_synth',
		era: '1992',
		country: 'USA',
		bio: 'Produtor do álbum que colocou o Dream Theater no mapa mundial: "Images and Words" (com o clássico "Pull Me Under"). Criou o lendário som de caixa com gated snare sample, guitarras brilhantes e vocais cristalinos que definiram a produção dos anos 90.',
		albums: [
			{
				id: 'dt_images_and_words',
				albumTitle: 'Images and Words',
				band: 'Dream Theater',
				year: 1992,
				hardwareChain:
					'Mesa Boogie Quad Preamp, Marshall 1960 Cabs, Ludwig & Tama Snare with Dynacord Trigger, Lexicon 480L, SSL 4000E Console, Studer A800, Mastered by George Marino',
				soundSignature:
					'O álbum que definiu o som do metal progressivo mundial. Caixa com estalo e gated reverb icônico, voz de James LaBrie com alcance inacreditável e guitarras rítmicas estéreo abertas.',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'E Standard (440Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 115,
					midScoopHz: 750,
					midScoopGainDb: -2.8,
					bitePresenceHz: 3400,
					biteGainDb: 3.6,
					cabHighCutHz: 6900,
					distortionGain: 0.65,
					stereoSpread: 1.4,
					description:
						'O lendário timbre do Mesa Quad Preamp com TriAxis e chorus estéreo TC Electronic nos arpejos.',
				},
				eq10Band: {
					hz30: 1.2,
					hz60: 2.6,
					hz120: 1.0,
					hz250: -1.2,
					hz500: -2.0,
					hz1000: 0.6,
					hz2500: 2.8,
					hz4000: 3.4,
					hz8000: 2.8,
					hz16000: 2.0,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.38,
				},
				compressor: {
					threshold: -18.5,
					ratio: 3.2,
					attack: 28.0,
					release: 130.0,
					knee: 2.8,
				},
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 0.8,
						eq: { sub: 2.8, punch: 2.4, attack: 4.2, air: 2.8 },
						saturation: 'ssl_vca',
						drive: 0.32,
						compRatio: 4.0,
						compAttack: 22,
						compRelease: 110,
						description:
							'A icônica caixa com gated sample e bumbo veloz de Mike Portnoy em Pull Me Under e Metropolis.',
					},
					bass: {
						volumeDb: -0.6,
						eq: { subBass: 2.6, grit: 1.8, cutMids: -2.2, clarity: 2.5 },
						saturation: 'ampeg_svt',
						drive: 0.32,
						compRatio: 4.0,
						compAttack: 16,
						compRelease: 130,
						description:
							'Baixo Tobias e Tung de John Myung com slap limpo e tapping em Metropolis Pt. 1.',
					},
					guitars: {
						volumeDb: 0.8,
						eq: { lowCut: 85, body: 1.8, bite: 3.2, sheen: 2.6 },
						saturation: 'mesa_rectifier',
						drive: 0.58,
						stereoWidth: 1.42,
						description:
							'Ibanez Universe e Custom com chorus estéreo 2290 e solos cortantes em Under a Glass Moon.',
					},
					vocals: {
						volumeDb: 1.4,
						eq: { body: 1.4, clarity: 3.0, presence: 3.6, air: 3.0 },
						saturation: 'la2a_opto',
						drive: 0.25,
						compRatio: 2.8,
						compAttack: 25,
						compRelease: 190,
						description:
							'James LaBrie atingindo notas agudas inacreditáveis (F#5 em Learning to Live) com brilho cristalino.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 0.8, presence: 2.0, air: 2.6 },
						saturation: 'pultec_tube',
						drive: 0.22,
						stereoWidth: 1.44,
						description:
							'Kevin Moore com piano acústico majestoso e solos de sintetizador melódicos em Surrounded.',
					},
				},
			},
		],
	},
	{
		id: 'producer_kevin_shirley',
		name: 'Kevin Shirley "Caveman"',
		title: 'The Raw Power Giant',
		category: 'metal_rock',
		era: '1997–2024',
		country: 'South Africa / USA',
		bio: 'Produtor lendário de Iron Maiden, Led Zeppelin (DVDs/Remasters), Rush (Counterparts), Journey, Joe Bonamassa e Dream Theater (Falling into Infinity e mix de Train of Thought). Famoso por capturar a energia crua e o ar físico dos instrumentos sem artificialismos digitais.',
		albums: [
			{
				id: 'dt_falling_into_infinity',
				albumTitle: 'Falling into Infinity',
				band: 'Dream Theater',
				year: 1997,
				hardwareChain:
					'Avatar Studios NYC, Neve 8078 Console, Mesa Boogie TriAxis & Dual Rectifier, Tama Starclassic, Studer A800, Pultec EQP-1A, LA-2A, Fairchild 670',
				soundSignature:
					'Produção orgânica, quente e dinâmica com a mão de Kevin Shirley. Baixo com corpo analógico gigante (Peruvian Skies e Lines in the Sand) e solos de guitarra com calor valvulado.',
				targetLufs: -13.5,
				tuningSignature: {
					standardName: 'E Standard (440Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 110,
					midScoopHz: 650,
					midScoopGainDb: -1.5,
					bitePresenceHz: 3300,
					biteGainDb: 2.8,
					cabHighCutHz: 6700,
					distortionGain: 0.62,
					stereoSpread: 1.35,
					description:
						'Timbre analógico de TriAxis/Mesa com calor de console Neve e saturação suave de fita.',
				},
				eq10Band: {
					hz30: 1.5,
					hz60: 2.8,
					hz120: 1.4,
					hz250: -0.5,
					hz500: -1.0,
					hz1000: 0.8,
					hz2500: 2.2,
					hz4000: 2.8,
					hz8000: 2.2,
					hz16000: 1.8,
				},
				saturation: {
					type: 'neve_tube',
					drive: 0.44,
				},
				compressor: {
					threshold: -18.0,
					ratio: 3.4,
					attack: 24.0,
					release: 120.0,
					knee: 3.2,
				},
				stereoWidth: 1.35,
				gemSetup: {
					drums: {
						volumeDb: 0.6,
						eq: { sub: 3.0, punch: 2.5, attack: 3.5, air: 2.0 },
						saturation: 'ssl_vca',
						drive: 0.35,
						compRatio: 3.8,
						compAttack: 22,
						compRelease: 105,
						description:
							'Mike Portnoy com som de bateria acústica real e natural sem triggers digitais.',
					},
					bass: {
						volumeDb: 0.2,
						eq: { subBass: 3.2, grit: 2.2, cutMids: -1.2, clarity: 2.6 },
						saturation: 'ampeg_svt',
						drive: 0.38,
						compRatio: 4.2,
						compAttack: 16,
						compRelease: 120,
						description:
							'John Myung com o som de baixo mais quente e encorpado da discografia (Lines in the Sand).',
					},
					guitars: {
						volumeDb: 0.8,
						eq: { lowCut: 80, body: 2.2, bite: 2.8, sheen: 2.2 },
						saturation: 'neve_tube',
						drive: 0.55,
						stereoWidth: 1.36,
						description:
							'Petrucci com guitarras expressivas e solo arrebatador com Doug Pinnick nos vocais de apoio.',
					},
					vocals: {
						volumeDb: 1.2,
						eq: { body: 1.8, clarity: 2.6, presence: 3.0, air: 2.4 },
						saturation: 'la2a_opto',
						drive: 0.28,
						compRatio: 2.9,
						compAttack: 24,
						compRelease: 175,
						description: 'James LaBrie com presença calorosa e dinâmica aberta.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.0, presence: 2.2, air: 2.6 },
						saturation: 'pultec_tube',
						drive: 0.24,
						stereoWidth: 1.42,
						description:
							'Derek Sherinian com solos de teclado distorcidos e órgão Hammond B3 visceral.',
					},
				},
			},
		],
	},
	{
		id: 'producer_john_purdell_duane_baron',
		name: 'John Purdell & Duane Baron',
		title: 'The Dark Masterminds',
		category: 'prog_synth',
		era: '1994',
		country: 'USA',
		bio: 'A famosa dupla de produtores e engenheiros por trás de "Awake" do Dream Theater e do multiplatinado "No More Tears" de Ozzy Osbourne. Criaram a estética sombria, guitarras de 7 cordas densas e ambiências profundas que tornaram "Awake" um disco cult.',
		albums: [
			{
				id: 'dt_awake',
				albumTitle: 'Awake',
				band: 'Dream Theater',
				year: 1994,
				hardwareChain:
					'One On One Studios LA, Neve Console, Mesa Boogie Dual Rectifier & Mark IIC+, Ibanez UV77 7-String, Tama Starclassic, Studer A800, Eventide H3000, Lexicon 480L',
				soundSignature:
					'Estética escura, gótica e agressiva. Estreia oficial das guitarras de 7 cordas (The Mirror e Lie), caixa profunda e cavernosa e vocal encorpado.',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'B Standard (7-string) / E Standard',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 61.7,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 98,
					midScoopHz: 680,
					midScoopGainDb: -2.2,
					bitePresenceHz: 3600,
					biteGainDb: 3.4,
					cabHighCutHz: 6800,
					distortionGain: 0.72,
					stereoSpread: 1.38,
					description:
						'O timbre sombrio de 7 cordas de The Mirror: peso colossal nos graves e médios encorpados.',
				},
				eq10Band: {
					hz30: 1.8,
					hz60: 3.0,
					hz120: 1.6,
					hz250: -0.6,
					hz500: -1.4,
					hz1000: 0.8,
					hz2500: 2.6,
					hz4000: 3.2,
					hz8000: 2.4,
					hz16000: 1.9,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.46,
				},
				compressor: {
					threshold: -17.5,
					ratio: 3.6,
					attack: 22.0,
					release: 115.0,
					knee: 3.2,
				},
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0.8,
						eq: { sub: 3.2, punch: 2.6, attack: 3.8, air: 2.2 },
						saturation: 'ssl_vca',
						drive: 0.36,
						compRatio: 4.2,
						compAttack: 20,
						compRelease: 95,
						description:
							'Mike Portnoy com som de caixa profunda e esteira solta gravada no lendário One On One Studios.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.0, grit: 2.4, cutMids: -1.6, clarity: 2.8 },
						saturation: 'ampeg_svt',
						drive: 0.4,
						compRatio: 4.5,
						compAttack: 14,
						compRelease: 110,
						description:
							'John Myung com baixo 6 cordas casando com as afinações pesadas de 7 cordas.',
					},
					guitars: {
						volumeDb: 1.0,
						eq: { lowCut: 75, body: 2.4, bite: 3.4, sheen: 2.4 },
						saturation: 'mesa_rectifier',
						drive: 0.66,
						stereoWidth: 1.4,
						description:
							'Muralhas pesadas em The Mirror e solo magistral em Voices e The Silent Man.',
					},
					vocals: {
						volumeDb: 1.2,
						eq: { body: 1.9, clarity: 2.7, presence: 3.2, air: 2.4 },
						saturation: 'la2a_opto',
						drive: 0.28,
						compRatio: 3.1,
						compAttack: 22,
						compRelease: 165,
						description: 'James LaBrie com entrega emotiva, dramática e presença de estúdio densa.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.2, presence: 2.2, air: 2.8 },
						saturation: 'pultec_tube',
						drive: 0.26,
						stereoWidth: 1.45,
						description:
							'Kevin Moore em seu último álbum: texturas misteriosas em Space-Dye Vest e 6:00.',
					},
				},
			},
		],
	},
	{
		id: 'producer_john_petrucci_solo_era',
		name: 'John Petrucci (Solo Production Era)',
		title: 'The Modern Progressive Titan',
		category: 'prog_synth',
		era: '2011–2024',
		country: 'USA',
		bio: 'Assumiu o controle total de produção a partir de 2011 (A Dramatic Turn of Events, Dream Theater 2013, The Astonishing, Distance over Time e A View from the Top of the World — vencedor do GRAMMY). Trabalhou ao lado de mestres como Andy Wallace, Richard Chycki, Ben Grosse e Andy Sneap para alcançar a mais refinada tecnologia de áudio moderno.',
		albums: [
			{
				id: 'dt_dramatic_turn',
				albumTitle: 'A Dramatic Turn of Events',
				band: 'Dream Theater',
				year: 2011,
				hardwareChain:
					'Mesa Boogie Mark V & Lone Star, Pearl Reference Kit (Mike Mangini debut), Mixed by Andy Wallace (Nirvana/Slayer/Avenged Sevenfold), Mastered by Ted Jensen',
				soundSignature:
					'Mixagem lendingária de Andy Wallace: separação cristalina de cada instrumento no campo estéreo, bumbo estalado com subgrave cirúrgico e vocais de clareza absoluta.',
				targetLufs: -11.5,
				tuningSignature: {
					standardName: 'E Standard / 7-String A440',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 106,
					midScoopHz: 650,
					midScoopGainDb: -1.6,
					bitePresenceHz: 3800,
					biteGainDb: 3.6,
					cabHighCutHz: 7100,
					distortionGain: 0.72,
					stereoSpread: 1.42,
					description:
						'Timbre polido de Andy Wallace com clareza nos médios-altos e graves firmes em On the Backs of Angels.',
				},
				eq10Band: {
					hz30: 2.0,
					hz60: 3.2,
					hz120: 1.8,
					hz250: -0.6,
					hz500: -1.2,
					hz1000: 1.0,
					hz2500: 3.0,
					hz4000: 3.6,
					hz8000: 2.8,
					hz16000: 2.2,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.5,
				},
				compressor: {
					threshold: -16.5,
					ratio: 4.0,
					attack: 18.0,
					release: 90.0,
					knee: 3.5,
				},
				stereoWidth: 1.42,
				gemSetup: {
					drums: {
						volumeDb: 0.9,
						eq: { sub: 3.5, punch: 3.0, attack: 4.2, air: 2.4 },
						saturation: 'ssl_vca',
						drive: 0.4,
						compRatio: 4.8,
						compAttack: 16,
						compRelease: 85,
						description:
							'Mix de Andy Wallace com transientes percussivos super-velozes de Mike Mangini.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.1, grit: 2.6, cutMids: -1.5, clarity: 3.0 },
						saturation: 'ampeg_svt',
						drive: 0.42,
						compRatio: 5.0,
						compAttack: 12,
						compRelease: 100,
						description: 'Baixo 6 cordas com frequências graves perfeitamente ancoradas.',
					},
					guitars: {
						volumeDb: 1.1,
						eq: { lowCut: 76, body: 2.3, bite: 3.6, sheen: 2.8 },
						saturation: 'mesa_rectifier',
						drive: 0.7,
						stereoWidth: 1.44,
						description:
							'Guitarras com corpo denso e solo indicado ao Grammy em On the Backs of Angels.',
					},
					vocals: {
						volumeDb: 1.0,
						eq: { body: 1.7, clarity: 2.8, presence: 3.4, air: 2.6 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.2,
						compAttack: 20,
						compRelease: 150,
						description: 'Vocal com a consagrada compressão SSL/LA-2A de Andy Wallace.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.0, presence: 2.4, air: 3.0 },
						saturation: 'pultec_tube',
						drive: 0.26,
						stereoWidth: 1.46,
						description: 'Arranjos épicos em Bridges in the Sky e Breaking All Illusions.',
					},
				},
			},
			{
				id: 'dt_distance_over_time',
				albumTitle: 'Distance over Time',
				band: 'Dream Theater',
				year: 2019,
				hardwareChain:
					'Yonderbarn Studios NY, Mesa Boogie JP-2C, Ernie Ball Majesty, Mixed by Ben Grosse (Depeche Mode/Disturbed), Mastered by Tom Baker',
				soundSignature:
					'Retorno a um som direto, orgânico e com peso demolidor. Bateria com ressonância acústica de sala viva, guitarras ultra-pesadas em Untethered Moon e Paralyzed.',
				targetLufs: -11.0,
				tuningSignature: {
					standardName: 'Drop D / Drop C / Standard',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 73.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 110,
					midScoopHz: 660,
					midScoopGainDb: -1.7,
					bitePresenceHz: 3900,
					biteGainDb: 3.7,
					cabHighCutHz: 7200,
					distortionGain: 0.78,
					stereoSpread: 1.44,
					description:
						'Timbre moderno da guitarra Majesty no JP-2C: graves focados e saturação rápida.',
				},
				eq10Band: {
					hz30: 2.1,
					hz60: 3.4,
					hz120: 1.9,
					hz250: -0.5,
					hz500: -1.3,
					hz1000: 1.0,
					hz2500: 3.1,
					hz4000: 3.7,
					hz8000: 2.7,
					hz16000: 2.2,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.54,
				},
				compressor: {
					threshold: -16.2,
					ratio: 4.1,
					attack: 17.0,
					release: 88.0,
					knee: 3.6,
				},
				stereoWidth: 1.44,
				gemSetup: {
					drums: {
						volumeDb: 1.0,
						eq: { sub: 3.6, punch: 3.1, attack: 4.2, air: 2.4 },
						saturation: 'ssl_vca',
						drive: 0.42,
						compRatio: 4.6,
						compAttack: 17,
						compRelease: 88,
						description:
							'Mike Mangini com a afinação de bateria mais elogiada de sua era no Dream Theater.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.2, grit: 2.7, cutMids: -1.6, clarity: 2.9 },
						saturation: 'darkglass_b7k',
						drive: 0.44,
						compRatio: 5.2,
						compAttack: 12,
						compRelease: 98,
						description: 'John Myung com ataque presente e corpo encorpado nos graves.',
					},
					guitars: {
						volumeDb: 1.2,
						eq: { lowCut: 76, body: 2.4, bite: 3.8, sheen: 2.7 },
						saturation: 'mesa_rectifier',
						drive: 0.74,
						stereoWidth: 1.45,
						description: 'Paredes densas de guitarra gravadas no retiro do Yonderbarn Studios.',
					},
					vocals: {
						volumeDb: 0.9,
						eq: { body: 1.8, clarity: 2.7, presence: 3.3, air: 2.4 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.3,
						compAttack: 20,
						compRelease: 155,
						description: 'James LaBrie com entrega direta e potente.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.0, presence: 2.3, air: 2.9 },
						saturation: 'pultec_tube',
						drive: 0.28,
						stereoWidth: 1.46,
						description: 'Jordan Rudess com timbres analógicos Moog e piano refinado.',
					},
				},
			},
			{
				id: 'dt_view_from_top_grammy',
				albumTitle: 'A View from the Top of the World (GRAMMY Winner)',
				band: 'Dream Theater',
				year: 2021,
				hardwareChain:
					'DTHQ Studios, Mesa Boogie JP-2C & 8-String Custom Ernie Ball, Mixed by Andy Sneap, Mastered by Ted Jensen',
				soundSignature:
					'Álbum vencedor do GRAMMY de Melhor Performance de Metal (The Alien). Bateria com velocidade ultra-humana, estreando guitarras de 8 cordas com definição e pressão absoluta.',
				targetLufs: -10.8,
				tuningSignature: {
					standardName: '8-String F# / 7-String B / 6-String E',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 46.2,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 115,
					midScoopHz: 700,
					midScoopGainDb: -2.0,
					bitePresenceHz: 4000,
					biteGainDb: 4.0,
					cabHighCutHz: 7400,
					distortionGain: 0.84,
					stereoSpread: 1.46,
					description:
						'O timbre vencedor do GRAMMY de The Alien: 8 cordas afinadas em F# com clareza inacreditável.',
				},
				eq10Band: {
					hz30: 2.4,
					hz60: 3.6,
					hz120: 2.1,
					hz250: -0.5,
					hz500: -1.3,
					hz1000: 1.2,
					hz2500: 3.3,
					hz4000: 3.9,
					hz8000: 2.9,
					hz16000: 2.4,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.56,
				},
				compressor: {
					threshold: -15.8,
					ratio: 4.3,
					attack: 15.0,
					release: 82.0,
					knee: 4.0,
				},
				stereoWidth: 1.46,
				gemSetup: {
					drums: {
						volumeDb: 1.1,
						eq: { sub: 3.9, punch: 3.3, attack: 4.5, air: 2.6 },
						saturation: 'ssl_vca',
						drive: 0.45,
						compRatio: 5.0,
						compAttack: 14,
						compRelease: 78,
						description:
							'Mike Mangini em performance vencedora do Grammy em The Alien com bumbo duplo supersônico.',
					},
					bass: {
						volumeDb: 0.1,
						eq: { subBass: 3.5, grit: 3.0, cutMids: -1.5, clarity: 3.2 },
						saturation: 'darkglass_b7k',
						drive: 0.5,
						compRatio: 5.5,
						compAttack: 10,
						compRelease: 88,
						description:
							'John Myung com Dingwall/Spector travado nas frequências graves de 8 cordas.',
					},
					guitars: {
						volumeDb: 1.3,
						eq: { lowCut: 72, body: 2.6, bite: 4.1, sheen: 2.9 },
						saturation: 'mesa_rectifier',
						drive: 0.78,
						stereoWidth: 1.48,
						description:
							'Mix de Andy Sneap com nitidez e peso inacreditável nas 8 cordas de Petrucci.',
					},
					vocals: {
						volumeDb: 0.9,
						eq: { body: 1.8, clarity: 2.8, presence: 3.5, air: 2.5 },
						saturation: 'la2a_opto',
						drive: 0.32,
						compRatio: 3.5,
						compAttack: 18,
						compRelease: 145,
						description:
							'Vocal direto e expressivo comandando a narrativa das suítes de 20 minutos.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.2, presence: 2.5, air: 3.2 },
						saturation: 'pultec_tube',
						drive: 0.3,
						stereoWidth: 1.5,
						description:
							'Jordan Rudess com sintetizadores imponentes e arranjos orquestrais futuristas.',
					},
				},
			},
		],
	},
]
