import type { MasterProducer } from './masters-database'

export const PRODUCERS_LEGENDS_ROCK_METAL: MasterProducer[] = [
	// ─── 1. EDDIE OFFORD (YES) ───
	{
		id: 'eddie_offord',
		name: 'EDDIE OFFORD',
		title: 'Architect of Progressive Rock Sound (Yes & ELP)',
		category: 'prog_synth',
		era: '1970 - 1985',
		country: 'United Kingdom 🇬🇧',
		bio: 'Pioneered the crystal-clear, dynamic multi-layered sonic architecture of progressive rock with Yes and Emerson Lake & Palmer at Advision Studios.',
		albums: [
			{
				id: 'yes_fragile',
				albumTitle: 'Fragile (1971)',
				band: 'Yes',
				year: 1971,
				hardwareChain:
					'Advision Custom 24-Channel Desk -> 3M 16-Track Tape -> Dolby A301 -> EMT 140 Plate',
				soundSignature:
					'Pristine acoustic shimmer, Chris Squire trebly Rickenbacker 4001 bass punch, and Steve Howe intricate classical-rock guitar separation.',
				targetLufs: -14.0,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 115,
					midScoopHz: 650,
					midScoopGainDb: -1.2,
					bitePresenceHz: 3600,
					biteGainDb: 3.2,
					cabHighCutHz: 8200,
					distortionGain: 0.35,
					stereoSpread: 1.35,
					description: 'Steve Howe Gibson ES-175 / Dual Showman sparkling high-definition bite.',
				},
				eq10Band: {
					hz30: 0.5,
					hz60: 2.2,
					hz120: 1.8,
					hz250: -1.0,
					hz500: 0.5,
					hz1000: 1.5,
					hz2500: 2.6,
					hz4000: 2.8,
					hz8000: 3.5,
					hz16000: 4.0,
				},
				saturation: { type: 'tape_warmth', drive: 0.28 },
				compressor: { threshold: -14, ratio: 1.8, attack: 45, release: 120, knee: 4 },
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0,
						eq: { sub: 2.0, punch: 2.5, attack: 3.0, air: 3.5 },
						saturation: 'tape_warmth',
						drive: 0.25,
						compRatio: 2.0,
						compAttack: 35,
						compRelease: 100,
						description: 'Bill Bruford jazz-rock articulate snare & crisp cymbals.',
					},
					bass: {
						volumeDb: 1.2,
						eq: { subBass: 2.5, grit: 3.5, cutMids: -1.0, clarity: 4.0 },
						saturation: 'marshall_jcm800',
						drive: 0.4,
						compRatio: 2.5,
						compAttack: 25,
						compRelease: 80,
						description: 'Chris Squire Rickenbacker 4001 clank & growl.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 100, body: 1.5, bite: 3.0, sheen: 3.5 },
						saturation: 'tape_warmth',
						drive: 0.3,
						stereoWidth: 1.4,
						description: 'Dual acoustic-electric sparkling harmonics.',
					},
					vocals: {
						volumeDb: 0.5,
						eq: { body: 1.0, clarity: 2.5, presence: 3.0, air: 3.8 },
						saturation: 'neve_tube',
						drive: 0.2,
						compRatio: 2.0,
						compAttack: 30,
						compRelease: 110,
						description: 'Jon Anderson crystalline tenor vocal clarity.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 1.0, presence: 2.0, air: 3.0 },
						saturation: 'tape_warmth',
						drive: 0.22,
						stereoWidth: 1.45,
						description: 'Rick Wakeman Mellotron and Minimoog analog width.',
					},
				},
			},
			{
				id: 'yes_close_to_the_edge',
				albumTitle: 'Close to the Edge (1972)',
				band: 'Yes',
				year: 1972,
				hardwareChain:
					'Advision 16-Track Ampex MM1000 -> Studer A80 -> Pultec EQP-1A -> Fairchild 660',
				soundSignature:
					'Massive symphonic prog dynamic range, cathedral pipe organ resonance, and lush layered vocal choirs.',
				targetLufs: -14.5,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'fender_twin' as any,
					cabResonanceHz: 120,
					midScoopHz: 700,
					midScoopGainDb: -1.0,
					bitePresenceHz: 4000,
					biteGainDb: 3.0,
					cabHighCutHz: 8500,
					distortionGain: 0.32,
					stereoSpread: 1.4,
					description: 'Sitar guitar and Spanish acoustic picking brilliance.',
				},
				eq10Band: {
					hz30: 1.2,
					hz60: 2.5,
					hz120: 1.5,
					hz250: -0.8,
					hz500: 0.8,
					hz1000: 1.2,
					hz2500: 2.2,
					hz4000: 2.8,
					hz8000: 3.2,
					hz16000: 3.8,
				},
				saturation: { type: 'pultec_tube', drive: 0.25 },
				compressor: { threshold: -15, ratio: 1.6, attack: 50, release: 140, knee: 5 },
				stereoWidth: 1.42,
				gemSetup: {
					drums: {
						volumeDb: 0,
						eq: { sub: 2.2, punch: 2.0, attack: 2.8, air: 3.2 },
						saturation: 'tape_warmth',
						drive: 0.22,
						compRatio: 1.8,
						compAttack: 40,
						compRelease: 120,
						description: 'Organic room acoustics with deep floor toms.',
					},
					bass: {
						volumeDb: 1.0,
						eq: { subBass: 3.0, grit: 2.8, cutMids: -0.5, clarity: 3.5 },
						saturation: 'ampeg_svt',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 30,
						compRelease: 90,
						description: 'Thunderous, articulate low-end backbone.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 90, body: 1.8, bite: 2.5, sheen: 3.2 },
						saturation: 'tape_warmth',
						drive: 0.28,
						stereoWidth: 1.38,
						description: 'Lush 12-string acoustic and electric cross-weaving.',
					},
					vocals: {
						volumeDb: 0.8,
						eq: { body: 1.2, clarity: 2.2, presence: 2.8, air: 3.5 },
						saturation: 'la2a_opto',
						drive: 0.2,
						compRatio: 1.9,
						compAttack: 35,
						compRelease: 120,
						description: 'Complex 4-part contrapuntal vocal harmonies.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.5, presence: 2.5, air: 3.2 },
						saturation: 'pultec_tube',
						drive: 0.25,
						stereoWidth: 1.5,
						description: 'Church organ acoustic reverbs and Moog leads.',
					},
				},
			},
		],
	},

	// ─── 2. TERRY BROWN (RUSH) ───
	{
		id: 'terry_brown',
		name: 'TERRY BROWN ("Broon")',
		title: 'The Legendary Rush Sonic Mastermind (1974 - 1982)',
		category: 'metal_rock',
		era: '1974 - 1985',
		country: 'Canada / UK 🇨🇦🇬🇧',
		bio: 'Engineered and produced Rush’s golden catalog (2112, Moving Pictures, Hemispheres) delivering the world’s most articulate hard-rock power-trio sound.',
		albums: [
			{
				id: 'rush_moving_pictures',
				albumTitle: 'Moving Pictures (1981)',
				band: 'Rush',
				year: 1981,
				hardwareChain:
					'Le Studio Morin-Heights SSL 4000B -> Studer A800 24-Track -> Lexicon 224 -> EMT 250',
				soundSignature:
					'The benchmark of rock production: Neil Peart’s punchy articulate drum kit, Geddy Lee’s punchy Wal/Rickenbacker bass, and Alex Lifeson’s chorused Marshall roar.',
				targetLufs: -13.5,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 110,
					midScoopHz: 600,
					midScoopGainDb: -0.8,
					bitePresenceHz: 3200,
					biteGainDb: 2.8,
					cabHighCutHz: 8000,
					distortionGain: 0.55,
					stereoSpread: 1.32,
					description: 'Alex Lifeson Marshall Club & Country with Roland CE-1 stereo chorus.',
				},
				eq10Band: {
					hz30: 1.0,
					hz60: 2.6,
					hz120: 2.0,
					hz250: -1.2,
					hz500: 0.8,
					hz1000: 1.4,
					hz2500: 2.5,
					hz4000: 3.0,
					hz8000: 3.4,
					hz16000: 3.8,
				},
				saturation: { type: 'ssl_vca', drive: 0.35 },
				compressor: { threshold: -13, ratio: 2.0, attack: 35, release: 90, knee: 3 },
				stereoWidth: 1.34,
				gemSetup: {
					drums: {
						volumeDb: 0.5,
						eq: { sub: 2.5, punch: 3.2, attack: 3.5, air: 3.8 },
						saturation: 'ssl_vca',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 30,
						compRelease: 80,
						description: 'Neil Peart Tama Superstar drum kit with crisp Slingerland snare.',
					},
					bass: {
						volumeDb: 1.0,
						eq: { subBass: 2.8, grit: 3.2, cutMids: -0.8, clarity: 3.6 },
						saturation: 'sansamp_di',
						drive: 0.42,
						compRatio: 2.4,
						compAttack: 25,
						compRelease: 85,
						description: 'Geddy Lee Rickenbacker 4001 / Fender Jazz punch and grit.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 95, body: 2.0, bite: 2.8, sheen: 3.2 },
						saturation: 'marshall_jcm800',
						drive: 0.48,
						stereoWidth: 1.36,
						description: 'Lush chorused heavy rock stereo wall.',
					},
					vocals: {
						volumeDb: 0.4,
						eq: { body: 1.2, clarity: 2.6, presence: 3.0, air: 3.5 },
						saturation: 'neve_tube',
						drive: 0.22,
						compRatio: 2.1,
						compAttack: 28,
						compRelease: 100,
						description: 'Geddy Lee high-register tenor vocal projection.',
					},
					synthsFx: {
						volumeDb: 0.3,
						eq: { lowMids: 1.8, presence: 2.2, air: 3.0 },
						saturation: 'tape_warmth',
						drive: 0.25,
						stereoWidth: 1.4,
						description: 'Oberheim OB-X and Moog Taurus bass synthesizer pedals.',
					},
				},
			},
			{
				id: 'rush_2112',
				albumTitle: '2112 (1976)',
				band: 'Rush',
				year: 1976,
				hardwareChain:
					'Toronto Sound Studios Trident A-Range -> Studer 2-Inch -> Teletronix LA-2A -> Marshall 1959 Plexi',
				soundSignature:
					'Raw, visceral hard-rock epic with screaming Marshall power chords, explosive drumming, and futuristic acoustic passages.',
				targetLufs: -13.8,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 105,
					midScoopHz: 550,
					midScoopGainDb: -0.5,
					bitePresenceHz: 2800,
					biteGainDb: 3.5,
					cabHighCutHz: 7800,
					distortionGain: 0.65,
					stereoSpread: 1.28,
					description: 'Gibson ES-335 through dimed Marshall Super Lead Plexi.',
				},
				eq10Band: {
					hz30: 0.8,
					hz60: 2.4,
					hz120: 2.2,
					hz250: -0.8,
					hz500: 1.0,
					hz1000: 1.6,
					hz2500: 2.8,
					hz4000: 3.2,
					hz8000: 3.0,
					hz16000: 3.2,
				},
				saturation: { type: 'tape_warmth', drive: 0.42 },
				compressor: { threshold: -14, ratio: 2.2, attack: 30, release: 95, knee: 3 },
				stereoWidth: 1.3,
				gemSetup: {
					drums: {
						volumeDb: 0.3,
						eq: { sub: 2.0, punch: 2.8, attack: 3.2, air: 3.0 },
						saturation: 'tape_warmth',
						drive: 0.3,
						compRatio: 2.0,
						compAttack: 35,
						compRelease: 90,
						description: 'Aggressive 1970s concert toms and crisp Zildjian hi-hats.',
					},
					bass: {
						volumeDb: 0.8,
						eq: { subBass: 2.6, grit: 3.0, cutMids: -0.5, clarity: 3.2 },
						saturation: 'ampeg_svt',
						drive: 0.4,
						compRatio: 2.3,
						compAttack: 25,
						compRelease: 80,
						description: 'Rickenbacker through Sunn Colosseum and Ampeg SVT.',
					},
					guitars: {
						volumeDb: 0.2,
						eq: { lowCut: 90, body: 2.2, bite: 3.2, sheen: 2.8 },
						saturation: 'marshall_jcm800',
						drive: 0.58,
						stereoWidth: 1.32,
						description: 'Roaring overdriven 70s British tube stacks.',
					},
					vocals: {
						volumeDb: 0.5,
						eq: { body: 1.0, clarity: 2.8, presence: 3.4, air: 3.2 },
						saturation: 'la2a_opto',
						drive: 0.28,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 90,
						description: 'Screaming operatic hard-rock banshee highs.',
					},
					synthsFx: {
						volumeDb: 0.1,
						eq: { lowMids: 1.2, presence: 1.8, air: 2.5 },
						saturation: 'tape_warmth',
						drive: 0.2,
						stereoWidth: 1.35,
						description: 'Vintage Minimoog sci-fi lasers and filter sweeps.',
					},
				},
			},
		],
	},

	// ─── 3. TOMMY HANSEN & CHARLIE BAUERFEIND (HELLOWEEN & ANGRA) ───
	{
		id: 'tommy_hansen_bauerfeind',
		name: 'TOMMY HANSEN & CHARLIE BAUERFEIND',
		title: 'Kings of European Power Metal & Progressive Elegance',
		category: 'metal_rock',
		era: '1987 - Present',
		country: 'Germany / Denmark 🇩🇪🇩🇰',
		bio: 'Pioneered the European Power Metal sound with Helloween (Keeper of the Seven Keys), Angra (Angels Cry, Holy Land), and Blind Guardian.',
		albums: [
			{
				id: 'helloween_keeper_2',
				albumTitle: 'Keeper of the Seven Keys Part II (1988)',
				band: 'Helloween',
				year: 1988,
				hardwareChain:
					'Horus Sound Hannover Soundcraft TS24 -> Otari MTR90 -> EMT 140 -> Pultec EQP-1A',
				soundSignature:
					'The undisputed power metal gold standard: lightning twin guitar harmonies, double-bass thunder, and Michael Kiske’s soaring 4-octave vocals.',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 112,
					midScoopHz: 650,
					midScoopGainDb: -1.0,
					bitePresenceHz: 3400,
					biteGainDb: 3.0,
					cabHighCutHz: 8200,
					distortionGain: 0.62,
					stereoSpread: 1.38,
					description:
						'Michael Weikath & Kai Hansen Gibson Flying V / Marshall JCM800 dual harmonizer.',
				},
				eq10Band: {
					hz30: 1.0,
					hz60: 2.5,
					hz120: 2.0,
					hz250: -1.0,
					hz500: 0.6,
					hz1000: 1.2,
					hz2500: 2.4,
					hz4000: 2.8,
					hz8000: 3.2,
					hz16000: 3.6,
				},
				saturation: { type: 'marshall_jcm800', drive: 0.4 },
				compressor: { threshold: -13, ratio: 2.0, attack: 35, release: 90, knee: 3 },
				stereoWidth: 1.36,
				gemSetup: {
					drums: {
						volumeDb: 0.4,
						eq: { sub: 2.6, punch: 3.0, attack: 3.2, air: 3.4 },
						saturation: 'ssl_vca',
						drive: 0.32,
						compRatio: 2.2,
						compAttack: 30,
						compRelease: 80,
						description: 'Ingo Schwichtenberg lightning double-bass punch.',
					},
					bass: {
						volumeDb: 0.8,
						eq: { subBass: 2.8, grit: 2.8, cutMids: -0.8, clarity: 3.2 },
						saturation: 'ampeg_svt',
						drive: 0.38,
						compRatio: 2.4,
						compAttack: 25,
						compRelease: 85,
						description: 'Markus Grosskopf precision galloping power bass.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 95, body: 1.8, bite: 2.8, sheen: 3.2 },
						saturation: 'marshall_jcm800',
						drive: 0.52,
						stereoWidth: 1.4,
						description: 'Lush stereo harmonized twin-lead guitars.',
					},
					vocals: {
						volumeDb: 0.6,
						eq: { body: 1.0, clarity: 2.5, presence: 3.2, air: 3.8 },
						saturation: 'neve_tube',
						drive: 0.22,
						compRatio: 2.0,
						compAttack: 25,
						compRelease: 95,
						description: 'Michael Kiske operatic golden high-E vibrato.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 1.2, presence: 2.0, air: 2.8 },
						saturation: 'tape_warmth',
						drive: 0.2,
						stereoWidth: 1.42,
						description: 'Epic brass and chime orchestral accents.',
					},
				},
			},
			{
				id: 'angra_holy_land',
				albumTitle: 'Holy Land (1996)',
				band: 'Angra',
				year: 1996,
				hardwareChain: 'Horus Sound & D.O.C. Studios -> SSL 4000G+ -> Lexicon 480L -> Studer A827',
				soundSignature:
					'Groundbreaking fusion of classical music, Brazilian indigenous percussion (Berimbau, Zabumba, Maracatu), and virtuosic progressive metal.',
				targetLufs: -13.2,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'soldano_slo100',
					cabResonanceHz: 110,
					midScoopHz: 600,
					midScoopGainDb: -0.8,
					bitePresenceHz: 3500,
					biteGainDb: 2.8,
					cabHighCutHz: 8400,
					distortionGain: 0.58,
					stereoSpread: 1.36,
					description:
						'Kiko Loureiro & Rafael Bittencourt Tagima / Soldano SLO-100 classical shred.',
				},
				eq10Band: {
					hz30: 1.2,
					hz60: 2.4,
					hz120: 1.8,
					hz250: -0.8,
					hz500: 0.8,
					hz1000: 1.4,
					hz2500: 2.2,
					hz4000: 2.6,
					hz8000: 3.2,
					hz16000: 3.8,
				},
				saturation: { type: 'soldano_slo100', drive: 0.36 },
				compressor: { threshold: -13, ratio: 1.9, attack: 40, release: 100, knee: 3 },
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0.4,
						eq: { sub: 2.4, punch: 2.8, attack: 3.2, air: 3.5 },
						saturation: 'ssl_vca',
						drive: 0.3,
						compRatio: 2.0,
						compAttack: 35,
						compRelease: 90,
						description: 'Ricardo Confessori acoustic kit + Brazilian organic percussion.',
					},
					bass: {
						volumeDb: 0.8,
						eq: { subBass: 2.6, grit: 2.5, cutMids: -0.6, clarity: 3.0 },
						saturation: 'sansamp_di',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 80,
						description: 'Luis Mariutti deep, warm, dynamic fingerstyle bass.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 90, body: 1.8, bite: 2.6, sheen: 3.4 },
						saturation: 'soldano_slo100',
						drive: 0.48,
						stereoWidth: 1.4,
						description: 'Classical nylon acoustic blended with heavy high-gain leads.',
					},
					vocals: {
						volumeDb: 0.5,
						eq: { body: 1.2, clarity: 2.4, presence: 3.0, air: 3.6 },
						saturation: 'la2a_opto',
						drive: 0.2,
						compRatio: 2.0,
						compAttack: 30,
						compRelease: 100,
						description: 'Andre Matos emotive, dynamic, classical tenor voice.',
					},
					synthsFx: {
						volumeDb: 0.3,
						eq: { lowMids: 1.5, presence: 2.2, air: 3.2 },
						saturation: 'tape_warmth',
						drive: 0.22,
						stereoWidth: 1.45,
						description: 'Renaissance flutes, harpsichords, and choir textures.',
					},
				},
			},
		],
	},

	// ─── 4. TOM ALLOM (JUDAS PRIEST) ───
	{
		id: 'tom_allom',
		name: 'TOM ALLOM ("The Colonel")',
		title: 'Architect of Pure British Heavy Metal (Judas Priest, Black Sabbath, Def Leppard)',
		category: 'metal_rock',
		era: '1979 - Present',
		country: 'United Kingdom 🇬🇧',
		bio: 'Produced Judas Priest’s most defining albums (British Steel, Screaming for Vengeance, Defenders of the Faith), establishing the cutting, punchy blueprint of Heavy Metal.',
		albums: [
			{
				id: 'priest_screaming_for_vengeance',
				albumTitle: 'Screaming for Vengeance (1982)',
				band: 'Judas Priest',
				year: 1982,
				hardwareChain:
					'Ibiza Sound Studios SSL 4000E -> Studer A80 -> DBX 160 -> Marshall JCM800 2203',
				soundSignature:
					'Razor-sharp dual Marshall guitars (Tipton & Downing), Dave Holland punchy drums, and Rob Halford’s glass-shattering vocal range.',
				targetLufs: -12.8,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 115,
					midScoopHz: 750,
					midScoopGainDb: -1.5,
					bitePresenceHz: 3500,
					biteGainDb: 3.5,
					cabHighCutHz: 8000,
					distortionGain: 0.65,
					stereoSpread: 1.35,
					description: 'Glenn Tipton & K.K. Downing Marshall JCM800 razor bite.',
				},
				eq10Band: {
					hz30: 0.8,
					hz60: 2.2,
					hz120: 2.0,
					hz250: -1.2,
					hz500: 0.5,
					hz1000: 1.5,
					hz2500: 2.8,
					hz4000: 3.2,
					hz8000: 3.5,
					hz16000: 3.5,
				},
				saturation: { type: 'marshall_jcm800', drive: 0.45 },
				compressor: { threshold: -12, ratio: 2.2, attack: 30, release: 85, knee: 3 },
				stereoWidth: 1.35,
				gemSetup: {
					drums: {
						volumeDb: 0.3,
						eq: { sub: 2.2, punch: 2.8, attack: 3.4, air: 3.2 },
						saturation: 'ssl_vca',
						drive: 0.35,
						compRatio: 2.4,
						compAttack: 25,
						compRelease: 75,
						description: 'Tight, punchy British metal snare and crisp crash cymbals.',
					},
					bass: {
						volumeDb: 0.7,
						eq: { subBass: 2.5, grit: 2.8, cutMids: -0.8, clarity: 3.0 },
						saturation: 'ampeg_svt',
						drive: 0.35,
						compRatio: 2.3,
						compAttack: 25,
						compRelease: 80,
						description: 'Ian Hill rock-solid anchor bass line.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 100, body: 1.8, bite: 3.2, sheen: 3.0 },
						saturation: 'marshall_jcm800',
						drive: 0.55,
						stereoWidth: 1.38,
						description: 'Iconic hard-panned dual Marshall metal assault.',
					},
					vocals: {
						volumeDb: 0.5,
						eq: { body: 1.0, clarity: 2.6, presence: 3.5, air: 3.8 },
						saturation: 'neve_tube',
						drive: 0.25,
						compRatio: 2.2,
						compAttack: 20,
						compRelease: 85,
						description: 'Rob Halford Metal God piercing high scream clarity.',
					},
					synthsFx: {
						volumeDb: 0,
						eq: { lowMids: 0.8, presence: 1.5, air: 2.2 },
						saturation: 'tape_warmth',
						drive: 0.18,
						stereoWidth: 1.3,
						description: 'Subtle analog FX and intro transitions.',
					},
				},
			},
			{
				id: 'priest_british_steel',
				albumTitle: 'British Steel (1980)',
				band: 'Judas Priest',
				year: 1980,
				hardwareChain:
					'Startling Studios (Tittenhurst Park) Helios Console -> 3M M79 Tape -> Urei 1176',
				soundSignature:
					'Direct, dry, anthemic heavy metal punch: "Breaking the Law" and "Living After Midnight" raw energy.',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 110,
					midScoopHz: 700,
					midScoopGainDb: -1.0,
					bitePresenceHz: 3200,
					biteGainDb: 3.0,
					cabHighCutHz: 7800,
					distortionGain: 0.55,
					stereoSpread: 1.3,
					description: 'Marshall JMP 50W master volume crunch.',
				},
				eq10Band: {
					hz30: 0.6,
					hz60: 2.0,
					hz120: 2.2,
					hz250: -1.0,
					hz500: 0.8,
					hz1000: 1.6,
					hz2500: 2.6,
					hz4000: 3.0,
					hz8000: 3.0,
					hz16000: 3.0,
				},
				saturation: { type: 'tape_warmth', drive: 0.38 },
				compressor: { threshold: -13, ratio: 2.0, attack: 35, release: 90, knee: 3 },
				stereoWidth: 1.3,
				gemSetup: {
					drums: {
						volumeDb: 0.2,
						eq: { sub: 2.0, punch: 2.6, attack: 3.0, air: 2.8 },
						saturation: 'tape_warmth',
						drive: 0.3,
						compRatio: 2.2,
						compAttack: 30,
						compRelease: 80,
						description: 'Dry, direct, room-sound British heavy drums.',
					},
					bass: {
						volumeDb: 0.6,
						eq: { subBass: 2.4, grit: 2.6, cutMids: -0.6, clarity: 2.8 },
						saturation: 'ampeg_svt',
						drive: 0.32,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 80,
						description: 'Clean low-end groove anchor.',
					},
					guitars: {
						volumeDb: 0.1,
						eq: { lowCut: 95, body: 2.0, bite: 3.0, sheen: 2.6 },
						saturation: 'marshall_jcm800',
						drive: 0.5,
						stereoWidth: 1.32,
						description: 'Raw British overdrive with instant anthemic cut.',
					},
					vocals: {
						volumeDb: 0.4,
						eq: { body: 1.0, clarity: 2.4, presence: 3.2, air: 3.2 },
						saturation: 'neve_tube',
						drive: 0.22,
						compRatio: 2.0,
						compAttack: 25,
						compRelease: 90,
						description: 'Aggressive, commanding Rob Halford lead vocal.',
					},
					synthsFx: {
						volumeDb: 0,
						eq: { lowMids: 0.5, presence: 1.0, air: 1.8 },
						saturation: 'tape_warmth',
						drive: 0.15,
						stereoWidth: 1.25,
						description: 'Subtle sound effects and room ambiance.',
					},
				},
			},
		],
	},

	// ─── 5. STEVE VAI (STEVE VAI SOLO MASTERS) ───
	{
		id: 'steve_vai',
		name: 'STEVE VAI',
		title: 'The Master of Guitar Alchemy & 3D Harmonic Dimension',
		category: 'metal_rock',
		era: '1984 - Present',
		country: 'United States 🇺🇸',
		bio: 'Visionary guitarist and producer of Passion and Warfare and Alien Love Secrets. Pioneer of 7-string guitars, microtonal harmony, and ultra-high-definition audio mastering.',
		albums: [
			{
				id: 'vai_passion_and_warfare',
				albumTitle: 'Passion and Warfare (1990)',
				band: 'Steve Vai',
				year: 1990,
				hardwareChain:
					'The Mothership Studio Harrison 3232 -> Studer A800 24-Track -> Eventide H3000 -> Bogner / Carvin Amps',
				soundSignature:
					'The masterpiece of instrumental guitar: Eventide micro-pitch widening, 7-string sub-lows, expressive whammy textures, and "For the Love of God" emotional resonance.',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'Standard E / 7-String B (B-E-A-D-G-B-E)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 61.74,
				},
				guitarToneprint: {
					ampModel: 'soldano_slo100',
					cabResonanceHz: 118,
					midScoopHz: 680,
					midScoopGainDb: -0.8,
					bitePresenceHz: 3600,
					biteGainDb: 3.4,
					cabHighCutHz: 8600,
					distortionGain: 0.68,
					stereoSpread: 1.42,
					description:
						'Ibanez Universe 7-string through Carvin X100B, Bogner Ecstasy and Eventide H3000.',
				},
				eq10Band: {
					hz30: 1.2,
					hz60: 2.6,
					hz120: 2.2,
					hz250: -1.0,
					hz500: 0.8,
					hz1000: 1.5,
					hz2500: 2.8,
					hz4000: 3.4,
					hz8000: 3.8,
					hz16000: 4.2,
				},
				saturation: { type: 'soldano_slo100', drive: 0.45 },
				compressor: { threshold: -13, ratio: 2.1, attack: 35, release: 95, knee: 4 },
				stereoWidth: 1.45,
				gemSetup: {
					drums: {
						volumeDb: 0.3,
						eq: { sub: 2.5, punch: 3.0, attack: 3.5, air: 3.8 },
						saturation: 'ssl_vca',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 30,
						compRelease: 85,
						description: 'Punchy studio rock drums with massive gated stereo snares.',
					},
					bass: {
						volumeDb: 0.8,
						eq: { subBass: 3.0, grit: 2.8, cutMids: -0.8, clarity: 3.4 },
						saturation: 'sansamp_di',
						drive: 0.38,
						compRatio: 2.3,
						compAttack: 25,
						compRelease: 80,
						description: 'Deep 5-string bass supporting the 7-string guitar sub frequencies.',
					},
					guitars: {
						volumeDb: 0.5,
						eq: { lowCut: 80, body: 2.2, bite: 3.5, sheen: 4.0 },
						saturation: 'soldano_slo100',
						drive: 0.62,
						stereoWidth: 1.48,
						description: 'Multi-tracked Eventide pitch-shifted singing guitar sustain.',
					},
					vocals: {
						volumeDb: 0,
						eq: { body: 1.0, clarity: 2.0, presence: 2.5, air: 3.0 },
						saturation: 'neve_tube',
						drive: 0.2,
						compRatio: 1.8,
						compAttack: 30,
						compRelease: 100,
						description: 'Subtle spoken word and whisper textures.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.5, presence: 2.5, air: 3.8 },
						saturation: 'tape_warmth',
						drive: 0.28,
						stereoWidth: 1.5,
						description: 'Synclavier II, Kurzweil K250, and backward reverb sweeps.',
					},
				},
			},
		],
	},

	// ─── 6. JIMMY PAGE (LED ZEPPELIN) ───
	{
		id: 'jimmy_page',
		name: 'JIMMY PAGE & EDDIE KRAMER',
		title: 'The Alchemists of Monumental Heavy Rock & Ambient Distance (Led Zeppelin)',
		category: 'metal_rock',
		era: '1968 - 1980',
		country: 'United Kingdom 🇬🇧',
		bio: 'Engineered and produced the legendary Led Zeppelin sound with pioneering ambient room acoustics, John Bonham’s thunderous drums, and explosive Les Paul dynamics.',
		albums: [
			{
				id: 'led_zeppelin_iv',
				albumTitle: 'Led Zeppelin IV (1971)',
				band: 'Led Zeppelin',
				year: 1971,
				hardwareChain: 'Headley Grange Helios Mobile -> 3M 16-Track -> EMT 140 -> Binson Echorec',
				soundSignature:
					'The holy grail of rock production: John Bonham’s massive Headley Grange stairwell drums ("When the Levee Breaks"), roaring Marshall/Supro riffs, and acoustic mystical air ("Stairway to Heaven").',
				targetLufs: -13.5,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 110,
					midScoopHz: 600,
					midScoopGainDb: -0.6,
					bitePresenceHz: 3000,
					biteGainDb: 3.2,
					cabHighCutHz: 7800,
					distortionGain: 0.52,
					stereoSpread: 1.34,
					description: '1959 Gibson Les Paul Standard through Marshall SLP & Vox AC30.',
				},
				eq10Band: {
					hz30: 1.5,
					hz60: 3.0,
					hz120: 2.2,
					hz250: -0.8,
					hz500: 0.8,
					hz1000: 1.5,
					hz2500: 2.6,
					hz4000: 3.0,
					hz8000: 3.2,
					hz16000: 3.6,
				},
				saturation: { type: 'tape_warmth', drive: 0.45 },
				compressor: { threshold: -14, ratio: 2.2, attack: 35, release: 100, knee: 4 },
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0.8,
						eq: { sub: 3.5, punch: 3.5, attack: 3.2, air: 3.5 },
						saturation: 'tape_warmth',
						drive: 0.45,
						compRatio: 2.5,
						compAttack: 30,
						compRelease: 80,
						description: 'John Bonham 26-inch Ludwig Green Sparkle kick & deep room reverb.',
					},
					bass: {
						volumeDb: 0.8,
						eq: { subBass: 3.0, grit: 2.8, cutMids: -0.6, clarity: 3.0 },
						saturation: 'ampeg_svt',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 85,
						description: 'John Paul Jones Fender Jazz Bass warmth and precision.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 85, body: 2.2, bite: 3.0, sheen: 3.2 },
						saturation: 'marshall_jcm800',
						drive: 0.5,
						stereoWidth: 1.36,
						description: 'Jimmy Page layered acoustic 12-string and roaring electric stacks.',
					},
					vocals: {
						volumeDb: 0.5,
						eq: { body: 1.2, clarity: 2.4, presence: 3.0, air: 3.5 },
						saturation: 'la2a_opto',
						drive: 0.25,
						compRatio: 2.0,
						compAttack: 30,
						compRelease: 100,
						description: 'Robert Plant golden-age blues-rock wails and dynamic whisper.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 1.2, presence: 2.0, air: 3.0 },
						saturation: 'tape_warmth',
						drive: 0.22,
						stereoWidth: 1.4,
						description: 'Mellotron flutes, recorders, and ambient hall space.',
					},
				},
			},
			{
				id: 'led_zeppelin_ii',
				albumTitle: 'Led Zeppelin II (1969)',
				band: 'Led Zeppelin',
				year: 1969,
				hardwareChain:
					'A&R Studios NY Custom Desk -> Scully 8-Track -> Pultec EQP-1A -> Teletronix LA-2A',
				soundSignature:
					'Heavy, saturated, overdriven blues-metal explosion: "Whole Lotta Love" dynamic panning and tape phasing.',
				targetLufs: -13.2,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 105,
					midScoopHz: 550,
					midScoopGainDb: -0.5,
					bitePresenceHz: 2800,
					biteGainDb: 3.5,
					cabHighCutHz: 7600,
					distortionGain: 0.6,
					stereoSpread: 1.32,
					description: 'Sola Sound Tone Bender MkII fuzz into 100W Marshall stack.',
				},
				eq10Band: {
					hz30: 1.2,
					hz60: 2.8,
					hz120: 2.4,
					hz250: -0.6,
					hz500: 1.0,
					hz1000: 1.8,
					hz2500: 2.8,
					hz4000: 3.2,
					hz8000: 3.0,
					hz16000: 3.2,
				},
				saturation: { type: 'tape_warmth', drive: 0.5 },
				compressor: { threshold: -13, ratio: 2.3, attack: 30, release: 90, knee: 3 },
				stereoWidth: 1.35,
				gemSetup: {
					drums: {
						volumeDb: 0.6,
						eq: { sub: 3.0, punch: 3.2, attack: 3.0, air: 3.0 },
						saturation: 'tape_warmth',
						drive: 0.42,
						compRatio: 2.3,
						compAttack: 30,
						compRelease: 80,
						description: 'Massive live Ludwig kit room saturation.',
					},
					bass: {
						volumeDb: 0.9,
						eq: { subBass: 3.2, grit: 3.0, cutMids: -0.5, clarity: 2.8 },
						saturation: 'ampeg_svt',
						drive: 0.4,
						compRatio: 2.4,
						compAttack: 25,
						compRelease: 80,
						description: 'Heavy, round, driving bass groove.',
					},
					guitars: {
						volumeDb: 0.2,
						eq: { lowCut: 80, body: 2.5, bite: 3.2, sheen: 2.8 },
						saturation: 'marshall_jcm800',
						drive: 0.58,
						stereoWidth: 1.34,
						description: 'Fuzz-driven heavy riffs and swirling stereo panning.',
					},
					vocals: {
						volumeDb: 0.5,
						eq: { body: 1.0, clarity: 2.5, presence: 3.2, air: 3.2 },
						saturation: 'la2a_opto',
						drive: 0.28,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 90,
						description: 'Robert Plant expressive, raw, dynamic blues scream.',
					},
					synthsFx: {
						volumeDb: 0.3,
						eq: { lowMids: 1.0, presence: 2.0, air: 3.0 },
						saturation: 'tape_warmth',
						drive: 0.35,
						stereoWidth: 1.45,
						description: 'Theremin oscillations, tape reverse delay, and echo spin.',
					},
				},
			},
		],
	},

	// ─── 7. YNGWIE MALMSTEEN ───
	{
		id: 'yngwie_malmsteen',
		name: 'YNGWIE MALMSTEEN & JEFF GLIXMAN',
		title: 'Pioneers of Neo-Classical Heavy Metal & Shred Speed',
		category: 'metal_rock',
		era: '1984 - Present',
		country: 'Sweden 🇸🇪',
		bio: 'Created the neo-classical metal genre with Rising Force, Marching Out, Trilogy, combining Bach/Paganini violin harmonic runs with 50W Marshall Plexi stacks and DOD Overdrive.',
		albums: [
			{
				id: 'yngwie_rising_force',
				albumTitle: 'Rising Force (1984)',
				band: 'Yngwie Malmsteen',
				year: 1984,
				hardwareChain:
					'Record Plant LA Trident Console -> 3M 24-Track -> DOD 250 Preamp Overdrive -> 1971 Marshall 50W Plexi',
				soundSignature:
					'Lightning neo-classical arpeggio clarity, harmonized Baroque counterpoint, and scalloped Stratocaster singing sustain ("Black Star", "Far Beyond the Sun").',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'Eb Standard (Eb-Ab-Db-Gb-Bb-Eb / A=415.3Hz)',
					baseFreqA4Hz: 415.3,
					centOffset: -100,
					harmonicResonanceCenterHz: 77.78,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 112,
					midScoopHz: 600,
					midScoopGainDb: -0.5,
					bitePresenceHz: 3500,
					biteGainDb: 3.6,
					cabHighCutHz: 8200,
					distortionGain: 0.65,
					stereoSpread: 1.36,
					description:
						'Fender Stratocaster with DiMarzio HS-3 pickups into DOD 250 Preamp & Marshall 50W.',
				},
				eq10Band: {
					hz30: 0.8,
					hz60: 2.2,
					hz120: 2.0,
					hz250: -1.0,
					hz500: 0.8,
					hz1000: 1.6,
					hz2500: 2.8,
					hz4000: 3.4,
					hz8000: 3.6,
					hz16000: 3.8,
				},
				saturation: { type: 'marshall_jcm800', drive: 0.45 },
				compressor: { threshold: -13, ratio: 2.0, attack: 35, release: 90, knee: 3 },
				stereoWidth: 1.36,
				gemSetup: {
					drums: {
						volumeDb: 0.3,
						eq: { sub: 2.2, punch: 2.8, attack: 3.2, air: 3.4 },
						saturation: 'ssl_vca',
						drive: 0.32,
						compRatio: 2.2,
						compAttack: 30,
						compRelease: 80,
						description: 'Barriemore Barlow tight classical-rock dynamic drumming.',
					},
					bass: {
						volumeDb: 0.7,
						eq: { subBass: 2.6, grit: 2.8, cutMids: -0.8, clarity: 3.2 },
						saturation: 'ampeg_svt',
						drive: 0.35,
						compRatio: 2.3,
						compAttack: 25,
						compRelease: 80,
						description: 'Jens Johansson & Yngwie tight neo-classical pedal bass.',
					},
					guitars: {
						volumeDb: 0.6,
						eq: { lowCut: 95, body: 2.0, bite: 3.6, sheen: 3.8 },
						saturation: 'marshall_jcm800',
						drive: 0.6,
						stereoWidth: 1.4,
						description: 'Screaming harmonic minor arpeggios and vibrato sustain.',
					},
					vocals: {
						volumeDb: 0,
						eq: { body: 1.0, clarity: 2.0, presence: 2.5, air: 3.0 },
						saturation: 'neve_tube',
						drive: 0.2,
						compRatio: 1.8,
						compAttack: 30,
						compRelease: 100,
						description: 'Instrumental track focus with occasional acoustic choirs.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.4, presence: 2.2, air: 3.2 },
						saturation: 'tape_warmth',
						drive: 0.22,
						stereoWidth: 1.45,
						description: 'Jens Johansson Korg Polysix and Harpsichord fast dual solos.',
					},
				},
			},
		],
	},
]
