/**
 * Master of Masters Studio Pro — Complete Legendary Producers Discography Expansion.
 *
 * Fully calibrated album sound signatures, 10-band mastering EQ curves, hardware chains,
 * guitar toneprints, drum kits, and stem processing for all major historic productions by:
 * - Bob Rock
 * - Andy Sneap
 * - Terry Date
 * - Rick Rubin
 * - Martin Birch
 * - Brendan O'Brien
 * - Colin Richardson
 */

import type { MasterProducer } from './masters-database'

export const PRODUCERS_LEGENDS_EXPANDED_DISCOGRAPHY: MasterProducer[] = [
	{
		id: 'producer_bob_rock_complete',
		name: 'Bob Rock (Complete Discography)',
		title: 'The Multi-Platinum Master of Punch',
		category: 'metal_rock',
		era: '1989–2024',
		country: 'Canada',
		bio: 'O arquiteto do som mais poderoso e comercial da história do heavy metal. Produziu o lendário The Black Album do Metallica, Dr. Feelgood do Mötley Crüe, Sonic Temple do The Cult, Keep the Faith do Bon Jovi e The Offspring. Famoso pela caixa maciça de 6.5" Ludwig Black Beauty, bumbo com sub-graves titânicos e paredes de guitarras em camadas quádruplas gravadas no One On One Studios LA.',
		albums: [
			{
				id: 'metallica_black_album_1991',
				albumTitle: 'Metallica (The Black Album)',
				band: 'Metallica',
				year: 1991,
				hardwareChain:
					'One On One Studios LA, Neve 8078 & SSL 4000E, Mesa Boogie Mark IIC+ & Quad Preamp, Marshall JCM800, Tama Artstar II Kit, Ludwig Black Beauty Snare (40 mics), Studer A800 24-track, Mastered by George Marino at Sterling Sound',
				soundSignature:
					'A referência suprema da história da produção musical de rock/metal. Bumbo com impacto de 50Hz sem sobras, caixa de estalo sísmico e guitarras rítmicas com corpo denso e textura aveludada.',
				targetLufs: -12.8,
				tuningSignature: {
					standardName: 'E Standard (A=440Hz) / D Standard (Sad But True)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 110,
					midScoopHz: 680,
					midScoopGainDb: -3.0,
					bitePresenceHz: 3600,
					biteGainDb: 3.5,
					cabHighCutHz: 6800,
					distortionGain: 0.72,
					stereoSpread: 1.4,
					description:
						'Paredes de 4 a 6 camadas de guitarras ESP com captadores EMG 81 através de Mesa Mark IIC+, Marshall JCM800 e cabines Celestion V30.',
				},
				eq10Band: {
					hz30: 2.2,
					hz60: 3.8,
					hz120: 1.8,
					hz250: -1.0,
					hz500: -2.0,
					hz1000: 0.8,
					hz2500: 2.8,
					hz4000: 3.6,
					hz8000: 2.5,
					hz16000: 2.0,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.48,
				},
				compressor: {
					threshold: -17.0,
					ratio: 3.8,
					attack: 22.0,
					release: 110.0,
					knee: 3.2,
				},
				stereoWidth: 1.42,
				gemSetup: {
					drums: {
						volumeDb: 1.2,
						eq: { sub: 4.2, punch: 3.5, attack: 4.5, air: 2.5 },
						saturation: 'ssl_vca',
						drive: 0.45,
						compRatio: 4.5,
						compAttack: 18,
						compRelease: 90,
						description:
							'Lars Ulrich com o timbre mais famoso do metal: Ludwig Black Beauty com microfonação de sala rica no One On One.',
					},
					bass: {
						volumeDb: 0.2,
						eq: { subBass: 3.5, grit: 2.6, cutMids: -1.8, clarity: 2.8 },
						saturation: 'ampeg_svt',
						drive: 0.4,
						compRatio: 4.8,
						compAttack: 14,
						compRelease: 110,
						description:
							'Jason Newsted com baixo Warwick e Ampeg SVT com graves profundos dobrando com o bumbo.',
					},
					guitars: {
						volumeDb: 1.2,
						eq: { lowCut: 80, body: 2.5, bite: 3.6, sheen: 2.6 },
						saturation: 'mesa_rectifier',
						drive: 0.72,
						stereoWidth: 1.45,
						description:
							'Base pesada de James Hetfield com afinação D em Sad But True e solo de Kirk Hammett com Cry Baby Wah.',
					},
					vocals: {
						volumeDb: 1.4,
						eq: { body: 2.0, clarity: 2.8, presence: 3.5, air: 2.6 },
						saturation: 'la2a_opto',
						drive: 0.32,
						compRatio: 3.2,
						compAttack: 22,
						compRelease: 160,
						description:
							'James Hetfield aprendendo técnicas vocais de estúdio com Bob Rock, entregando calor e autoridade.',
					},
					synthsFx: {
						volumeDb: 0.0,
						eq: { lowMids: 0.8, presence: 2.0, air: 2.5 },
						saturation: 'pultec_tube',
						drive: 0.2,
						stereoWidth: 1.35,
						description: 'Arranjos orquestrais sutis de Michael Kamen em Nothing Else Matters.',
					},
				},
			},
			{
				id: 'motley_crue_dr_feelgood_1989',
				albumTitle: 'Dr. Feelgood',
				band: 'Mötley Crüe',
				year: 1989,
				hardwareChain:
					'Little Mountain Sound Studios Vancouver, SSL 4000E Console, Marshall JCM800 & Soldano SLO-100, DW Custom Drum Kit, Studer A800, Mastered by George Marino',
				soundSignature:
					'O ápice do hard rock dos anos 80. Bateria colossal de Tommy Lee com estalo cortante, baixo pulsante de Nikki Sixx e riffs pegajosos de Mick Mars.',
				targetLufs: -12.5,
				tuningSignature: {
					standardName: 'D Standard (1 step down)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 73.4,
				},
				guitarToneprint: {
					ampModel: 'soldano_slo100',
					cabResonanceHz: 112,
					midScoopHz: 700,
					midScoopGainDb: -2.2,
					bitePresenceHz: 3800,
					biteGainDb: 3.8,
					cabHighCutHz: 7000,
					distortionGain: 0.74,
					stereoSpread: 1.4,
					description: 'O timbre rasgado e encorpado de Mick Mars no Soldano SLO-100 afinado em D.',
				},
				eq10Band: {
					hz30: 2.0,
					hz60: 3.5,
					hz120: 1.6,
					hz250: -0.8,
					hz500: -1.6,
					hz1000: 0.9,
					hz2500: 3.0,
					hz4000: 3.8,
					hz8000: 2.8,
					hz16000: 2.2,
				},
				saturation: {
					type: 'soldano_slo100',
					drive: 0.52,
				},
				compressor: {
					threshold: -16.5,
					ratio: 4.0,
					attack: 20.0,
					release: 95.0,
					knee: 3.5,
				},
				stereoWidth: 1.42,
				gemSetup: {
					drums: {
						volumeDb: 1.2,
						eq: { sub: 4.0, punch: 3.4, attack: 4.5, air: 2.6 },
						saturation: 'ssl_vca',
						drive: 0.44,
						compRatio: 4.6,
						compAttack: 16,
						compRelease: 85,
						description:
							'Tommy Lee com som de bateria poderoso, dinâmico e estalo de caixa inesquecível em Kickstart My Heart.',
					},
					bass: {
						volumeDb: 0.1,
						eq: { subBass: 3.4, grit: 2.7, cutMids: -1.6, clarity: 2.9 },
						saturation: 'ampeg_svt',
						drive: 0.42,
						compRatio: 5.0,
						compAttack: 12,
						compRelease: 100,
						description: 'Nikki Sixx com baixo Spector/Gibson Thunderbird roncando nos graves.',
					},
					guitars: {
						volumeDb: 1.1,
						eq: { lowCut: 78, body: 2.4, bite: 3.8, sheen: 2.8 },
						saturation: 'soldano_slo100',
						drive: 0.75,
						stereoWidth: 1.45,
						description: 'Mick Mars com guitarras dobradas em afinação D com ataque agressivo.',
					},
					vocals: {
						volumeDb: 1.1,
						eq: { body: 1.8, clarity: 2.8, presence: 3.5, air: 2.6 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.3,
						compAttack: 20,
						compRelease: 150,
						description:
							'Vince Neil com presença cortante e coros de arena massivos com Steven Tyler e Bryan Adams.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 0.8, presence: 2.2, air: 2.6 },
						saturation: 'pultec_tube',
						drive: 0.24,
						stereoWidth: 1.4,
						description:
							'Sons de sirenes, buzinas de moto e sintetizadores de apoio em Kickstart My Heart.',
					},
				},
			},
			{
				id: 'the_cult_sonic_temple_1989',
				albumTitle: 'Sonic Temple',
				band: 'The Cult',
				year: 1989,
				hardwareChain:
					'Little Mountain Sound Vancouver, Neve Console, Marshall JCM800 & 1959 Plexi, Gretsch White Falcon, Studer A800',
				soundSignature:
					'Hard rock clássico e grandioso. Riffs icônicos de Billy Duffy em Fire Woman com muito sustain, ambiência rica e vocal monumental de Ian Astbury.',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'E Standard (440Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 108,
					midScoopHz: 650,
					midScoopGainDb: -1.8,
					bitePresenceHz: 3500,
					biteGainDb: 3.4,
					cabHighCutHz: 6800,
					distortionGain: 0.68,
					stereoSpread: 1.38,
					description:
						'O lendário som da Gretsch White Falcon com Marshall JCM800 e Boss SD-1 de Billy Duffy.',
				},
				eq10Band: {
					hz30: 1.6,
					hz60: 3.0,
					hz120: 1.5,
					hz250: -0.7,
					hz500: -1.4,
					hz1000: 0.9,
					hz2500: 2.8,
					hz4000: 3.4,
					hz8000: 2.6,
					hz16000: 2.0,
				},
				saturation: {
					type: 'marshall_jcm800',
					drive: 0.46,
				},
				compressor: {
					threshold: -17.5,
					ratio: 3.6,
					attack: 22.0,
					release: 110.0,
					knee: 3.2,
				},
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0.9,
						eq: { sub: 3.5, punch: 2.8, attack: 4.0, air: 2.4 },
						saturation: 'ssl_vca',
						drive: 0.38,
						compRatio: 4.2,
						compAttack: 18,
						compRelease: 95,
						description: 'Mickey Curry com bumbo e caixa poderosos gravados por Bob Rock.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.0, grit: 2.4, cutMids: -1.6, clarity: 2.7 },
						saturation: 'ampeg_svt',
						drive: 0.38,
						compRatio: 4.5,
						compAttack: 14,
						compRelease: 115,
						description: 'Jamie Stewart com linhas de baixo quentes e sólidas nos graves.',
					},
					guitars: {
						volumeDb: 1.1,
						eq: { lowCut: 80, body: 2.3, bite: 3.5, sheen: 2.6 },
						saturation: 'marshall_jcm800',
						drive: 0.68,
						stereoWidth: 1.42,
						description:
							'Riffs monumentais de Fire Woman e Sun King com chorus estéreo e eco analógico.',
					},
					vocals: {
						volumeDb: 1.2,
						eq: { body: 1.9, clarity: 2.7, presence: 3.3, air: 2.5 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.1,
						compAttack: 22,
						compRelease: 160,
						description: 'Ian Astbury em performance vocal arrebatadora com calor de console Neve.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 0.8, presence: 2.0, air: 2.5 },
						saturation: 'pultec_tube',
						drive: 0.22,
						stereoWidth: 1.4,
						description: 'Camadas de apoio e percussões sutis.',
					},
				},
			},
		],
	},
	{
		id: 'producer_andy_sneap_complete',
		name: 'Andy Sneap (Complete Discography)',
		title: 'The Heavy Metal Precision General',
		category: 'metal_rock',
		era: '1999–2025',
		country: 'UK',
		bio: 'O produtor e engenheiro de mixagem mais influente do heavy metal moderno. Produziu e mixou Judas Priest (Firepower, Invincible Shield), Megadeth (Endgame, Dystopia), Accept (Blood of the Nations), Nevermore, Arch Enemy, Testament, Exodus, Kreator, Dimmu Borgir e Dream Theater. Inventor do padrão de guitarra Peavey 5150 com TS9 Tube Screamer, graves cirúrgicos sem embolamento e impacto percussivo devastador.',
		albums: [
			{
				id: 'judas_priest_firepower_2018',
				albumTitle: 'Firepower',
				band: 'Judas Priest',
				year: 2018,
				hardwareChain:
					'Backstage Studios UK, EVH 5150 III & Marshall JCM800, Ibanez TS9, Sonor SQ2 Drum Kit, SSL G-Bus Compressor, Dangerous Music BAX EQ, Mastered by Ted Jensen',
				soundSignature:
					'O renascimento triunfal do Judas Priest. Guitarras cortantes com ataque de palheta metálico, bumbo e caixa com definição cirúrgica e Rob Halford cortando com potência soberana.',
				targetLufs: -10.5,
				tuningSignature: {
					standardName: 'E Standard (440Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.4,
				},
				guitarToneprint: {
					ampModel: 'peavey_5150',
					cabResonanceHz: 110,
					midScoopHz: 650,
					midScoopGainDb: -1.5,
					bitePresenceHz: 4200,
					biteGainDb: 4.2,
					cabHighCutHz: 7400,
					distortionGain: 0.82,
					stereoSpread: 1.45,
					description:
						'O lendário timbre de Andy Sneap: EVH 5150 III com boost de Ibanez TS9 cortando os subgraves antes do ganho para foco cirúrgico.',
				},
				eq10Band: {
					hz30: 1.8,
					hz60: 3.4,
					hz120: 2.0,
					hz250: -0.5,
					hz500: -1.2,
					hz1000: 1.1,
					hz2500: 3.2,
					hz4000: 3.9,
					hz8000: 2.8,
					hz16000: 2.4,
				},
				saturation: {
					type: 'peavey_5150',
					drive: 0.58,
				},
				compressor: {
					threshold: -15.5,
					ratio: 4.2,
					attack: 16.0,
					release: 80.0,
					knee: 3.8,
				},
				stereoWidth: 1.45,
				gemSetup: {
					drums: {
						volumeDb: 1.1,
						eq: { sub: 3.8, punch: 3.2, attack: 4.4, air: 2.6 },
						saturation: 'ssl_vca',
						drive: 0.45,
						compRatio: 5.0,
						compAttack: 15,
						compRelease: 75,
						description:
							'Scott Travis com bumbos duplos velozes e estalo percussivo perfeito em Lightning Strike.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.4, grit: 2.9, cutMids: -1.5, clarity: 3.1 },
						saturation: 'darkglass_b7k',
						drive: 0.48,
						compRatio: 5.4,
						compAttack: 10,
						compRelease: 90,
						description: 'Ian Hill com baixo sólido travando as notas fundamentais com o bumbo.',
					},
					guitars: {
						volumeDb: 1.3,
						eq: { lowCut: 75, body: 2.5, bite: 4.0, sheen: 2.8 },
						saturation: 'peavey_5150',
						drive: 0.78,
						stereoWidth: 1.46,
						description:
							'Richie Faulkner e Glenn Tipton com duelos de guitarras gêmeas de ataque supersônico.',
					},
					vocals: {
						volumeDb: 1.0,
						eq: { body: 1.8, clarity: 2.9, presence: 3.6, air: 2.6 },
						saturation: 'la2a_opto',
						drive: 0.32,
						compRatio: 3.5,
						compAttack: 18,
						compRelease: 140,
						description: 'Rob Halford com os agudos mais poderosos do metal britânico.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 0.8, presence: 2.0, air: 2.6 },
						saturation: 'pultec_tube',
						drive: 0.22,
						stereoWidth: 1.4,
						description: 'Introduções épicas de sintetizadores em Guardians.',
					},
				},
			},
			{
				id: 'megadeth_endgame_2009',
				albumTitle: 'Endgame',
				band: 'Megadeth',
				year: 2009,
				hardwareChain:
					"Vic's Garage Studios San Marcos CA, Marshall JVM410H & Engl Powerball, Dean Guitars, Line 6 Amp Farm & Custom IRs, Mixed by Andy Sneap",
				soundSignature:
					'O som de thrash metal moderno definitivo de Dave Mustaine. Riffs de velocidade inacreditável em Head Crusher e Dialectic Chaos com precisão cirúrgica.',
				targetLufs: -10.8,
				tuningSignature: {
					standardName: 'D Standard (1 step down)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 73.4,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 112,
					midScoopHz: 680,
					midScoopGainDb: -1.6,
					bitePresenceHz: 4100,
					biteGainDb: 4.0,
					cabHighCutHz: 7300,
					distortionGain: 0.84,
					stereoSpread: 1.44,
					description:
						'Riffs ultra-articulados de Dave Mustaine e Chris Broderick com ataque de palheta em alta rotação.',
				},
				eq10Band: {
					hz30: 1.9,
					hz60: 3.5,
					hz120: 2.0,
					hz250: -0.6,
					hz500: -1.3,
					hz1000: 1.0,
					hz2500: 3.2,
					hz4000: 3.8,
					hz8000: 2.8,
					hz16000: 2.2,
				},
				saturation: {
					type: 'marshall_jcm800',
					drive: 0.56,
				},
				compressor: {
					threshold: -16.0,
					ratio: 4.3,
					attack: 15.0,
					release: 82.0,
					knee: 3.9,
				},
				stereoWidth: 1.44,
				gemSetup: {
					drums: {
						volumeDb: 1.1,
						eq: { sub: 3.8, punch: 3.2, attack: 4.5, air: 2.5 },
						saturation: 'ssl_vca',
						drive: 0.44,
						compRatio: 5.0,
						compAttack: 14,
						compRelease: 75,
						description: 'Shawn Drover com bumbo de alta velocidade e pratos cortantes.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.3, grit: 2.8, cutMids: -1.5, clarity: 3.0 },
						saturation: 'darkglass_b7k',
						drive: 0.46,
						compRatio: 5.2,
						compAttack: 11,
						compRelease: 92,
						description: 'James LoMenzo com baixo estalado sustentando os riffs rápidos.',
					},
					guitars: {
						volumeDb: 1.3,
						eq: { lowCut: 75, body: 2.4, bite: 4.1, sheen: 2.8 },
						saturation: 'marshall_jcm800',
						drive: 0.78,
						stereoWidth: 1.46,
						description: 'Solos alternados entre Mustaine e Broderick com nitidez absoluta.',
					},
					vocals: {
						volumeDb: 0.9,
						eq: { body: 1.7, clarity: 2.8, presence: 3.4, air: 2.4 },
						saturation: 'la2a_opto',
						drive: 0.32,
						compRatio: 3.4,
						compAttack: 18,
						compRelease: 140,
						description: 'Mustaine com vocais rasgados e diretos cortando na mixagem.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 0.8, presence: 2.0, air: 2.5 },
						saturation: 'pultec_tube',
						drive: 0.2,
						stereoWidth: 1.4,
						description: 'Efeitos e introduções de guitarra limpa.',
					},
				},
			},
			{
				id: 'nevermore_dead_heart_2000',
				albumTitle: 'Dead Heart in a Dead World',
				band: 'Nevermore',
				year: 2000,
				hardwareChain:
					'Village Productions Tornillo TX, Peavey 5150 Block Letter, Schecter 7-String, Ibanez TS9, Mixed & Mastered by Andy Sneap',
				soundSignature:
					'O marco definitivo das guitarras de 7 cordas no metal mundial. Jeff Loomis criando a bíblia do timbre moderno de 7 cordas em afinação Bb.',
				targetLufs: -11.5,
				tuningSignature: {
					standardName: 'Bb Standard (7-string half-step down)',
					baseFreqA4Hz: 440.0,
					centOffset: -100,
					harmonicResonanceCenterHz: 58.27,
				},
				guitarToneprint: {
					ampModel: 'peavey_5150',
					cabResonanceHz: 92,
					midScoopHz: 620,
					midScoopGainDb: -1.8,
					bitePresenceHz: 4000,
					biteGainDb: 4.2,
					cabHighCutHz: 7200,
					distortionGain: 0.86,
					stereoSpread: 1.45,
					description:
						'O clássico som de 7 cordas de Jeff Loomis em Enemies of Reality e Narcosynthesis: peso brutal e clareza perfeita.',
				},
				eq10Band: {
					hz30: 2.2,
					hz60: 3.6,
					hz120: 2.0,
					hz250: -0.6,
					hz500: -1.4,
					hz1000: 1.0,
					hz2500: 3.2,
					hz4000: 3.8,
					hz8000: 2.7,
					hz16000: 2.2,
				},
				saturation: {
					type: 'peavey_5150',
					drive: 0.6,
				},
				compressor: {
					threshold: -16.2,
					ratio: 4.4,
					attack: 16.0,
					release: 85.0,
					knee: 3.8,
				},
				stereoWidth: 1.45,
				gemSetup: {
					drums: {
						volumeDb: 1.0,
						eq: { sub: 3.7, punch: 3.1, attack: 4.3, air: 2.4 },
						saturation: 'ssl_vca',
						drive: 0.44,
						compRatio: 4.8,
						compAttack: 16,
						compRelease: 80,
						description: 'Van Williams com bumbo com clique perfurante e caixa com estalo seco.',
					},
					bass: {
						volumeDb: 0.0,
						eq: { subBass: 3.4, grit: 2.8, cutMids: -1.6, clarity: 3.0 },
						saturation: 'darkglass_b7k',
						drive: 0.46,
						compRatio: 5.2,
						compAttack: 12,
						compRelease: 95,
						description: 'Jim Sheppard com graves colossais afinados em Bb.',
					},
					guitars: {
						volumeDb: 1.3,
						eq: { lowCut: 70, body: 2.5, bite: 4.0, sheen: 2.8 },
						saturation: 'peavey_5150',
						drive: 0.8,
						stereoWidth: 1.46,
						description:
							'Jeff Loomis com sweeps e arpejos inacreditáveis e riffs em Believe in Nothing.',
					},
					vocals: {
						volumeDb: 1.1,
						eq: { body: 1.9, clarity: 2.8, presence: 3.5, air: 2.5 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.3,
						compAttack: 20,
						compRelease: 150,
						description:
							'Warrel Dane com alcance dramático e voz operística/rasgada inconfundível.',
					},
					synthsFx: {
						volumeDb: 0.3,
						eq: { lowMids: 1.0, presence: 2.2, air: 2.8 },
						saturation: 'pultec_tube',
						drive: 0.25,
						stereoWidth: 1.42,
						description: 'Violões de 7 cordas e ambiências obscuras.',
					},
				},
			},
		],
	},
	{
		id: 'producer_terry_date_complete',
		name: 'Terry Date (Complete Discography)',
		title: 'The Organic Heavyweight Architect',
		category: 'metal_rock',
		era: '1989–2024',
		country: 'USA',
		bio: 'Produtor lendário que definiu o som do groove metal e do rock alternativo dos anos 90. Produziu Pantera (Cowboys from Hell, Vulgar Display of Power, Far Beyond Driven, The Great Southern Trendkill), Soundgarden (Badmotorfinger), Deftones (Around the Fur, White Pony), White Zombie (Astro-Creep 2000) e Overkill. Mestre em capturar bumbos percussivos, guitarras em estado bruto com afinações graves e dinâmica sem filtros estéreis.',
		albums: [
			{
				id: 'pantera_vulgar_display_1992',
				albumTitle: 'Vulgar Display of Power',
				band: 'Pantera',
				year: 1992,
				hardwareChain:
					'Pantego Sound Studios Texas, Soundcraft Console, Randall RG100ES & Century 200, MXR 6-Band EQ, Furman PQ4 Parametric, Tama Artstar II, Mastered by Bob Ludwig',
				soundSignature:
					'O maior marco do groove metal mundial. O lendário "Scoop de Médios" e o ataque de transiente da navalha de Dimebag Darrell com o bumbo metralhadora de Vinnie Paul em Walk e Fucking Hostile.',
				targetLufs: -11.8,
				tuningSignature: {
					standardName: 'D Standard (down 1/4 step: A425Hz)',
					baseFreqA4Hz: 425.0,
					centOffset: -60,
					harmonicResonanceCenterHz: 70.8,
				},
				guitarToneprint: {
					ampModel: 'boss_hm2_buzzsaw',
					cabResonanceHz: 115,
					midScoopHz: 800,
					midScoopGainDb: -5.0,
					bitePresenceHz: 4500,
					biteGainDb: 5.0,
					cabHighCutHz: 7600,
					distortionGain: 0.9,
					stereoSpread: 1.42,
					description:
						'O lendário som transistorizado de Dimebag: Randall Solid State com boost furioso de Furman PQ4 cortando 800Hz e explodindo nos 4.5kHz.',
				},
				eq10Band: {
					hz30: 2.5,
					hz60: 4.0,
					hz120: 1.5,
					hz250: -1.2,
					hz500: -3.5,
					hz1000: 0.5,
					hz2500: 3.5,
					hz4000: 4.5,
					hz8000: 3.0,
					hz16000: 2.0,
				},
				saturation: {
					type: 'boss_hm2_buzzsaw',
					drive: 0.65,
				},
				compressor: {
					threshold: -15.5,
					ratio: 4.5,
					attack: 12.0,
					release: 75.0,
					knee: 4.0,
				},
				stereoWidth: 1.42,
				gemSetup: {
					drums: {
						volumeDb: 1.3,
						eq: { sub: 4.4, punch: 3.8, attack: 5.0, air: 2.5 },
						saturation: 'ssl_vca',
						drive: 0.5,
						compRatio: 5.2,
						compAttack: 12,
						compRelease: 70,
						description:
							'Vinnie Paul com o som de bumbo e caixa mais percussivo e impactante do heavy metal.',
					},
					bass: {
						volumeDb: 0.2,
						eq: { subBass: 3.8, grit: 2.8, cutMids: -2.0, clarity: 3.0 },
						saturation: 'ampeg_svt',
						drive: 0.44,
						compRatio: 5.0,
						compAttack: 12,
						compRelease: 95,
						description:
							'Rex Brown preenchendo com peso nos médios-graves o espaço do scoop de Dimebag.',
					},
					guitars: {
						volumeDb: 1.4,
						eq: { lowCut: 75, body: 2.0, bite: 4.5, sheen: 2.8 },
						saturation: 'boss_hm2_buzzsaw',
						drive: 0.85,
						stereoWidth: 1.45,
						description: 'Dimebag Darrell com harmônicos de alavanca e riffs de groove esmagador.',
					},
					vocals: {
						volumeDb: 1.1,
						eq: { body: 1.8, clarity: 2.8, presence: 3.6, air: 2.4 },
						saturation: 'la2a_opto',
						drive: 0.35,
						compRatio: 3.5,
						compAttack: 18,
						compRelease: 140,
						description:
							'Phil Anselmo com entrega violenta, crua e visceral gravada sem firulas digitais.',
					},
					synthsFx: {
						volumeDb: 0.0,
						eq: { lowMids: 0.0, presence: 0.0, air: 0.0 },
						saturation: 'pultec_tube',
						drive: 0.0,
						stereoWidth: 1.0,
						description: 'Sem sintetizadores — 100% poder físico analógico de estúdio.',
					},
				},
			},
			{
				id: 'deftones_white_pony_2000',
				albumTitle: 'White Pony',
				band: 'Deftones',
				year: 2000,
				hardwareChain:
					'The Plant Recording Studios Sausalito CA, Neve 8068, Marshall JCM800 & Rivera Knucklehead, Tama Starclassic, Studer A800, Mastered by Howie Weinberg',
				soundSignature:
					'Obra-prima do rock alternativo/art metal. Bateria de Abe Cunningham com ar de sala e pegada fantasma incomparável, guitarras em Drop C etéreas e vocais sussurrados/gritados de Chino Moreno.',
				targetLufs: -12.0,
				tuningSignature: {
					standardName: 'Drop C (C G C F A D)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 65.4,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 104,
					midScoopHz: 660,
					midScoopGainDb: -1.8,
					bitePresenceHz: 3600,
					biteGainDb: 3.5,
					cabHighCutHz: 6900,
					distortionGain: 0.72,
					stereoSpread: 1.4,
					description:
						'O som etéreo e esmagador de Stephen Carpenter em Change (In the House of Flies) e Digital Bath.',
				},
				eq10Band: {
					hz30: 2.0,
					hz60: 3.4,
					hz120: 1.8,
					hz250: -0.6,
					hz500: -1.2,
					hz1000: 0.9,
					hz2500: 2.8,
					hz4000: 3.5,
					hz8000: 2.6,
					hz16000: 2.2,
				},
				saturation: {
					type: 'marshall_jcm800',
					drive: 0.5,
				},
				compressor: {
					threshold: -17.0,
					ratio: 3.8,
					attack: 20.0,
					release: 105.0,
					knee: 3.4,
				},
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 1.0,
						eq: { sub: 3.6, punch: 3.0, attack: 4.0, air: 2.6 },
						saturation: 'ssl_vca',
						drive: 0.4,
						compRatio: 4.4,
						compAttack: 18,
						compRelease: 90,
						description:
							'Abe Cunningham com a caixa mais dinâmica, musical e viva do rock alternativo.',
					},
					bass: {
						volumeDb: 0.1,
						eq: { subBass: 3.4, grit: 2.5, cutMids: -1.5, clarity: 2.8 },
						saturation: 'ampeg_svt',
						drive: 0.4,
						compRatio: 4.8,
						compAttack: 14,
						compRelease: 105,
						description:
							'Chi Cheng com linhas de baixo pesadas, quentes e cheias de groove em Digital Bath.',
					},
					guitars: {
						volumeDb: 1.1,
						eq: { lowCut: 75, body: 2.4, bite: 3.6, sheen: 2.6 },
						saturation: 'marshall_jcm800',
						drive: 0.7,
						stereoWidth: 1.44,
						description:
							'Stephen Carpenter alternando entre texturas atmosféricas limpas e acordes de parede em Drop C.',
					},
					vocals: {
						volumeDb: 1.1,
						eq: { body: 1.8, clarity: 2.7, presence: 3.4, air: 2.8 },
						saturation: 'la2a_opto',
						drive: 0.3,
						compRatio: 3.2,
						compAttack: 22,
						compRelease: 160,
						description:
							'Chino Moreno com sussurros cheios de ar, delays espaciais e berros viscerais.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.0, presence: 2.4, air: 3.0 },
						saturation: 'pultec_tube',
						drive: 0.26,
						stereoWidth: 1.48,
						description:
							'Frank Delgado com sintetizadores Moog, samplers e scratches atmosféricos.',
					},
				},
			},
			{
				id: 'soundgarden_badmotorfinger_1991',
				albumTitle: 'Badmotorfinger',
				band: 'Soundgarden',
				year: 1991,
				hardwareChain:
					'Studio Litho & Avast! Recording Co Seattle, Neve Console, Mesa Boogie Dual Rectifier & Peavey VTM, Mastered by Howie Weinberg',
				soundSignature:
					'O grunge mais pesado e complexo dos anos 90. Afinações alternativas em Drop D e Drop C (Rusty Cage, Outshined, Jesus Christ Pose) com a voz lendária de Chris Cornell.',
				targetLufs: -12.5,
				tuningSignature: {
					standardName: 'Drop D (D A D G B E) / Drop B (Rusty Cage)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 73.4,
				},
				guitarToneprint: {
					ampModel: 'mesa_rectifier',
					cabResonanceHz: 110,
					midScoopHz: 650,
					midScoopGainDb: -1.8,
					bitePresenceHz: 3700,
					biteGainDb: 3.6,
					cabHighCutHz: 7000,
					distortionGain: 0.76,
					stereoSpread: 1.4,
					description:
						'Riffs pesadíssimos de Kim Thayil com wah-wah fixo e afinações estranhas em Rusty Cage.',
				},
				eq10Band: {
					hz30: 1.8,
					hz60: 3.2,
					hz120: 1.7,
					hz250: -0.7,
					hz500: -1.3,
					hz1000: 1.0,
					hz2500: 3.0,
					hz4000: 3.6,
					hz8000: 2.6,
					hz16000: 2.0,
				},
				saturation: {
					type: 'mesa_rectifier',
					drive: 0.52,
				},
				compressor: {
					threshold: -16.8,
					ratio: 3.9,
					attack: 18.0,
					release: 95.0,
					knee: 3.6,
				},
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 1.0,
						eq: { sub: 3.5, punch: 3.0, attack: 4.2, air: 2.4 },
						saturation: 'ssl_vca',
						drive: 0.42,
						compRatio: 4.6,
						compAttack: 16,
						compRelease: 85,
						description: 'Matt Cameron em performance magistral de polirritmia e força bruta.',
					},
					bass: {
						volumeDb: 0.1,
						eq: { subBass: 3.2, grit: 2.6, cutMids: -1.6, clarity: 2.8 },
						saturation: 'ampeg_svt',
						drive: 0.42,
						compRatio: 5.0,
						compAttack: 12,
						compRelease: 100,
						description:
							'Ben Shepherd com baixo agressivo e roncando nos graves em Jesus Christ Pose.',
					},
					guitars: {
						volumeDb: 1.2,
						eq: { lowCut: 75, body: 2.4, bite: 3.8, sheen: 2.6 },
						saturation: 'mesa_rectifier',
						drive: 0.74,
						stereoWidth: 1.42,
						description: 'Guitarras densas e pesadas de Kim Thayil e Chris Cornell.',
					},
					vocals: {
						volumeDb: 1.2,
						eq: { body: 1.9, clarity: 2.8, presence: 3.6, air: 2.6 },
						saturation: 'la2a_opto',
						drive: 0.32,
						compRatio: 3.4,
						compAttack: 20,
						compRelease: 150,
						description:
							'Chris Cornell no auge vocal de sua vida, atingindo notas inacreditáveis com drive natural.',
					},
					synthsFx: {
						volumeDb: 0.2,
						eq: { lowMids: 0.8, presence: 2.0, air: 2.5 },
						saturation: 'pultec_tube',
						drive: 0.2,
						stereoWidth: 1.38,
						description: 'Efeitos de feedback e ambiências de guitarra.',
					},
				},
			},
		],
	},
]
