import type { MasterProducer } from './masters-database'

export const PRODUCERS_ICONS_PROG_POP: MasterProducer[] = [
	// ─── 1. QUINCY JONES & BRUCE SWEDIEN (MICHAEL JACKSON) ───
	{
		id: 'quincy_swedien',
		name: 'QUINCY JONES & BRUCE SWEDIEN',
		title: "Architects of the World's Best-Selling Production & Acusonic 3D Stereo",
		category: 'prog_synth',
		era: '1978 - 1995',
		country: 'United States 🇺🇸',
		bio: 'Produced the undisputed pinnacle of sonic perfection (Thriller, Bad, Off the Wall, Dangerous) inventing the "Acusonic Recording Process" with uncompressed analog transient punch.',
		albums: [
			{
				id: 'mj_thriller',
				albumTitle: 'Thriller (1982)',
				band: 'Michael Jackson',
				year: 1982,
				hardwareChain:
					'Westlake Audio Studio A Harrison 4032 Desk -> 3M 32-Track Digital & Studer A800 -> Shure SM7B -> EMT 250 -> Pultec EQP-1A',
				soundSignature:
					'The global benchmark of pop/rock production: Ndugu Chancler & Jeff Porcaro punchy kick/snare, Louis Johnson thumb-slap bass ("Billie Jean"), Eddie Van Halen searing solo ("Beat It"), and Michael’s razor-sharp vocal beatboxing.',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 110,
					midScoopHz: 650,
					midScoopGainDb: -0.8,
					bitePresenceHz: 3400,
					biteGainDb: 3.0,
					cabHighCutHz: 8200,
					distortionGain: 0.55,
					stereoSpread: 1.36,
					description:
						'Eddie Van Halen modified Marshall 1959 Plexi & Steve Lukather rhythm funk riffs.',
				},
				eq10Band: {
					hz30: 1.5,
					hz60: 3.2,
					hz120: 2.2,
					hz250: -1.2,
					hz500: 0.8,
					hz1000: 1.4,
					hz2500: 2.6,
					hz4000: 3.2,
					hz8000: 3.8,
					hz16000: 4.5,
				},
				saturation: { type: 'neve_tube', drive: 0.28 },
				compressor: { threshold: -13, ratio: 2.0, attack: 35, release: 85, knee: 3 },
				stereoWidth: 1.42,
				gemSetup: {
					drums: {
						volumeDb: 0.6,
						eq: { sub: 3.2, punch: 3.6, attack: 3.8, air: 4.0 },
						saturation: 'ssl_vca',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 30,
						compRelease: 80,
						description:
							'Iconic Bruce Swedien wood-platform acoustic kick and crisp snare transient.',
					},
					bass: {
						volumeDb: 1.0,
						eq: { subBass: 3.5, grit: 2.6, cutMids: -1.0, clarity: 3.8 },
						saturation: 'sansamp_di',
						drive: 0.38,
						compRatio: 2.4,
						compAttack: 25,
						compRelease: 80,
						description: 'Louis Johnson Music Man StingRay thumb-slap & Minimoog bass layer.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 100, body: 1.8, bite: 3.0, sheen: 3.6 },
						saturation: 'marshall_jcm800',
						drive: 0.45,
						stereoWidth: 1.4,
						description: 'Steve Lukather & Paul Jackson Jr. funk strumming and Van Halen lead.',
					},
					vocals: {
						volumeDb: 0.8,
						eq: { body: 1.2, clarity: 2.8, presence: 3.5, air: 4.2 },
						saturation: 'la2a_opto',
						drive: 0.2,
						compRatio: 2.0,
						compAttack: 25,
						compRelease: 90,
						description: 'Michael Jackson Shure SM7B multi-tracked lead, breaths and falsetto.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.5, presence: 2.5, air: 3.8 },
						saturation: 'tape_warmth',
						drive: 0.22,
						stereoWidth: 1.48,
						description: 'Synclavier II, Yamaha GS-1, and Jerry Hey Horn Section punch.',
					},
				},
			},
			{
				id: 'mj_bad',
				albumTitle: 'Bad (1987)',
				band: 'Michael Jackson',
				year: 1987,
				hardwareChain:
					'Westlake Studio D SSL 4000E -> Mitsubishi X-850 32-Track Digital -> Neve 1073 -> Lexicon 480L',
				soundSignature:
					'Hyper-tight, ultra-crisp, explosive modern punch: "Smooth Criminal", "Bad", and "Man in the Mirror" audiophile clarity.',
				targetLufs: -12.5,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'soldano_slo100',
					cabResonanceHz: 112,
					midScoopHz: 700,
					midScoopGainDb: -1.0,
					bitePresenceHz: 3500,
					biteGainDb: 3.2,
					cabHighCutHz: 8400,
					distortionGain: 0.58,
					stereoSpread: 1.38,
					description:
						'Steve Stevens & David Williams razor funk and screaming hard-rock leads ("Dirty Diana").',
				},
				eq10Band: {
					hz30: 1.6,
					hz60: 3.4,
					hz120: 2.4,
					hz250: -1.4,
					hz500: 0.6,
					hz1000: 1.5,
					hz2500: 2.8,
					hz4000: 3.5,
					hz8000: 4.0,
					hz16000: 4.6,
				},
				saturation: { type: 'ssl_vca', drive: 0.32 },
				compressor: { threshold: -12, ratio: 2.2, attack: 30, release: 80, knee: 3 },
				stereoWidth: 1.44,
				gemSetup: {
					drums: {
						volumeDb: 0.8,
						eq: { sub: 3.4, punch: 3.8, attack: 4.0, air: 4.2 },
						saturation: 'ssl_vca',
						drive: 0.38,
						compRatio: 2.4,
						compAttack: 25,
						compRelease: 75,
						description: 'LinnDrum LM-2 sampled transients with live John Robinson punch.',
					},
					bass: {
						volumeDb: 1.0,
						eq: { subBass: 3.6, grit: 3.0, cutMids: -1.2, clarity: 4.0 },
						saturation: 'sansamp_di',
						drive: 0.4,
						compRatio: 2.5,
						compAttack: 20,
						compRelease: 75,
						description: 'Dual Roland D-50 & Minimoog synth bass + live bass snap.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 100, body: 1.8, bite: 3.2, sheen: 3.8 },
						saturation: 'soldano_slo100',
						drive: 0.5,
						stereoWidth: 1.42,
						description: 'Steve Stevens heavy rock soloing and razor-sharp rhythm lines.',
					},
					vocals: {
						volumeDb: 0.9,
						eq: { body: 1.2, clarity: 3.0, presence: 3.8, air: 4.5 },
						saturation: 'neve_tube',
						drive: 0.22,
						compRatio: 2.2,
						compAttack: 20,
						compRelease: 85,
						description: 'Michael Jackson aggressive vocal attacks, hiccups and harmonies.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.6, presence: 2.8, air: 4.0 },
						saturation: 'tape_warmth',
						drive: 0.25,
						stereoWidth: 1.5,
						description: 'Synclavier FM bells, digital brass stabs, and cinematic impacts.',
					},
				},
			},
		],
	},

	// ─── 2. PRINCE & SUSAN ROGERS (PAISLEY PARK) ───
	{
		id: 'prince_rogers',
		name: 'PRINCE & SUSAN ROGERS',
		title: 'The Minneapolis Sound & Eclectic Funk-Rock Geniuses',
		category: 'prog_synth',
		era: '1980 - 1995',
		country: 'United States 🇺🇸',
		bio: "Pioneered the revolutionary Minneapolis sound at Paisley Park and Sunset Sound (Purple Rain, 1999, Sign o' the Times), blending LinnDrum punch with roaring guitar solos and analog synths.",
		albums: [
			{
				id: 'prince_purple_rain',
				albumTitle: 'Purple Rain (1984)',
				band: 'Prince & The Revolution',
				year: 1984,
				hardwareChain:
					'Sunset Sound Custom API / DeMedio Console -> Studer A800 24-Track -> EMT 140 -> Boss BF-2 Flanger',
				soundSignature:
					'Emotional electric rock-funk power: Wendy & Lisa lush acoustic guitars, iconic Linn LM-1 flanged rimshot, and Prince’s soaring guitar solo ("Purple Rain").',
				targetLufs: -13.0,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 112,
					midScoopHz: 650,
					midScoopGainDb: -0.8,
					bitePresenceHz: 3400,
					biteGainDb: 3.2,
					cabHighCutHz: 8200,
					distortionGain: 0.62,
					stereoSpread: 1.38,
					description:
						'Hohner MadCat Telecaster into Boss DS-1 Distortion, BF-2 Flanger and Mesa/Marshall.',
				},
				eq10Band: {
					hz30: 1.2,
					hz60: 2.6,
					hz120: 2.0,
					hz250: -1.0,
					hz500: 0.8,
					hz1000: 1.4,
					hz2500: 2.6,
					hz4000: 3.2,
					hz8000: 3.6,
					hz16000: 4.0,
				},
				saturation: { type: 'tape_warmth', drive: 0.35 },
				compressor: { threshold: -13, ratio: 2.0, attack: 35, release: 90, knee: 3 },
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 0.5,
						eq: { sub: 2.6, punch: 3.2, attack: 3.5, air: 3.6 },
						saturation: 'ssl_vca',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 28,
						compRelease: 80,
						description: 'Linn LM-1 tuned kick and flanged snare/rimshot.',
					},
					bass: {
						volumeDb: 0.9,
						eq: { subBass: 3.0, grit: 2.8, cutMids: -0.8, clarity: 3.4 },
						saturation: 'sansamp_di',
						drive: 0.38,
						compRatio: 2.3,
						compAttack: 25,
						compRelease: 80,
						description: 'Brown Mark Fender Jazz Bass deep groove anchor.',
					},
					guitars: {
						volumeDb: 0.3,
						eq: { lowCut: 90, body: 2.0, bite: 3.2, sheen: 3.6 },
						saturation: 'marshall_jcm800',
						drive: 0.55,
						stereoWidth: 1.42,
						description: 'Prince crying guitar solos and Wendy Melvoin funk rhythm.',
					},
					vocals: {
						volumeDb: 0.7,
						eq: { body: 1.2, clarity: 2.6, presence: 3.4, air: 4.0 },
						saturation: 'la2a_opto',
						drive: 0.22,
						compRatio: 2.0,
						compAttack: 25,
						compRelease: 90,
						description: 'Prince emotional falsetto, screams and spoken intros.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.5, presence: 2.5, air: 3.5 },
						saturation: 'tape_warmth',
						drive: 0.25,
						stereoWidth: 1.48,
						description: 'Oberheim OB-8 strings, pads and Yamaha DX7 pianos.',
					},
				},
			},
		],
	},

	// ─── 3. HUGH PADGHAM (PHIL COLLINS) ───
	{
		id: 'hugh_padgham',
		name: 'HUGH PADGHAM & PHIL COLLINS',
		title: 'Pioneers of the Legendary Gated Reverb Drum & 80s Power Production',
		category: 'prog_synth',
		era: '1980 - 1995',
		country: 'United Kingdom 🇬🇧',
		bio: 'Invented the revolutionary Gated Reverb drum sound at The Town House on the SSL 4000E listen mic, producing Phil Collins (Face Value, No Jacket Required) and The Police (Synchronicity).',
		albums: [
			{
				id: 'phil_face_value',
				albumTitle: 'Face Value (1981)',
				band: 'Phil Collins',
				year: 1981,
				hardwareChain:
					'The Town House Studio 2 SSL 4000E Console -> Studer A800 -> SSL Listen Mic Compressor -> EMT 140 Plate',
				soundSignature:
					'The most iconic drum fill in history ("In the Air Tonight"): explosive gated room snare, Prophet-5 analog brass, and Phil’s intimate vocal delivery.',
				targetLufs: -13.2,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 110,
					midScoopHz: 600,
					midScoopGainDb: -0.6,
					bitePresenceHz: 3200,
					biteGainDb: 2.8,
					cabHighCutHz: 8000,
					distortionGain: 0.4,
					stereoSpread: 1.34,
					description: 'Daryl Stuermer & Eric Clapton clean compressed Stratocaster.',
				},
				eq10Band: {
					hz30: 1.5,
					hz60: 3.0,
					hz120: 2.2,
					hz250: -1.0,
					hz500: 0.8,
					hz1000: 1.5,
					hz2500: 2.8,
					hz4000: 3.2,
					hz8000: 3.6,
					hz16000: 4.0,
				},
				saturation: { type: 'ssl_vca', drive: 0.38 },
				compressor: { threshold: -13, ratio: 2.2, attack: 30, release: 85, knee: 3 },
				stereoWidth: 1.4,
				gemSetup: {
					drums: {
						volumeDb: 1.0,
						eq: { sub: 3.2, punch: 3.8, attack: 3.6, air: 3.8 },
						saturation: 'ssl_vca',
						drive: 0.45,
						compRatio: 2.8,
						compAttack: 20,
						compRelease: 65,
						description: 'Phil Collins massive SSL reverse-talkback gated Gretsch drum kit.',
					},
					bass: {
						volumeDb: 0.8,
						eq: { subBass: 3.2, grit: 2.5, cutMids: -0.8, clarity: 3.2 },
						saturation: 'sansamp_di',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 80,
						description: 'Moog Taurus bass pedals & John Giblin fretless bass warmth.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 95, body: 1.8, bite: 2.8, sheen: 3.2 },
						saturation: 'tape_warmth',
						drive: 0.3,
						stereoWidth: 1.35,
						description: 'Subtle clean chorused electric rhythm guitar.',
					},
					vocals: {
						volumeDb: 0.7,
						eq: { body: 1.2, clarity: 2.8, presence: 3.4, air: 4.0 },
						saturation: 'neve_tube',
						drive: 0.22,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 85,
						description: 'Phil Collins dry, close-mic dynamic lead vocals.',
					},
					synthsFx: {
						volumeDb: 0.5,
						eq: { lowMids: 1.8, presence: 2.5, air: 3.5 },
						saturation: 'tape_warmth',
						drive: 0.28,
						stereoWidth: 1.45,
						description: 'Sequential Circuits Prophet-5 and Roland CR-78 drum machine.',
					},
				},
			},
		],
	},

	// ─── 4. SAM PHILLIPS & FELTON JARVIS (ELVIS PRESLEY) ───
	{
		id: 'sam_phillips_elvis',
		name: 'SAM PHILLIPS & FELTON JARVIS',
		title: 'Pioneers of Rock and Roll & Analog Slapback Echo (Elvis Presley)',
		category: 'metal_rock',
		era: '1954 - 1977',
		country: 'United States 🇺🇸',
		bio: 'Recorded and engineered The King of Rock and Roll at Sun Studio Memphis and RCA Studio B Nashville, inventing tape slapback echo and explosive dynamic rock vocals.',
		albums: [
			{
				id: 'elvis_sun_sessions',
				albumTitle: 'The Sun Sessions (1954-1955)',
				band: 'Elvis Presley',
				year: 1955,
				hardwareChain:
					'Sun Studio RCA 76-D Custom Console -> Ampex 350 Tape Slapback Machine -> RCA 77-DX Ribbon Mic',
				soundSignature:
					'The origin of rock & roll: Scotty Moore slapback guitar, Bill Black standup slapping bass, and Elvis’s electric, passionate young voice ("That\'s All Right", "Mystery Train").',
				targetLufs: -14.0,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'fender_twin' as any,
					cabResonanceHz: 115,
					midScoopHz: 650,
					midScoopGainDb: -0.5,
					bitePresenceHz: 3000,
					biteGainDb: 3.0,
					cabHighCutHz: 7500,
					distortionGain: 0.35,
					stereoSpread: 1.25,
					description: 'Scotty Moore Gibson Super 400 through Ray Butts EchoSonic amplifier.',
				},
				eq10Band: {
					hz30: 0.5,
					hz60: 2.0,
					hz120: 2.2,
					hz250: -0.6,
					hz500: 1.0,
					hz1000: 1.6,
					hz2500: 2.6,
					hz4000: 2.8,
					hz8000: 2.8,
					hz16000: 3.0,
				},
				saturation: { type: 'tape_warmth', drive: 0.48 },
				compressor: { threshold: -14, ratio: 1.8, attack: 40, release: 110, knee: 4 },
				stereoWidth: 1.25,
				gemSetup: {
					drums: {
						volumeDb: 0,
						eq: { sub: 1.8, punch: 2.2, attack: 2.8, air: 2.5 },
						saturation: 'tape_warmth',
						drive: 0.35,
						compRatio: 1.8,
						compAttack: 40,
						compRelease: 100,
						description: 'D.J. Fontana minimal, tight rockabilly snare brushes.',
					},
					bass: {
						volumeDb: 1.0,
						eq: { subBass: 2.8, grit: 2.5, cutMids: -0.5, clarity: 3.0 },
						saturation: 'tape_warmth',
						drive: 0.38,
						compRatio: 2.0,
						compAttack: 30,
						compRelease: 90,
						description: 'Bill Black upright bass acoustic percussive string slap.',
					},
					guitars: {
						volumeDb: 0.2,
						eq: { lowCut: 85, body: 2.2, bite: 2.8, sheen: 2.8 },
						saturation: 'tape_warmth',
						drive: 0.35,
						stereoWidth: 1.28,
						description: 'Scotty Moore country-blues fingerpicking with 120ms tape slap.',
					},
					vocals: {
						volumeDb: 0.9,
						eq: { body: 1.4, clarity: 2.6, presence: 3.2, air: 3.5 },
						saturation: 'pultec_tube',
						drive: 0.3,
						compRatio: 2.0,
						compAttack: 25,
						compRelease: 95,
						description: 'Elvis Presley raw, charismatic, baritone-to-tenor Sun slapback echo.',
					},
					synthsFx: {
						volumeDb: 0,
						eq: { lowMids: 0.5, presence: 1.0, air: 1.5 },
						saturation: 'tape_warmth',
						drive: 0.15,
						stereoWidth: 1.2,
						description: 'Natural Memphis studio room reflections.',
					},
				},
			},
		],
	},

	// ─── 5. GLYN JOHNS & PETE TOWNSHEND (THE WHO) ───
	{
		id: 'glyn_johns_who',
		name: 'GLYN JOHNS & PETE TOWNSHEND',
		title: "Pioneers of The Who's Explosive Stadium Rock & The 3-Mic Drum Technique",
		category: 'metal_rock',
		era: '1965 - 1980',
		country: 'United Kingdom 🇬🇧',
		bio: 'Engineered and produced Who\'s Next and Quadrophenia, inventing the famous "Glyn Johns Drum Recording Technique" and marrying modular synthesizers with stadium-sized hard rock.',
		albums: [
			{
				id: 'who_whos_next',
				albumTitle: "Who's Next (1971)",
				band: 'The Who',
				year: 1971,
				hardwareChain:
					'Olympic Studios London Helios Console -> 3M 16-Track Tape -> ARP 2600 & VCS3 Synths -> Hiwatt Custom 100 Amps',
				soundSignature:
					"Monumental dynamic hard rock: Keith Moon's explosive wild drumming, John Entwistle's lead bass growl, Pete Townshend's windmill power chords, and Roger Daltrey's legendary scream in \"Won't Get Fooled Again\".",
				targetLufs: -13.2,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 110,
					midScoopHz: 600,
					midScoopGainDb: -0.6,
					bitePresenceHz: 3200,
					biteGainDb: 3.4,
					cabHighCutHz: 8000,
					distortionGain: 0.56,
					stereoSpread: 1.34,
					description:
						'1957 Gretsch 6120 Chet Atkins through Fender Tweed Bandmaster & Hiwatt DR103.',
				},
				eq10Band: {
					hz30: 1.2,
					hz60: 2.8,
					hz120: 2.2,
					hz250: -0.8,
					hz500: 0.8,
					hz1000: 1.5,
					hz2500: 2.6,
					hz4000: 3.2,
					hz8000: 3.4,
					hz16000: 3.8,
				},
				saturation: { type: 'tape_warmth', drive: 0.42 },
				compressor: { threshold: -13, ratio: 2.1, attack: 35, release: 95, knee: 3 },
				stereoWidth: 1.38,
				gemSetup: {
					drums: {
						volumeDb: 0.8,
						eq: { sub: 3.0, punch: 3.5, attack: 3.4, air: 3.6 },
						saturation: 'tape_warmth',
						drive: 0.4,
						compRatio: 2.3,
						compAttack: 30,
						compRelease: 80,
						description:
							'Keith Moon Premier double-bass kit with iconic Glyn Johns open stereo field.',
					},
					bass: {
						volumeDb: 1.0,
						eq: { subBass: 3.0, grit: 3.4, cutMids: -0.6, clarity: 3.6 },
						saturation: 'ampeg_svt',
						drive: 0.42,
						compRatio: 2.4,
						compAttack: 25,
						compRelease: 80,
						description: 'John Entwistle "The Ox" treble-boosted Hiwatt bass roar.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 90, body: 2.2, bite: 3.2, sheen: 3.2 },
						saturation: 'marshall_jcm800',
						drive: 0.52,
						stereoWidth: 1.36,
						description: 'Windmill power chords with explosive dynamic attack.',
					},
					vocals: {
						volumeDb: 0.6,
						eq: { body: 1.2, clarity: 2.6, presence: 3.4, air: 3.8 },
						saturation: 'neve_tube',
						drive: 0.25,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 90,
						description: 'Roger Daltrey colossal chest voice wails and final scream.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.5, presence: 2.5, air: 3.5 },
						saturation: 'tape_warmth',
						drive: 0.25,
						stereoWidth: 1.45,
						description: 'Lowrey Berkshire Deluxe organ processed through EMS VCS3 synthesizer.',
					},
				},
			},
		],
	},

	// ─── 6. IAN ANDERSON & TERRY ELLIS (JETHRO TULL) ───
	{
		id: 'ian_anderson_tull',
		name: 'IAN ANDERSON & TERRY ELLIS',
		title: 'Pioneers of Progressive Folk-Rock & Dynamic Acoustic-Electric Fusion',
		category: 'prog_synth',
		era: '1968 - 1980',
		country: 'United Kingdom 🇬🇧',
		bio: 'Produced the legendary Jethro Tull masterpieces (Aqualung, Thick as a Brick, Songs from the Wood), combining acoustic flutes, 12-string guitars, and heavy Marshall riffs.',
		albums: [
			{
				id: 'tull_aqualung',
				albumTitle: 'Aqualung (1971)',
				band: 'Jethro Tull',
				year: 1971,
				hardwareChain:
					'Island Studios London Custom Helios Console -> 3M 16-Track -> Neumann U67 -> Pultec EQP-1A',
				soundSignature:
					"Extreme dynamic contrast: delicate acoustic fingerpicking and Ian's frantic flute flutter-tonguing suddenly exploding into Martin Barre's iconic heavy Gibson Les Paul riffs.",
				targetLufs: -13.8,
				tuningSignature: {
					standardName: 'Standard E (A=440.0Hz)',
					baseFreqA4Hz: 440.0,
					centOffset: 0,
					harmonicResonanceCenterHz: 82.41,
				},
				guitarToneprint: {
					ampModel: 'marshall_jcm800',
					cabResonanceHz: 110,
					midScoopHz: 650,
					midScoopGainDb: -0.8,
					bitePresenceHz: 3200,
					biteGainDb: 3.2,
					cabHighCutHz: 8000,
					distortionGain: 0.58,
					stereoSpread: 1.34,
					description: 'Martin Barre 1958 Gibson Les Paul Junior straight into 100W Hiwatt stack.',
				},
				eq10Band: {
					hz30: 1.0,
					hz60: 2.4,
					hz120: 2.0,
					hz250: -0.8,
					hz500: 0.8,
					hz1000: 1.4,
					hz2500: 2.6,
					hz4000: 3.0,
					hz8000: 3.4,
					hz16000: 3.8,
				},
				saturation: { type: 'tape_warmth', drive: 0.38 },
				compressor: { threshold: -14, ratio: 1.9, attack: 40, release: 110, knee: 4 },
				stereoWidth: 1.36,
				gemSetup: {
					drums: {
						volumeDb: 0.4,
						eq: { sub: 2.4, punch: 2.8, attack: 3.2, air: 3.4 },
						saturation: 'tape_warmth',
						drive: 0.32,
						compRatio: 2.0,
						compAttack: 35,
						compRelease: 90,
						description: 'Clive Bunker crisp jazz-rock snare articulation and ride bell.',
					},
					bass: {
						volumeDb: 0.8,
						eq: { subBass: 2.8, grit: 2.6, cutMids: -0.6, clarity: 3.2 },
						saturation: 'ampeg_svt',
						drive: 0.35,
						compRatio: 2.2,
						compAttack: 25,
						compRelease: 85,
						description: 'Jeffrey Hammond-Hammond driving, melodic bass lines.',
					},
					guitars: {
						volumeDb: 0,
						eq: { lowCut: 90, body: 2.0, bite: 3.0, sheen: 3.4 },
						saturation: 'marshall_jcm800',
						drive: 0.52,
						stereoWidth: 1.38,
						description: 'Martin Barre ferocious Les Paul riffs paired with acoustic 6/12-strings.',
					},
					vocals: {
						volumeDb: 0.6,
						eq: { body: 1.2, clarity: 2.6, presence: 3.2, air: 3.8 },
						saturation: 'la2a_opto',
						drive: 0.22,
						compRatio: 2.0,
						compAttack: 30,
						compRelease: 95,
						description: 'Ian Anderson theatrical, dynamic storytelling voice and vocal breaths.',
					},
					synthsFx: {
						volumeDb: 0.4,
						eq: { lowMids: 1.2, presence: 2.8, air: 3.8 },
						saturation: 'pultec_tube',
						drive: 0.25,
						stereoWidth: 1.42,
						description:
							'Ian Anderson signature acoustic concert flute with aggressive overblowing.',
					},
				},
			},
		],
	},
]
